### ISSUE TITLE
package or1k-linux binutils

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#101]
New compiler/runtime needs it.

**Comment by fallen** [comment]
You mean a conda package?

**Comment by sbourdeauducq** [comment]
Since conda is what we use for distribution, yes.

**Comment by sbourdeauducq** [comment]
The package should include this patch:
https://sourceware.org/bugzilla/attachment.cgi?id=8474

**Comment by fallen** [comment]
Fixed in https://github.com/m-labs/artiq/commit/93a2e7fd85aef40930da95ed7765ce17cfc4d59a
