### ISSUE TITLE
CI conda uploads from win64 not working (was: missing  llvmlite-artiq 0.23.0.dev py35_4)

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#1011]
Anaconda packed uploads not working (was llvmlite-artiq 0.23.0.dev py35_4 doesn't exist for win64 making artiq uninstallable)

**Comment by jordens** [comment]
AFAICT I triggered the build, it was built and uploaded but now it doesn't exist anymore.
http://buildbot.m-labs.hk/builders/conda-win64/builds/250

**Comment by jordens** [comment]
probably hit the conda repo size limit. i deleted a bunch of packages on anaconda.

**Comment by jordens** [comment]
Was looking at the wrong package. Uploads still disappearing.

**Comment by jordens** [comment]
Uploaded manually but the problem persists.

**Comment by sbourdeauducq** [comment]
Since there is a workaround, it's not critical.

**Comment by jordens** [comment]
That's a bad idea.

**Comment by whitequark** [comment]
In the past it was solved by `conda update anaconda-client`.

**Comment by jordens** [comment]
Pretty sure I had tried that on the buildbot.

**Comment by whitequark** [comment]
No idea then. It also could be that the uploads failed at random, anaconda often has network issues, and by the time you manually uploaded the package that stopped.

**Comment by jordens** [comment]
I probably did five attempts at automatic uploading.

**Comment by sbourdeauducq** [comment]
Hydra + self-hosted conda channel does not have such issues.
