### ISSUE TITLE
SUServo: document connections/settings

### ISSUE THREAD

**Issue by hartytp** [m-labs/artiq#1015]
It would be helpful to document:

- On Urukul DIP switch 2 (hw is not zero-indexed) must be ON to enable SUServo. 
- Urukul DIP switch 1 also needs to be on for HW v 1.0 to select the AD9910 variant
- Less important: Urukul and Sampler also need to be connected with 2 EEM connectors (QSPI mode). 
- IMHO, it's not worth documenting that a clock is required for Urkul (like saying Kasli needs power). Might be worth commenting that the servo itself is agnostic about the clock frequency.

**Comment by jbqubit** [comment]
> IMHO, it's not worth documenting that a clock is required for Urkul

To a new user it may not be clear if clock is derived from DRTIO or external or from XO. Never hurts to reiterate frequency range and power.

**Comment by hartytp** [comment]
> To a new user it may not be clear if clock is derived from DRTIO or external or from XO. Never hurts to reiterate frequency range and power.

Right. I'm not saying that it's a bad thing to document this -- in the same way that we should definitely document Kasli's power supply requirements properly at some point -- just that it's not a SU-servo issue, but rather a more general Urukul issue. IMO, the SU-servo documentation should say "these are the servo-specific settings, everything else is a standard Urukul setup." I don't consider fully documenting Urukul to be within the scope of the SU-servo project; it's a separate project.

**Comment by jbqubit** [comment]
That makes sense. Keep the SU-servo docs to the diffs.
