### ISSUE TITLE
package aiohttp / install on travis

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#102]
Required for influxdb.

**Comment by fallen** [comment]
Done in https://github.com/m-labs/artiq/commit/a64c6a321bb505bee5f411f4d8131de14ee4dcd5

**Comment by jordens** [comment]
We don't need conda packaging for this (and many others) AFAICT. In most cases we can just install using pip (plays nicely with conda) on either the pypi tarballs or the github .zip files. Even if we have patched forks this should work fine and saves a lot of conda packaging/binstar work.

**Comment by jordens** [comment]
And the architecture independent packages (aiohttp, quamash etc) should be `noarch`. That saves tons of debugging and build time.
