### ISSUE TITLE
Sayma Ethernet high packet losses

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#1021]
When Sayma does successfully boot it often does not subsequently work with ```artiq_run```. This is using Sayma_AMC (TS190717-6) sent to Duke from HK -- now temporarily being testing at UMD. This is using Ethernet components validated to work in HK: SATA cable, SATA-SFP adapter, SFP-Ethernet module. Using my Ethernet cable and [switch](https://www.fs.com/products/35290.html). Builds I've tested include db4d187 and bcb9c3 and 8fd57e6ccb6e5070d3dc988a9d5550b295621d72. See attached for wireshark log. 

```
$ cat repository/misc/blink_led.pyfrom artiq.experiment import *


class BlinkSaymaLED(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.setattr_device("led0")
        self.setattr_device("led1")

        self.setattr_device("ttl_sma_out")


    @kernel
    def run(self):
        self.core.reset()
        self.ttl_sma_out.output()

        for i in range(10): 
            div = 1.0
            self.ttl_sma_out.pulse(1*us)
            delay(1000/div*ms)
            self.led0.pulse(1000/div*ms)
            delay(500/div*ms)
            self.led0.pulse(500/div*ms)
            delay(250/div*ms)
            self.led0.pulse(250/div*ms)
            delay(125/div*ms)
            self.led0.pulse(125/div*ms)
```

```
(artiq-dev) britton@artiqbuild:~$ ifconfig
enp0s31f6 Link encap:Ethernet  HWaddr 18:66:da:26:66:ae  
          inet addr:192.168.1.68  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::6dfb:223c:9a52:c5bd/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:9822210 errors:0 dropped:91 overruns:0 frame:0
          TX packets:12474139 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:6977223037 (6.9 GB)  TX bytes:1828491752 (1.8 GB)
          Interrupt:16 Memory:f7200000-f7220000 
```

```
$ sudo dumpcap
$ artiq_run repository/misc/blink_led.py
stop dumpcap
```

```
$ sudo dumpcap
$ ping 192.168.1.75
PING 192.168.1.75 (192.168.1.75) 56(84) bytes of data.
64 bytes from 192.168.1.75: icmp_seq=2 ttl=64 time=32.8 ms
64 bytes from 192.168.1.75: icmp_seq=6 ttl=64 time=32.7 ms
64 bytes from 192.168.1.75: icmp_seq=10 ttl=64 time=32.9 ms
64 bytes from 192.168.1.75: icmp_seq=11 ttl=64 time=33.0 ms
64 bytes from 192.168.1.75: icmp_seq=15 ttl=64 time=32.9 ms
64 bytes from 192.168.1.75: icmp_seq=16 ttl=64 time=32.9 ms
64 bytes from 192.168.1.75: icmp_seq=18 ttl=64 time=33.0 ms
64 bytes from 192.168.1.75: icmp_seq=19 ttl=64 time=33.0 ms
64 bytes from 192.168.1.75: icmp_seq=20 ttl=64 time=33.0 ms
64 bytes from 192.168.1.75: icmp_seq=21 ttl=64 time=32.9 ms
64 bytes from 192.168.1.75: icmp_seq=22 ttl=64 time=32.9 ms
64 bytes from 192.168.1.75: icmp_seq=24 ttl=64 time=32.9 ms
^C
--- 192.168.1.75 ping statistics ---
26 packets transmitted, 12 received, 53% packet loss, time 25244ms
rtt min/avg/max/mdev = 32.788/32.970/33.036/0.145 ms

stop dumpcap
```
[wireshark_enp0s31f6_20180530103446_5F35At.pcapng.zip](https://github.com/m-labs/artiq/files/2054371/wireshark_enp0s31f6_20180530103446_5F35At.pcapng.zip)

[wireshark_enp0s31f6_20180530102445_XbxFGU.pcapng.zip](https://github.com/m-labs/artiq/files/2054357/wireshark_enp0s31f6_20180530102445_XbxFGU.pcapng.zip)

**Comment by sbourdeauducq** [comment]
Apply TRST rework (@gkasprow) and/or use another switch.

**Comment by jbqubit** [comment]
Switched to using Netgear GS608 v4. This is same switch [used at M-Labs](https://github.com/m-labs/artiq/issues/854#issuecomment-380708051). @trxw points out that this switch is currently selling in two version v3 and v4. What version did M-Labs use?  Only two hosts attached to the switch. ARTIQ Master PC and Sayma. Still see packet loss. 

```
$ ping 192.168.1.75
PING 192.168.1.75 (192.168.1.75) 56(84) bytes of data.
64 bytes from 192.168.1.75: icmp_seq=2 ttl=64 time=67.6 ms
64 bytes from 192.168.1.75: icmp_seq=4 ttl=64 time=32.7 ms
64 bytes from 192.168.1.75: icmp_seq=5 ttl=64 time=32.8 ms
64 bytes from 192.168.1.75: icmp_seq=8 ttl=64 time=32.8 ms
64 bytes from 192.168.1.75: icmp_seq=9 ttl=64 time=32.8 ms
64 bytes from 192.168.1.75: icmp_seq=10 ttl=64 time=32.9 ms
^C
--- 192.168.1.75 ping statistics ---
10 packets transmitted, 6 received, 40% packet loss, time 9045ms
rtt min/avg/max/mdev = 32.795/38.652/67.609/12.950 ms
```

**Comment by sbourdeauducq** [comment]
> Only two hosts attached to the switch

Try without the switch then.

**Comment by sbourdeauducq** [comment]
Anyway, with that level of packet loss it is expected that you get that error when running kernels.
I actually had packet losses like this when using certain media converters, which is why I shipped the SFP/RJ45, but it seems there are other factors in the equation.

**Comment by gkasprow** [comment]
the ping time is very high. I'd expect below 10ms.
After you connect the switch, 2..3 first pings can be lost because it may take some time to discover the correct MAC address using ARP.

**Comment by jbqubit** [comment]
I applied TRST patch with a helping hand from @restelli. Very tricky! Helpful tools we used that were not available in my lab.
- [Chipquik SMD291 solder paste](https://www.amazon.com/ChipQuik-SMD-291-Clean-Syringe-Nozzle/dp/B00CM2A97S) -- so much better than regular solder paste! 
- prior to using solder wick applied [solder containing Bi](http://www.chipquik.com/store/product_info.php?products_id=630001) Chipquik SMDSWLTLFP32

Now back to running Sayma on [fs.com switch](https://www.fs.com/products/35290.html). Ping reports 0% packet loss.  

```
--- 192.168.1.75 ping statistics ---
69 packets transmitted, 69 received, 0% packet loss, time 68077ms
rtt min/avg/max/mdev = 32.764/33.258/43.353/1.676 ms
```

**Comment by jbqubit** [comment]
Ping time is often < 1 ms. But on occasion I see that it jumps to > 10 ms. Any idea why @sbourdeauducq ?

**Comment by jbqubit** [comment]
![image](https://user-images.githubusercontent.com/20543958/40748585-e6802b8c-642e-11e8-8885-538acd3db257.png)

**Comment by sbourdeauducq** [comment]
No, I've only seen low ping times.
