### ISSUE TITLE
Sayma stand alone setup instructions

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#1024]
Creating independent Issue from https://github.com/m-labs/artiq/issues/1019#issuecomment-393275565. 

@sbourdeauducq Do you have updated installation instructions for Sayma standalone? There are several groups that will be evaluating Sayma hardware and would benefit from a concise setup list. [This post](https://ssl.serverraum.org/lists-archive/artiq/2018-January/001176.html) is the most recent that I know about. Diffs presently are the following.
- no HMC830 patch -- HMC830 locks!
- apply 100 MHz (+10 dBm) to SMA clock input on RTM
- ```conda install --force jesd204b=0.6```

[This](https://github.com/jbqubit/sinara-testing/blob/master/sayma/tools/build-artiq.bash) is the script I'm using to automate my builds.

**Comment by sbourdeauducq** [comment]
The satellite variant with Kasli as master is an easy way to use Sayma, Metlino should be coming soon, builds for the satellite variant (AMC and RTM) for both Nix and Conda have been on Hydra for a while now, Sayma v2 does not need patching or other hacks, and flashing it is done just like the other ARTIQ boards. Closing.
