### ISSUE TITLE
suservo: gain parameterisation 

### ISSUE THREAD

**Issue by hartytp** [m-labs/artiq#1033]
- I would generally think of a PI controller as H=kp + ki/s
- IIUC, the current parameterization is: `gain=kp`; `corner=ki/kp` unless `kp=0` when `corner=ki`. Is that correct?
- I see the appeal of the way this is currently done. But, I think it might be easier to just parametrize by `kp` and `ki` without the need for any special casing. It's trivial for users to parametrize however they want in their code. 

Let me know if I've misunderstood something or if you have a strong motivation for keeping things as they are.

**Comment by jordens** [comment]
I went along the lines of the digital-servo. We change it if that's your preferred parametrizaion. I don't think there would be that much less special casing.

**Comment by hartytp** [comment]
`kp` and `ki` is my preference. But, as I said, I'm happy to be convinced otherwise.
