### ISSUE TITLE
Sayma SAWG produces distorted output at certain amplitudes

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#1039]
```python
from artiq.experiment import *

class SAWGTest(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.setattr_device("sawg1")

    @kernel
    def run(self):
        self.core.reset()
        self.sawg1.reset()
        delay(300 * us)

        self.sawg1.frequency0.set(10*MHz)
        self.sawg1.amplitude1.set(0.5)
```

Looks relatively normal:
![screenshot-2018-6-1 tek e scope](https://user-images.githubusercontent.com/720864/40828951-a108d1ee-65b4-11e8-8bb9-00f513e3e468.png)

Then change the amplitude to 0.2:
![screenshot-2018-6-1 tek e scope 1](https://user-images.githubusercontent.com/720864/40828987-c014135a-65b4-11e8-8243-87f358a5015f.png)

**Comment by sbourdeauducq** [comment]
Might be a duplicate of #1022 indeed - I am not sure.

**Comment by sbourdeauducq** [comment]
Also not fixed by JESD update to https://github.com/m-labs/jesd204b/commit/25fd79dbf9d5b9536482f11a4d716747479191ec

**Comment by marmeladapk** [comment]
Reproduced:

![tek00037](https://user-images.githubusercontent.com/24512604/41046189-39ba82b8-69aa-11e8-95ce-21996bafad6b.png)

Artiq: c28fe47, Misoc: 86c6fcb, Migen: 6425844, jesd204b: 25fd79d

**Comment by jordens** [comment]
Thanks.

**Comment by jbqubit** [comment]
@marmeladapk Thanks for reproducing! @jordens Do you think this could be SAWG (vs JESD)?

**Comment by hartytp** [comment]
Does this work for all sawgs? e.g. can I use `sawg0`?

**Comment by jordens** [comment]
@hartytp any channel

**Comment by hartytp** [comment]
Flashed this to the startup kernel:

```python
from artiq.experiment import *

class SAWGTest(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.setattr_device("sawg0")

    @kernel
    def run(self):
        self.core.reset()
        self.sawg0.reset()
        delay(300 * us)

        self.sawg0.frequency0.set(10*MHz)
        self.sawg0.amplitude1.set(0.2)
```

Hooked up microscope probes to Sayma https://github.com/hartytp/artiq/tree/sawg_probes

```
+----------+------+----------+
|  Group   | Name |  Value   |
+----------+------+----------+
|  sawg0   |  a1  |   0x0    |
| sawg0_a1 |  xo  |  0xf87   |
| sawg0_a1 |  yo  |  0xf87   |
| sawg0_b  | xo0  |  0x7f8c  |
| sawg0_b  | yo0  | 0xffb787 |
| sawg0_b  | xo1  |  0x62eb  |
| sawg0_b  | yo1  |  0x9a89  |
| sawg0_b  | xo2  |  0x92dc  |
| sawg0_b  | yo2  | 0xff984e |
| sawg0_b  | xo3  | 0xff9ce9 |
| sawg0_b  | yo3  | 0xff9622 |
+----------+------+----------+
```

**Comment by hartytp** [comment]
amplitude to 0.5 gives a good sine and

```
+----------+------+----------+
|  Group   | Name |  Value   |
+----------+------+----------+
|  sawg0   |  a1  |   0x0    |
| sawg0_a1 |  xo  |  0x26d3  |
| sawg0_a1 |  yo  |  0x26d3  |
| sawg0_b  | xo0  |  0x2ef2  |
| sawg0_b  | yo0  | 0xff21d6 |
| sawg0_b  | xo1  | 0xff3f38 |
| sawg0_b  | yo1  |  0x32b6  |
| sawg0_b  | xo2  |  0xe3a9  |
| sawg0_b  | yo2  |  0xd052  |
| sawg0_b  | xo3  | 0xffca1f |
| sawg0_b  | yo3  |  0x3105  |
+----------+------+----------+
```

**Comment by jbqubit** [comment]
@jordens Is this still open? cf https://irclog.whitequark.org/m-labs/2018-06-09#22299432; Closed status following commit implies to me that I can reproduce fix by rebuilding.

**Comment by sbourdeauducq** [comment]
@jbqubit Please try it, the Sayma in HK is currently broken. https://irclog.whitequark.org/m-labs/2018-06-09#1528542903-1528545687;

**Comment by hartytp** [comment]
This bug seems fixed now.

See the following video: https://drive.google.com/file/d/1_Wkg8eDb3q3fVKrkaSxhvNfwyYxdB2Y1/view?usp=sharing
