### ISSUE TITLE
Sayma SAWG frequency0.set(240*MHz) produces nonsense

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#1044]
Sayma SAWG frequency0.set(240\*MHz) produces nonsense. Frequencies below about 150\*MHz produce sinusoids. 

```python
from artiq.experiment import *


class SAWGTestSines(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.setattr_device("ttl_sma_out")
        self.sawgs = [self.get_device("sawg"+str(i)) for i in range(8)]

    @kernel
    def run(self):
        self.core.reset()
        delay(1*ms)

        for sawg in self.sawgs:
            sawg.reset()
            delay(1*us)
            sawg.amplitude1.set(.5)

            sawg.frequency0.set(240*MHz)
            
            delay(100*ns)

        while True:
            delay(0.5*ms)
            self.ttl_sma_out.pulse(0.6*ms)
```

![tek005](https://user-images.githubusercontent.com/20543958/40861139-fb1b0426-65b5-11e8-99c2-fe564a872167.png)

**Comment by jbqubit** [comment]
@sbourdeauducq Do you see this on your hardware?

**Comment by sbourdeauducq** [comment]
As pointed out elsewhere by Tom and Robert, SAWG tests are not relevant until further JESD204 testing and debugging.

**Comment by jbqubit** [comment]
I don't see any symptoms on my board suggesting JESD204b problems. I do see reproducible nonsense out of SAWG. Please take a look @jordens on Sayma in HK. Some additional examples...

```
from artiq.experiment import *


class SAWGTestSines(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.setattr_device("ttl_sma_out")
        self.sawgs = [self.get_device("sawg"+str(i)) for i in range(8)]

    @kernel
    def run(self):
        self.core.reset()
        delay(1*ms)

        for sawg in self.sawgs:
            sawg.reset()
            delay(1*us)
            sawg.amplitude1.set(.5)
            sawg.frequency0.set(50*MHz)
            delay(100*ns)

        while True:
            delay(0.5*ms)
            self.ttl_sma_out.pulse(0.6*ms)
```

## frequency0.set(50*MHz)

https://www.youtube.com/watch?v=au4JqPSl5d0
This exact same pattern repeats from run to run and from boot to boot. This isn't a JESD issue. 

## frequency0.set(244*MHz)

https://www.youtube.com/watch?v=0TQgnauXb4M

## frequency0.set(280*MHz)
![tek006_013](https://user-images.githubusercontent.com/20543958/41107315-1f77f70a-6a40-11e8-9081-3342e5177303.png)
This exact same pattern repeats from run to run and from boot to boot. This isn't a JESD issue.

**Comment by jbqubit** [comment]
@jordens Still broken using 5b73dd86.
