### ISSUE TITLE
Unable to start artiq_gui on Windows 32-bit machine

### ISSUE THREAD

**Issue by Justin318** [m-labs/artiq#105]
I tried to run artiq on a windows 32-bit machine. Installation using "conda instasll artiq" works and I am able to start artiq_master. As calling the artiq_gui, it throws the exception as in the picture below. 

![image](https://cloud.githubusercontent.com/assets/11168506/9415498/120b4e72-47fd-11e5-90c5-6543763de381.png)

This has been tested both in the standard windows cmd and starting from cygwin console as well. For both cases, it shows the same traceback sequence.

**Comment by fallen** [comment]
This is due to bug #39
