### ISSUE TITLE
Client can browser all files on master via Explorer?

### ISSUE THREAD

**Issue by KaifengC** [m-labs/artiq#1053]
Considering running `artiq_master --blind *` on PC_1 but open dashboard on PC_2. 
Then if you right click the `Explorer` on dashboard and select `Open file outside repository`, you'll be able to see all the folders (and *.py files) on PC_1.

Is that supposed to work like this? 
I think if one connected to the `master` on another computer and tried to `Open file outside repository`, he would want to submit a **local** experiment instead of seeing all files on the server.

**Comment by sbourdeauducq** [comment]
Yes, it is supposed to work like this. Experiments can use multiple files, and the client cannot know what to send. You can use a shared network folder to solve this problem.
