### ISSUE TITLE
Variant should be added to the identifier (gateware, firmware)

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#1060]
c.f. #1059

**Comment by hartytp** [comment]
:+1:

**Comment by sbourdeauducq** [comment]
The RTM gateware is the same for all variants.

**Comment by sbourdeauducq** [comment]
That's about the ARTIQ variant, not hardware versions.

**Comment by gkasprow** [comment]
OK, but to get rid of confusion when next HW releases arrives, we should check the board ID before loading ARTIQ.

**Comment by sbourdeauducq** [comment]
Alternatively: avoid breaking compatibility, or deprecate the current set of boards - they have plenty of bugs and fragile reworks anyway.

**Comment by hartytp** [comment]
Let's depreciate them. Maintaining software support for old boards gets very expensive and isn't worth it for a handful of quite hacked prototypes.

**Comment by gkasprow** [comment]
I mean protection feature that won't enable loading i.e. old firmware to new boards. Then user will get clear message instead of frustration that something does not work.
