### ISSUE TITLE
sayma_rtm builds broken

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#1062]
Fails because of passing a variant:
http://buildbot.m-labs.hk/builders/artiq-board/builds/1628
Fails because of passing no variant:
http://buildbot.m-labs.hk/builders/artiq-board/builds/1629

**Comment by jordens** [comment]
And `sayma_amc` fails because the rtm csr csv obviously doesn't exist.
http://buildbot.m-labs.hk/builders/artiq-board/builds/1630

**Comment by whitequark** [comment]
You should build the `artiq-sayma_rtm` package instead.
