### ISSUE TITLE
sayma: generate rtm csr map on the fly when building amc

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#1070]
Generating the RTM csv map on the fly is not that expensive and the only way to verify compatibility currently is looking at the gateware identifiers in the log anyway. Thus using the csv from the rtm build doesn't help with compat issues.
That would decouple the build and avoid at least some errors when testing and debugging.
c.f. #1062

**Comment by sbourdeauducq** [comment]
@whitequark wanted instead to make the rtm package a build dependency of the amc package.

**Comment by sbourdeauducq** [comment]
AMC-RTM link is now DRTIO-based so this is no longer an issue.
