### ISSUE TITLE
".dirty" in firmware version does not appear reliably

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#1074]
The version string is cached by cargo and recomputed when the contents of ``.git`` changes. This leads to inconsistencies around ``.dirty``, which depends on the whole repository contents and not only ``.git``.

Can be reproduced by compiling the firmware from a pristine git tree, then making a modification to the source, and recompiling without deleting the previous compilation results.

**Comment by whitequark** [comment]
Fixed. But this makes builds take 8 seconds regardless of whether they're fresh or not because of some issue with dependency tracking I never figured out.
