### ISSUE TITLE
AD9914 amplitude control

### ISSUE THREAD

**Issue by raghavendrasrinivas** [m-labs/artiq#108]
Is there any way to control the amplitude from the AD9914? The manual describes phase and frequency control but not amplitude.

**Comment by sbourdeauducq** [comment]
What should the amplitude unit be?

**Comment by raghavendrasrinivas** [comment]
Could we just leave it as a fraction?

**Comment by sbourdeauducq** [comment]
You mean a number between 0 (min) and 1 (max)?

**Comment by raghavendrasrinivas** [comment]
Yes. I think that's probably better than any absolute power or voltage value as most of the time the output is amplified anyway.

**Comment by whitequark** [comment]
@sbourdeauducq What do you want me to do?

**Comment by dhslichter** [comment]
Needs to be a new method which takes an amplitude between 0 and 1, converts to a 12-bit value, and writes to ASF register.

**Comment by raghavendrasrinivas** [comment]
diff --git a/artiq/coredevice/dds.py b/artiq/coredevice/dds.py
index e9e8303..9759ec2 100644
--- a/artiq/coredevice/dds.py
+++ b/artiq/coredevice/dds.py
@@ -89,6 +89,11 @@ class _DDSGeneric:
         word."""
         return pow/2**self.pow_width
 
+    @portable
+    def amplitude_to_asf(self, amplitude):
+        """Converts amplitude from scale of 0 to 1 to 0 to 2^12."""
+        return round(amplitude*0x0fff)
+
     @kernel
     def init(self):
         """Resets and initializes the DDS channel.
@@ -117,12 +122,13 @@ class _DDSGeneric:
         self.phase_mode = phase_mode
 
     @kernel
-    def set_mu(self, frequency, phase=0, phase_mode=_PHASE_MODE_DEFAULT):
+    def set_mu(self, frequency, phase=0, phase_mode=_PHASE_MODE_DEFAULT, amplitude=0x0fff):
         """Sets the DDS channel to the specified frequency and phase.
 
         This uses machine units (FTW and POW). The frequency tuning word width
         is 32, whereas the phase offset word width depends on the type of DDS
-        chip and can be retrieved via the ``pow_width`` attribute.
+        chip and can be retrieved via the ``pow_width`` attribute. The amplitude
+        width is 12.
 
         :param frequency: frequency to generate.
         :param phase: adds an offset, in turns, to the phase.
@@ -132,13 +138,14 @@ class _DDSGeneric:
         if phase_mode == _PHASE_MODE_DEFAULT:
             phase_mode = self.phase_mode
         syscall("dds_set", now_mu(), self.channel, frequency,
-                phase, phase_mode)
+                phase, phase_mode, amplitude)
 
     @kernel
-    def set(self, frequency, phase=0.0, phase_mode=_PHASE_MODE_DEFAULT):
+    def set(self, frequency, phase=0.0, phase_mode=_PHASE_MODE_DEFAULT,
+            amplitude=1.0):
         """Like ``set_mu``, but uses Hz and turns."""
         self.set_mu(self.frequency_to_ftw(frequency),
-                    self.turns_to_pow(phase), phase_mode)
+                    self.turns_to_pow(phase), phase_mode, self.amplitude_to_asf(amplitude))
 
 
 class AD9858(_DDSGeneric):
diff --git a/artiq/coredevice/runtime.py b/artiq/coredevice/runtime.py
index ae818b1..5fcaf56 100644
--- a/artiq/coredevice/runtime.py
+++ b/artiq/coredevice/runtime.py
@@ -25,7 +25,7 @@ _syscalls = {
     "dds_init": "Ii:n",
     "dds_batch_enter": "I:n",
     "dds_batch_exit": "n:n",
-    "dds_set": "Iiiii:n",
+    "dds_set": "Iiiiii:n",
 }
 
 
diff --git a/examples/master/ddb.pyon b/examples/master/ddb.pyon
index cafe5e5..443bba6 100644
--- a/examples/master/ddb.pyon
+++ b/examples/master/ddb.pyon
@@ -9,7 +9,7 @@
         "type": "local",
         "module": "artiq.coredevice.core",
         "class": "Core",
-        "arguments": {"ref_period": 1e-9}
+        "arguments": {"ref_period": 1.25e-9}
     },
 
     "pmt0": {
diff --git a/soc/runtime/dds.c b/soc/runtime/dds.c
index ad62988..0d5f0f6 100644
--- a/soc/runtime/dds.c
+++ b/soc/runtime/dds.c
@@ -7,19 +7,21 @@
 #include "dds.h"
 
 #define DURATION_WRITE (5 << RTIO_FINE_TS_WIDTH)
+#define DURATION_RESET_PULSE (50 << RTIO_FINE_TS_WIDTH)
+#define DURATION_RESET_RECOVERY (50 << RTIO_FINE_TS_WIDTH)
 
 #if defined DDS_AD9858
 /* Assume 8-bit bus */
 #define DURATION_INIT (7*DURATION_WRITE) /* not counting FUD */
-#define DURATION_PROGRAM (8*DURATION_WRITE) /* not counting FUD */
+#define DURATION_PROGRAM (8*DURATION_WRITE + DURATION_RESET_PULSE + DURATION_RESET_RECOVERY) /* not co
 
 #elif defined DDS_AD9914
 /* Assume 16-bit bus */
 /* DAC calibration takes max. 1ms as per datasheet */
-#define DURATION_DAC_CAL (147000 << RTIO_FINE_TS_WIDTH)
+#define DURATION_DAC_CAL (166666 << RTIO_FINE_TS_WIDTH)
 /* not counting final FUD */
-#define DURATION_INIT (10*DURATION_WRITE + DURATION_DAC_CAL)
-#define DURATION_PROGRAM (5*DURATION_WRITE) /* not counting FUD */
+#define DURATION_INIT (10*DURATION_WRITE + DURATION_RESET_PULSE + DURATION_RESET_RECOVERY + DURATION_D
+#define DURATION_PROGRAM (6*DURATION_WRITE) /* not counting FUD */
 
 #else
 #error Unknown DDS configuration
@@ -59,8 +61,10 @@ void dds_init(long long int timestamp, int channel)
 #endif
     channel <<= 1;
     DDS_WRITE(DDS_GPIO, channel);
-    DDS_WRITE(DDS_GPIO, channel | 1); /* reset */
+    DDS_WRITE(DDS_GPIO, channel); /* reset */
+    now += DURATION_RESET_PULSE;
     DDS_WRITE(DDS_GPIO, channel);
+    now += DURATION_RESET_RECOVERY;
 
 #ifdef DDS_AD9858
     /*
@@ -94,7 +98,7 @@ void dds_init(long long int timestamp, int channel)
 static unsigned int continuous_phase_comp[DDS_CHANNEL_COUNT];
 
 static void dds_set_one(long long int now, long long int ref_time, unsigned int channel,
-    unsigned int ftw, unsigned int pow, int phase_mode)
+    unsigned int ftw, unsigned int pow, int phase_mode, unsigned int amplitude)
 {
     unsigned int channel_enc;
 
@@ -130,7 +134,7 @@ static void dds_set_one(long long int now, long long int ref_time, unsigned int
         DDS_WRITE(DDS_CFR2, 0x00);
 #endif
 #ifdef DDS_AD9914
-        DDS_WRITE(DDS_CFR1L, 0x0008);
+        DDS_WRITE(DDS_CFR1L, 0x0108);
 #endif
         pow += continuous_phase_comp[channel];
     } else {
@@ -141,7 +145,7 @@ static void dds_set_one(long long int now, long long int ref_time, unsigned int
         DDS_WRITE(DDS_CFR2, 0x40);
 #endif
 #ifdef DDS_AD9914
-        DDS_WRITE(DDS_CFR1L, 0x2008);
+        DDS_WRITE(DDS_CFR1L, 0x2108);
 #endif
         fud_time = now + 2*DURATION_WRITE;
         pow -= (ref_time - fud_time)*DDS_RTIO_CLK_RATIO*ftw >> (32-DDS_POW_WIDTH);
@@ -157,6 +161,9 @@ static void dds_set_one(long long int now, long long int ref_time, unsigned int
 #ifdef DDS_AD9914
     DDS_WRITE(DDS_POW, pow);
 #endif
+#ifdef DDS_AD9914
+    DDS_WRITE(DDS_ASF, amplitude);
+#endif
     DDS_WRITE(DDS_FUD, 0);
 }
 
@@ -165,6 +172,7 @@ struct dds_set_params {
     unsigned int ftw;
     unsigned int pow;
     int phase_mode;
+    unsigned int amplitude;
 };
 
 static int batch_mode;
@@ -193,14 +201,14 @@ void dds_batch_exit(void)
     now = batch_ref_time - batch_count*(DURATION_PROGRAM + DURATION_WRITE);
     for(i=0;i<batch_count;i++) {
         dds_set_one(now, batch_ref_time,
-            batch[i].channel, batch[i].ftw, batch[i].pow, batch[i].phase_mode);
+            batch[i].channel, batch[i].ftw, batch[i].pow, batch[i].phase_mode, batch[i].amplitude);
         now += DURATION_PROGRAM + DURATION_WRITE;
     }
     batch_mode = 0;
 }
 
 void dds_set(long long int timestamp, int channel,
-    unsigned int ftw, unsigned int pow, int phase_mode)
+    unsigned int ftw, unsigned int pow, int phase_mode, unsigned int amplitude)
 {
     if(batch_mode) {
         if(batch_count >= DDS_MAX_BATCH)
@@ -210,9 +218,10 @@ void dds_set(long long int timestamp, int channel,
         batch[batch_count].ftw = ftw;
         batch[batch_count].pow = pow;
         batch[batch_count].phase_mode = phase_mode;
+        batch[batch_count].amplitude = amplitude;
         batch_count++;
     } else {
         rtio_chan_sel_write(RTIO_DDS_CHANNEL);
-        dds_set_one(timestamp - DURATION_PROGRAM, timestamp, channel, ftw, pow, phase_mode);
+        dds_set_one(timestamp - DURATION_PROGRAM, timestamp, channel, ftw, pow, phase_mode, amplitude)
     }
 }
diff --git a/soc/runtime/dds.h b/soc/runtime/dds.h
index 03c2bf0..2e3a4d0 100644
--- a/soc/runtime/dds.h
+++ b/soc/runtime/dds.h
@@ -59,6 +59,6 @@ void dds_init(long long int timestamp, int channel);
 void dds_batch_enter(long long int timestamp);
 void dds_batch_exit(void);
 void dds_set(long long int timestamp, int channel,
-    unsigned int ftw, unsigned int pow, int phase_mode);
+    unsigned int ftw, unsigned int pow, int phase_mode, unsigned int amplitude);
 
 #endif /* __DDS_H */

**Comment by fallen** [comment]
You can post this as a gist https://gist.github.com/ or on http://pastebin.com/

**Comment by sbourdeauducq** [comment]
Actually, better send those patches to the ML or by email to me.
There are still some issues to fix, e.g. this disables reset for the 9858 as well, adds the unneeded reset pulse delays, etc. Please review carefully each line of this patch.

**Comment by raghavendrasrinivas** [comment]
Added asf_to_amplitude function
http://pastebin.com/RVLji9xQ

**Comment by sbourdeauducq** [comment]
Almost there, there is still the reset test laying around in this patch, and the ddb should not be modified.

**Comment by raghavendrasrinivas** [comment]
I think I got rid of all the residual reset test stuff.

http://pastebin.com/1vpURX2F

**Comment by sbourdeauducq** [comment]
The "turns on OSK" comment is misplaced. DURATION_DAC_CAL should not be modified.

**Comment by raghavendrasrinivas** [comment]
We're not changing the DAC cal pulse time to match the datasheet? We don't want it at 1 ms?

**Comment by sbourdeauducq** [comment]
147000 is already the correct value for 1+ms, I already committed the fix. In all cases, this should be in a separate patch, since it has nothing to do with amplitude control.

**Comment by raghavendrasrinivas** [comment]
Okay. Where do you want the turn on OSK comment? That seems to be where we modified it.

**Comment by sbourdeauducq** [comment]
The comment and the source code currently sound as if bit 0x2000 were OSK disable.

**Comment by raghavendrasrinivas** [comment]
Is this clearer?
http://pastebin.com/2nax8WE0

**Comment by sbourdeauducq** [comment]
Yes, thanks
