### ISSUE TITLE
artiq_flash command not found

### ISSUE THREAD

**Issue by philipkent** [m-labs/artiq#1091]
On linux 64 bit, after creating a conda environment via `conda create -n artiq-3.6 artiq-kc705-nist_qc2=3.6
` the `artiq_flash` command is not found

    source activate artiq-3.6
    (artiq-3.6) philip@sophus:~/scripts$ artiq_flash -t kc705 -m nist_qc2
    artiq_flash: command not found

**Comment by philipkent** [comment]
This also happens if you create an environment from the "main" channel with `conda create -n artiq-main artiq-kc705-nist_qc2` which installs version 3.6 as well.

**Comment by sbourdeauducq** [comment]
duplicate of https://github.com/m-labs/artiq/issues/984
