### ISSUE TITLE
Dashboard doesn't get informations from Zotino

### ISSUE THREAD

**Issue by LabVIEWfan** [m-labs/artiq#1095]
Hello,

We use a Kasli-tester setup, so including Kasli and Zotino, with a recent commit (16b917be). 

The dashboard recognizes the Zotino module from the device database and displays the 32 channels, but their values are never updated (everything is fixed at 0.000%). Everything works well when setting the voltages via a EnvExperiment, as well as reading the voltages via the read_reg() function.

**Comment by sbourdeauducq** [comment]
Are other monitoring features e.g
 TTL working correctly?

**Comment by LabVIEWfan** [comment]
All the TTL are working correctly through both the EnvExperiment and the dashboard.

**Comment by sbourdeauducq** [comment]
Did you create a ``artiq.gateware.rtio.phy.ad53xx_monitor.AD53XXMonitor`` in the gateware?
