### ISSUE TITLE
Urukul AD9910 ref clk mismatch

### ISSUE THREAD

**Issue by prasath-d** [m-labs/artiq#1096]
I am using Urukul with kasli, and there is a mismatch in the ref clk value in **ptb** and **tester** variants.
In **tester** variant, the clock frequency seems not right. The output frequency is **setfreq/1.25**.

In PTB variant
   ```
 "urukul1_cpld": {
        "type": "local",
        "module": "artiq.coredevice.urukul",
        "class": "CPLD",
        "arguments": {
            "spi_device": "spi_urukul1",
            "io_update_device": "ttl_urukul1_io_update",
            "refclk": 100e6,
            "clk_sel": 0
        }
    }
})

device_db.update({
    "urukul1_ch" + str(i): {
        "type": "local",
        "module": "artiq.coredevice.ad9910",
        "class": "AD9910",
        "arguments": {
            "pll_n": 40,
            "chip_select": 4 + i,
            "cpld_device": "urukul1_cpld"
        }
    } for i in range(4)
})
```
In tester variant,
 ```
  urukul0_cpld={
        "type": "local",
        "module": "artiq.coredevice.urukul",
        "class": "CPLD",
        "arguments": {
            "spi_device": "spi_urukul0",
            "io_update_device": "ttl_urukul0_io_update",
            "refclk": 125e6,
            "clk_sel": 0
        }
    }
)

for i in range(4):
    device_db["urukul0_ch" + str(i)] = {
        "type": "local",
        "module": "artiq.coredevice.ad9910",
        "class": "AD9910",
        "arguments": {
            "pll_n": 32,
            "chip_select": 4 + i,
            "cpld_device": "urukul0_cpld",
            "sw_device": "ttl_urukul0_sw" + str(i)
        }
    }

```
How to change it?

**Comment by jordens** [comment]
Please provide some context. What is your reference clock, how is the board populated, how is it connected, and what's the reference frequency? See the documentation for info on the fields and arguments.

**Comment by prasath-d** [comment]
Kasli is flashed with Tester variant.
Urukul DDS is connected to EEM1 and EEM0, DIO in EEM5, Sampler in EEM3,2.
Before flashing Tester variant, The clock frequency of Urukul was 1GHz and after flashing tester variant, it seems to have a clock frequency of 800MHz.
For ex: Setting 300MHz in Urukul Channel shows 240MHz as an output frequency, which is 300/1.25

**Comment by jordens** [comment]
How is the clocking circuitry on the board populated, how is it connected? How do you actually want to clock it?

**Comment by prasath-d** [comment]
The Clock to the Urukul is managed by Kasli and I didn't populate anything other than EEM connectors.
Did I understand your question properly?

**Comment by jordens** [comment]
Are you using the on board 100 MHz oscillator or the kasli 125 MHz clock via mmcx? See the schematic for the clocking circuit and the board population.

**Comment by jordens** [comment]
Then you should change `"refclk": 125e6`. That's documented.

**Comment by prasath-d** [comment]
Reflash needed?

**Comment by jordens** [comment]
No

**Comment by prasath-d** [comment]
Works!!! Thank you
