### ISSUE TITLE
Text missing on right click context menu in linux

### ISSUE THREAD

**Issue by prasath-d** [m-labs/artiq#1135]
I have tried to run dashboard from Ubuntu 18.04 and noticed that the right-click context menu is not visible. for example 
I tried to plot the datasets, but the applet menu that shows templates etc was missing.

similarly, all the right-click menu fields are empty.
is there any quick fix for that?

**Comment by sbourdeauducq** [comment]
Can you post screenshots?

**Comment by prasath-d** [comment]
![image](https://user-images.githubusercontent.com/40395150/44297290-4129f980-a2cf-11e8-9bf4-353e91245299.png)

**Comment by prasath-d** [comment]
I found a fix.

`export QT_STYLE_OVERRIDE=gtk2`


Adding these lines to .bashrc fixes the problem.

**Comment by sbourdeauducq** [comment]
Where did you find this? Looks like a Qt or Ubuntu bug?

**Comment by prasath-d** [comment]
[](https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications
)
[](https://unix.stackexchange.com/questions/176696/qt5-applications-dont-use-gtk-style-on-liux-mint
)
These two links helped me.

**Comment by sbourdeauducq** [comment]
OK, well this doesn't look like a problem with ARTIQ. Good you found a workaround.
