### ISSUE TITLE
(S/NF) AD9914 register values

### ISSUE THREAD

**Issue by raghavendrasrinivas** [m-labs/artiq#114]
It seems like the amplitude register is missing from the list of addresses in artiq/soc/runtime/dds.h.

0x33 and 0x32 need to be programmed to 0x0f and 0xff respectively to generate an output on the DDS. Default for these registers is 0 and it doesn't seem like they are being programmed in dds.c.

**Comment by raghavendrasrinivas** [comment]
I think you also need to turn on the profile mode. I tested it on my eval board and there's no output without the profile mode. This is in address 0x06. Value should be 0x80.

**Comment by sbourdeauducq** [comment]
:+1: that works. Thanks!
