### ISSUE TITLE
Request: --version command-line arg for bug reporting

### ISSUE THREAD

**Issue by drewrisinger** [m-labs/artiq#1160]
When bug reporting, it's useful to have an idea what ARTIQ version is causing the issue. I suggest adding a `--version` flag to `artiq_run` or `artiq_master` to print the version number. 

It could be added elsewhere, but this seems one of the easiest places.

Implementation (neglecting adding flag to argparse):
```
import artiq

print("Current ARTIQ version: {}".format(artiq.__version__))
```

**Comment by sbourdeauducq** [comment]
That can be obtained with conda list or running that code in the python repl. The issue is to which tool the flag should be added. Why not dashboard, browser, or compile?

**Comment by jordens** [comment]
`artiq_run` and `_master` are fine by me. Why not just add it to `verbosity_args()`? That covers a lot.

**Comment by sbourdeauducq** [comment]
Maybe rename ``verbosity_args`` to e.g. ``common_args`` then?

**Comment by drewrisinger** [comment]
@sbourdeauducq That would require a fair amount of refactoring, though I agree with the idea. A quick scan of the repo shows ~15 files where `verbosity_args` is used, not counting code built on top of it.

**Comment by drewrisinger** [comment]
Also, processing the `--version` flag could be abstracted to some common function, maybe something like (in `artiq.tools`):

```python
def process_common_args(cmd_arguments: argparse.Namespace):
    """Process common ARTIQ arguments."""
    if cmd_arguments.version:
        # print version
    init_logger(cmd_arguments)
    if hasattr(cmd_arguments, "bind"):
        bind_address_from_args(cmd_arguments)
```

**Comment by drewrisinger** [comment]
See #1181 for related PR.

**Comment by drewrisinger** [comment]
Pending approval on #1181
