### ISSUE TITLE
problems with tune_sync_delay

### ISSUE THREAD

**Issue by meyerbernd** [m-labs/artiq#1194]
I tried to execute the calibration for the kasli-urukul synchronization but somehow it failed, prompting the error "ValueError: no valid window/delay". 
The device data base, the synchronization script (https://github.com/m-labs/artiq/issues/1143) and the prompt's output are attached.

[Kasli-Uru-Sync.zip](https://github.com/m-labs/artiq/files/2584264/Kasli-Uru-Sync.zip)

**Comment by jordens** [comment]
Below line 133 in device_db.py:

```patch
--- /tmp/Kasli-Uru-Sync/device_db.py_old        2018-11-16 14:08:59.018787050 +0100
+++ /tmp/Kasli-Uru-Sync/device_db.py    2018-11-16 14:09:14.838876215 +0100
@@ -131,6 +131,7 @@
         "arguments": {
             "spi_device": "spi_urukul0",
             "io_update_device": "ttl_urukul0_io_update",
+            "sync_device": "ttl_urukul0_sync",
             "refclk": 100e6,
             "clk_sel": 1
         }
```

This should be detected before trying to scan sync.
