### ISSUE TITLE
Add context info to RTIOUnderflow exceptions

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#12]
To be able to debug and solve `RTIOUnderflow`s, we should add a few easily reachable pieces of information to the exception:

 * rtio channel number
 * `now()`
 * the amount of the time violation.

Metadata in exceptions would be required for this. Full debugging information (AST nodes to ELF debugging symbols) is for later.

**Comment by sbourdeauducq** [comment]
Done in commit 7a1d60ee15fd8c87c0de94bebdc0785656c4787c
