### ISSUE TITLE
NXP firmware update via artiq_flash

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#1200]
```artiq_flash``` support for flashing NXP microprocessors such as that used on Sayma AMC.

@sbourdeauducq Commented that this is likely to be an expensive and complex project. 

> Completely different protocol (on UART), which may or may not be documented and may need to be reverse-engineered, existing open implementation is dysfunctional, mapping UART/JTAG may be difficult on multiple platforms, flashing MMC does not fit in existing artiq_flash architecture, problems with packaging and conda, etc. etc. lots of tedious research to do and things to sort out.

**Comment by sbourdeauducq** [comment]
@jbqubit Are you still interested in this?

**Comment by jbqubit** [comment]
Not sure if this is a new development or not but looks like openocd advertises built-in support for the NXP LPC1776.  I'm looking at [Flash Driver: lpc2000](http://openocd.org/doc/html/Flash-Commands.html).

**Comment by sbourdeauducq** [comment]
Yes, we used it before, it needs the internal JTAG connector.
