### ISSUE TITLE
[Deprecation]: Using importlib.load_module() in artiq.tools.file_import

### ISSUE THREAD

**Issue by drewrisinger** [m-labs/artiq#1203]
# Bug Report

## One-Line Summary

`artiq.tools.file_import` uses deprecated `importlib.FileLoader` function [`load_module()`](https://github.com/python/cpython/blob/7212148c95947b0fdfcb0c8e37d4357287bdb4bd/Lib/importlib/_bootstrap_external.py#L947-L956).

### Expected Behavior

ARTIQ should not rely on deprecated standard library functions. `importlib` suggests using [`exec_module()`](https://github.com/python/cpython/blob/7212148c95947b0fdfcb0c8e37d4357287bdb4bd/Lib/importlib/_bootstrap_external.py#L771-L777) instead.

### Actual (undesired) Behavior

Relevant code:
https://github.com/m-labs/artiq/blob/dce4f036db75e0f7380472bc1b0ec8bea977111b/artiq/tools.py#L86-L92

Further, this function call appears to be missing the parameter `fullname` in `Python` stdlib code.

Related `Python` stdlib code:
https://github.com/python/cpython/blob/7212148c95947b0fdfcb0c8e37d4357287bdb4bd/Lib/importlib/_bootstrap_external.py#L947-L956

Changing this will require some refactoring, because `exec_module()` doesn't have any return statement.

### Your System

* All versions of ARTIQ since at least 2.5

**Comment by sbourdeauducq** [comment]
> Changing this will require some refactoring, because `exec_module()` doesn't have any return statement.

How do you locate the new module that you just loaded at all?

NB: the Python module API is changing often, and tracking it creates significant work (as you are beginning to notice, it is also not straightforward to use).

**Comment by sbourdeauducq** [comment]
see also https://github.com/m-labs/artiq/issues/652

**Comment by drewrisinger** [comment]
> > Changing this will require some refactoring, because `exec_module()` doesn't have any return statement.
> 
> How do you locate the new module that you just loaded at all?

Don't know what you mean by this or why you would want to locate the new module. I haven't looked into what [`load_module()`](https://github.com/python/cpython/blob/7212148c95947b0fdfcb0c8e37d4357287bdb4bd/Lib/importlib/_bootstrap_external.py#L947-L956) is supposed to do.

**Comment by sbourdeauducq** [comment]
> why you would want to locate the new module

Because you have to return it.

**Comment by drewrisinger** [comment]
Deprecated since Python 3.5: https://github.com/python/cpython/commit/32439d6eb63f1ea31aed1e45459f0f50f965ef51
