### ISSUE TITLE
Compiler: AST can't parse multiple binary ops

### ISSUE THREAD

**Issue by drewrisinger** [m-labs/artiq#1240]
# Question

## Description

Can the AST (abstract syntax tree) handle parsing multiple binary operations? I used the following code snippet:

```python
self.var1 = 0x6000 0000
self.var2 = 0x01AB 0000
localvar3 = 0x0000 1999
self.output_spi(self.var1 | self.var2 | localvar3)
```
where ``output_spi`` is a utility function that logs the value to ``rtio_log``, configures the SPI bus and outputs it to ``spi2.write()``.

When I view the `rtio_log` dump, it shows the output value (i.e. the input parameter to ``output_spi()`` as: `0x61AB0000`, both in the ASCII `rtio_log` channel and the ``spi0/write`` register. Am I doing something wrong, or this this a compiler bug? Not sure if here or ``llvmlite-artiq`` is the better spot for this question.

**Comment by jordens** [comment]
Do you have a complete minimal example. I can't reproduce this here. The space is a syntax error. And if I remove it the correct value is computed. This pattern is also successfully used in a bunch of places.

**Comment by drewrisinger** [comment]
I'll look into it closer.

**Comment by drewrisinger** [comment]
I think I found the root cause of my error. Issues with casting between ints & np.int32 (maybe compiler inferencer or soft CPU). Opened #1242 with newly-discovered issues.
