### ISSUE TITLE
Multiple pipelines

### ISSUE THREAD

**Issue by AndreCie** [m-labs/artiq#1246]
Hello, 
I have a question regarding multiple piplines that I hope someone can awnser me.
I have 2 simple scripts, one controlling a single TTL I/O EEMs channels output and one controlling a single Zotino channel output. Both scripts are appended.
Now I want to have both running simultaneously in the same master and dashboard.
But everytime when I start one script, the other gets deleted. (I chose different pipeline names in the dashboard)
Can someone explain me, how it works, and what I have to addapt to make 2 programs run in the same master. 
A second question is, is there a way to load in a value from a dataset as soon as it gets changed, without having a loop over that dataset. So as soon as a change is detected --> Load the new value without a change in timeline.

Thanks in advance.

[TTL_controll.txt](https://github.com/m-labs/artiq/files/2758717/TTL_controll.txt)
[Zotino_controll.txt](https://github.com/m-labs/artiq/files/2758718/Zotino_controll.txt)

**Comment by jordens** [comment]
There can be only one kernel per core device at any time.
I don't understand the second question.
Why did you bypass the issue templates?
