### ISSUE TITLE
Compiler: Generating binary ints

### ISSUE THREAD

**Issue by drewrisinger** [m-labs/artiq#1249]
# Bug Report

## One-Line Summary

Issues generating 64-bit integers in ARTIQ compiler. Works in `@portable`, not on core.

## Desired Resolution

* Temporary workaround/tips on how to do this math properly.
* Fixed or clarified compiler/documentation, telling you what operations you can actually use properly on core device.

### Steps to Reproduce

Desired program: convert number from one base to another using division. Using for ad9912 DDS chip running on UMD's hardware.
```python
@portable
def freq_to_mu(frequency_raw: TInt32) -> TInt64:
    """
    Convert raw frequency to value used by DDS to denote frequency.

    Args:
        frequency_raw (float): Frequency in Hertz to set DDS to.

    Returns:
        Int64: DDS "frequency tuning word" equivalent to given frequency. Max of 48 bits

    Examples:
        >>> freq_to_mu(int(100E6))
        28147497671065
        >>> freq_to_mu(int(100.01E6))
        28150312420832
        >>> freq_to_mu(int(200E6))
        56294995342131
        >>> hex(freq_to_mu(int(100E6)))
        '0x19999999999a'

    """
    dds_clk_freq_sample = np.int64(10 ** 9) # 1 GHz
    binary_freq_tune_word_max = np.int64(2 ** 48)
    _LOGGER.debug("sclk: %d, ftwmax: %d", dds_clk_freq_sample, binary_freq_tune_word_max)
    return np.int64(
        round(float((frequency_raw / dds_clk_freq_sample)) * binary_freq_tune_word_max)
    )
```

### Expected Behavior

See doctests above.

### Actual (undesired) Behavior

This function typically produces 0 when run on the core, probably because `binary_freq_tune_word_max` is only registering as `0`. However, ``np.int64(10**9)`` seems to produce the desired result every time.

This says to me that constant folding/propagation compiler passes are not being done by ARTIQ/LLVM on the IR.

### Extra tests
* Issue disappears when all values are hard-coded as integers, and no float casting occurs. You do get one bit of rounding error, however, because the ALU truncates instead of rounds.
* ``binary_freq_tune_word_max = np.int64(1 << 48)`` also logs its value as 0. INCORRECT.
* ``binary_freq_tune_word_max = np.int64(round(2**48))`` throws a compiler error:

```bash
error: cannot unify numpy.int? with float
binary_freq_tune_word_max = np.int64(round(2**48))
                                           ^^^^^
note: expression of type numpy.int?
```

### Your System

* ARTIQ version: ARTIQ 4, including fix from #1242 
* Hardware involved: kc705 FPGA

Related: #1242 , #1225

**Comment by sbourdeauducq** [comment]
This is correct. 2 is a 32-bit integer which you are raising to the 48th power modulo 2**32, which yields 0. Same problem with shifting 1.

int64(2)**48 should work.

**Comment by sbourdeauducq** [comment]
And the constant folding passes are being done, but they are consistent with the type system.

**Comment by whitequark** [comment]
Thanks. If constant folding is implemented correctly, it never changes semantics of the code being compiled. As such, your assertions about constant folding happening or not are irrelevant (unless you are trying to highlight a bug in constant folding passes, that is.)
