### ISSUE TITLE
Kasli: support 10 MHz reference input

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#1254]
# ARTIQ Feature Request

## Problem this request addresses

10 MHz is a more common output of reference oscillators (GPSDO, Rb).
Currently a 100 MHz source is needed.

## Describe the solution you'd like

Support 10 MHz reference frequency Si5324 configurations.

## Additional context

Will affect #1172

**Comment by dnadlinger** [comment]
I'd be happy to [also add](https://github.com/m-labs/artiq/commit/4d215cf541bedf6380b0e956f9bedfd8a20d5fad) some configurations for 10 MHz, but wouldn't really have a reason to test it/measure its performance right now.
