### ISSUE TITLE
SUServo coefficient readback

### ISSUE THREAD

**Issue by hartytp** [m-labs/artiq#1258]
# Bug Report

## One-Line Summary

SUServo IIR coefficient read back does not work

### Steps to Reproduce

```python
a1 = -1
profile = 0
addr = 5
base = (self.aom_397_doppler.servo_channel << 8) | (profile << 3)
self.aom_servo.write(base + addr, a1)
readback = self.aom_servo.read(base + addr)

test = [0]*32
for i in range(32):
    test[i] = 1 if ((readback << i) & (1<<31)) != 0 else 0
print(test)
```

### Expected Behavior

The number we read back should match the number we write.

### Actual (undesired) Behavior

Readback seems to be: ```(((base+addr) | WE) >> 8) | ((addr << 5) & (1 << COEFF_WIDTH) - 1 ))```

i.e. the 5 LSB of the number we read back are `(((base+addr) | WE) >> 8)` and the upper 13 bits are the 13 LSB of the coefficent.

Appears to affect the a0 and b1 coefficients equally.

### Your System

Artiq 5.0.dev

**Comment by jordens** [comment]
@hartytp Yes that assert would fail since the new rtio layout. See https://github.com/m-labs/artiq/pull/1266#issuecomment-461424074
