### ISSUE TITLE
pxi6733: ping returns False

### ISSUE THREAD

**Issue by kcmccorm** [m-labs/artiq#126]
File "C:\Users\rabi\AppData\Local\Continuum\Anaconda3\lib\site-packages\artiq-
0.0+dev-py3.4.egg\artiq\devices\pxi6733\driver.py", line 54, in ping
    self.daq.DAQmxGetDevSerialNum(self.device, data)
AttributeError: 'DAQmx' object has no attribute 'device'

**Comment by fallen** [comment]
I just pushed this change: https://github.com/m-labs/artiq/commit/7dfd11e2f0c47b0b2b7303c4c76ee6ffa7e9d39e
Could you give this a try when the Windows conda package will be uploaded? (hopefully in a few minutes)
In any case, if it fails or not, please post the console output of the controller.

**Comment by fallen** [comment]
The Windows package is uploaded, you can update by doing : conda update artiq

**Comment by fallen** [comment]
I updated again so that the debug message is only printed when controller is run in verbose mode.
So please when you update your artiq package, in order to test run the controller in verbose mode with `-vv` argument

**Comment by sbourdeauducq** [comment]
It seems no one really cares about the PXI6733, so I'd remove support for it from the stable branches until we have a plan for testing.

**Comment by jordens** [comment]
@kcmccorm @dhslichter @jboulder ping

**Comment by dhslichter** [comment]
Are other groups, e.g. JQI, using these devices?

**Comment by jboulder** [comment]
I don't know of anyone using it except Katie. Katie, do you have continued
interest in the NI 6733? -Joe

**Comment by dhslichter** [comment]
After further discussion, we have decided that we will only use the PDQ with ARTIQ for this system, and will not try to use the PXI6733 with ARTIQ, so it is OK to remove it from the stable distributions.  Perhaps other groups using NI hardware may benefit from aspects of the code already in place.

**Comment by sbourdeauducq** [comment]
What about putting it into a separate repository?

**Comment by jboulder** [comment]
I just had a conversation with everyone about this. The plan is to switch
over to PDQs when we make the switch to ARTIQ.

Katie

**Comment by dhslichter** [comment]
If putting it into a separate repository is helpful to you, that should be OK from our end.

**Comment by jordens** [comment]
Leave it in a branch. We can resurrect it later.

**Comment by sbourdeauducq** [comment]
I don't like stale branches laying around, and the repository hints that you can have external ARTIQ controllers/drivers. People regularly ask how to extend ARTIQ; even if the code is untested, it should be easy to have a good structure so that the repository can be used as example.

**Comment by sbourdeauducq** [comment]
https://github.com/m-labs/aq_ni6733

**Comment by jordens** [comment]
A non-working example of how to extend artiq? Doesn't sound like a good idea and seems less "likeable" than a branch. And why would would it be less "stale"? Most people would prefer branches very much because they are much easier to handle then a bunch of additional repositories. There is nothing bad about branches.

**Comment by jordens** [comment]
You also need to migrate the issues.
