### ISSUE TITLE
fancy scanning widget

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#128]
Prototype design for a fancier scanning widget.

https://goo.gl/photos/AG7fPLGoACcZ8h4W9

**Comment by sbourdeauducq** [comment]
The purpose of this widget is to visually edit the main scan parameters: minimum, maximum and number of points.

The graduated axis represents all real numbers. The minimum and maximum of the scan are defined by two triangles. Those triangles can be dragged using the mouse to modify the corresponding value.

In addition to the graduation, the axis has dots that represent the values (iteration points) that the scanned variable will take during scanning.

Increasing or decreasing the number of points is done using shift+drag. The drag feels like ejecting or pulling points: when in the right part of the widget, dragging from left to right decreases the point count, dragging right to left increases it. When in the left part, the drag directions are reversed.

Zooming on the whole widget is done using the mouse wheel like in pyqtgraph. There is also a button to fit the view to the figure similar to the A button in pyqtgraph, and a button to set the scan min/max to 1/3 and 2/3 of the current view.

The widget should be synchronized with the three spin boxes.

**Comment by jordens** [comment]
https://github.com/m-labs/scanwidget

**Comment by jordens** [comment]
preview: https://github.com/m-labs/artiq/tree/scanwidget
todo: https://github.com/m-labs/scanwidget/blob/master/todo.md
