### ISSUE TITLE
Gateware: Change number of Lanes

### ISSUE THREAD

**Issue by drewrisinger** [m-labs/artiq#1282]
# Question

## Description

[Sequence Errors in manual](https://m-labs.hk/artiq/manual-master/rtio.html?highlight=lanes#sequence-errors) describes being able to add more lanes to the gateware. Looking through the gateware config [kc705.py](https://github.com/m-labs/artiq/blob/master/artiq/gateware/targets/kc705.py) doesn't seem to have any references to it. Where is such a config setting, if it exists?

**Comment by dnadlinger** [comment]
See the `lane_count` parameter to `artiq.gateware.rtio.core.Core` (which is passed down the tree to `SED`, etc.). Could use some documentation, though.

**Comment by dhslichter** [comment]
@drewrisinger is this for ARTIQ 2 as you mentioned in #1281 ?  There are no lanes in ARTIQ 2.
