### ISSUE TITLE
consistent moninj DDS widget ordering

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#1288]
https://github.com/m-labs/artiq/pull/1287#issuecomment-471384277

**Comment by sbourdeauducq** [comment]
@dnadlinger ping

**Comment by sbourdeauducq** [comment]
@dnadlinger ping

**Comment by hartytp** [comment]
Is reverting that really a good solution to this?

**Comment by sbourdeauducq** [comment]
I should not have accepted the PR, and reverting is the second-best option.
