### ISSUE TITLE
move relevant Kasli variants to kasli_generic

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#1289]
Requires reordering of RTIO channels for Zotino and SFP LEDs:
* PTB
* PTB2
* HUB
* LUH

Requires removal of RTIO SFP LEDs (conflicts with DRTIO link indicators):
* VLBAIMaster
* VLBAISatellite

Opticlock uses legacy Novogorny and is not supported.

**Comment by sbourdeauducq** [comment]
@jordens Do you want to do that, or we keep them as-is and move them out of tree?
With the latter option I can still keep the firmware build on CI, but you'd lose the automatically generated device database templates.

**Comment by jordens** [comment]
Done in https://git.m-labs.hk/M-Labs/sinara-systems/commit/5507339b447cd02b82b88a8f1af598445ee736a9 and later commits
