### ISSUE TITLE
unittests fail after #1262

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#1290]
After merging #1262 

http://buildbot.m-labs.hk/builders/artiq/builds/2960/steps/python_unittest_1/logs/stdio

@cjbe please run the unittests and fix it.

**Comment by sbourdeauducq** [comment]
This isn't just breaking unit tests, this is also making ``artiq_run`` unusable.

**Comment by cjbe** [comment]
Apologies - fixed in #1292.

**Comment by sbourdeauducq** [comment]
There are still issues with the hardware unit tests
https://nixbld.m-labs.hk/build/1343/log

**Comment by sbourdeauducq** [comment]
@cjbe Nope.
https://nixbld.m-labs.hk/build/1706/nixlog/2

**Comment by sbourdeauducq** [comment]
And you can run the HW unit tests on your own system by the way, you don't need buildbot for that.
