### ISSUE TITLE
upload artiq package on pypi

### ISSUE THREAD

**Issue by fallen** [m-labs/artiq#131]
Currently, trying to upload artiq to pypi results in this error message:
HTTPError: 400 Client Error: Invalid version, cannot use PEP 440 local versions on PyPI.
This is due to this line: https://github.com/m-labs/artiq/blob/master/setup.py#L53
I propose to replace the current version with a "Development release" version number: https://www.python.org/dev/peps/pep-0440/#developmental-releases

Would replacing 0.0+dev with 0.0.dev0 be OK?

**Comment by jordens** [comment]
Why do you want to upload to pypi? Do you plan on maintaining both conda and pypi packages? Did you figure out how to handle the bitstream binaries in the packages? How is the work of splitting the binaries from the rest coming along. That is important and necessary to parallelize the builds.

Anyway, more importantly than pypi packages: for both conda and pypi packages, the package versions need to be fixed. Add the git hash (unless we do real releases with version numbers) to distinguish, sort, and identify packages. Something like `0.0.dev$NUMBER.$GITHASH`? I don't think pypi will upgrade voluntarily if the version did not even change.
