### ISSUE TITLE
Outdated installation instructions

### ISSUE THREAD

**Issue by kaolpr** [m-labs/artiq#1314]
# Bug Report

## One-Line Summary

Instructions covered in "Developing ARTIQ" are outdated as [nix-scripts](https://github.com/m-labs/nix-scripts) repository does not exist anymore. Additinally there is a typo in link to the Conda installation script in "Installing ARTIQ" ([in manual](https://m-labs.hk/artiq/manual-master/installing.html)).

**Comment by sbourdeauducq** [comment]
That repository is moved to https://git.m-labs.hk/m-labs/nix-scripts.

As for the conda script location, use the links on https://m-labs.hk/artiq/resources.html for the latest documentation version.

**Comment by kaolpr** [comment]
That's fine for me, however googling `artiq manual` points to the reasonable looking location https://m-labs.hk/artiq/manual-master/installing.html what may be misleading for newbies.
