### ISSUE TITLE
Hardware CI tests for suservo

### ISSUE THREAD

**Issue by dnadlinger** [m-labs/artiq#1332]
There should be at least one Urukul/Sampler set up for use with suservo in the CI system. Basic unit tests for the driver should be really useful, as the recently fixed issues show.

(Actually including a dummy feedback loop with a diode detector would be a nice touch, too, if you have the hardware to spare.)

**Comment by sbourdeauducq** [comment]
duplicate of https://github.com/m-labs/artiq/issues/1004
