### ISSUE TITLE
inconsistent CLI switches for experiment selection in artiq_client submit

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#1348]
# Bug Report

## One-Line Summary

The command line switches to select an `Experiment` from a file are inconsistent.

### Steps to Reproduce

`artiq_run`: `-e EXPERIMENT, --experiment EXPERIMENT`
`artiq_compile`: `-e EXPERIMENT, --experiment EXPERIMENT`
`artiq_client submit`: `-c CLASS_NAME, --class-name CLASS_NAME`

### Expected/Proposal

Change `artiq_client` to use `-e`

### Your System (omit irrelevant parts)

ARTIQ master and release-4

**Comment by sbourdeauducq** [comment]
It's called ``class_name`` in ``expid``, which is used in many places (potentially in user code as well), so changing ``artiq_run`` and ``artiq_compile`` will result in the least breakage.
