### ISSUE TITLE
ARTIQ build (still) broken

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#135]
https://anaconda.org/m-labs/artiq/files

linux-32/artiq-0.0-np_1536.tar.bz2 is 1 month 2 days old

**Comment by whitequark** [comment]
There is now a build 1579 that should work.

**Comment by jboulder** [comment]
Confirmed build now works. I can install 1589 from conda. 

Is there a way of seeing the relationship between commit ID and build number?
https://github.com/m-labs/artiq/commits/master
https://anaconda.org/m-labs/artiq/files

**Comment by whitequark** [comment]
Not really, since while build number is derived from the output of `git describe`, it is ambiguous. We'd need to include the hash into the build number, conda allows to do that.

**Comment by sbourdeauducq** [comment]
@whitequark Can you make the platform-independent packages noarch in conda-recipes (most of them AFAICT), and upload linux32 and win32 versions for the other ones in addition to linux64?

**Comment by whitequark** [comment]
Will do.

**Comment by whitequark** [comment]
Well, every package that builds for linux32 and win32 is already uploaded, so that does not have to be done.

**Comment by sbourdeauducq** [comment]
@whitequark Nevertheless ARTIQ still cannot be installed on linux32 and win32. I tried to make it noarch, which would be the proper way of fixing this, but this tickles yet another conda bug. Can you have a look at it?

**Comment by sbourdeauducq** [comment]
https://github.com/conda/conda-build/issues/542

**Comment by whitequark** [comment]
I don't really see a point in bothering with noarch then, just build it thrice.

**Comment by sbourdeauducq** [comment]
The bitstream being included in the same package makes this approach somewhat slow and annoying (especially with the non-reproducibility of bitstream compilation by ISE and Vivado). How is #146 progressing?

**Comment by whitequark** [comment]
Everything in still issue should be done, #146 is in progress.
