### ISSUE TITLE
m-labs.hk/artiq/manual rebuild is not automatic

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#136]
Please automatically update manual as part of build. 

http://m-labs.hk/artiq/manual

Out of date manual made it harder to notice https://github.com/m-labs/artiq/commit/50a5a3baf0b3e4524b2f5b7d47ce62b4bf4212f1 .
```
environment: attr_* -> setattr_* 
```

**Comment by sbourdeauducq** [comment]
@whitequark can you implement automatic doc upload on the new build-server?

**Comment by whitequark** [comment]
@sbourdeauducq yes but I would like you to set up a separate account for doc upload

**Comment by sbourdeauducq** [comment]
You should be able to use a dedicated SFTP account (SSH file transfer) with the credentials in my home folder on the buildserver.

**Comment by whitequark** [comment]
It is actually impossible to use `sftp` in batch mode using password authentication.

**Comment by sbourdeauducq** [comment]
Use ``expect`` or some other hack.

**Comment by whitequark** [comment]
Done
