### ISSUE TITLE
release notes for API changes

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#137]
I spent a lot of time this weekend bringing the Penning lab up to speed with the changes to ARTIQ over the last month. There were a number of snaggles that took hours longer than necessary to debug. Mostly because python error messages generated using the old attr_device() with the new setattr_device() API were entirely opaque. A physicist-readable API change log would make it easier to know how to refactor experiments. Here's a start.

---
**10/12** Migration to Python 3.5 is complete. 
Note for other users of conda deployment. Due to ARTIQ's new python 3.5 dependency you'll have to create a new environment for python 3.5 and install ARTIQ in it.
```bash
(root)rabi@688penningA:~/git/m-labs/artiq$ conda create --name py5 python=3.5
(root)rabi@688penningA:~/git/m-labs/artiq$ source activate py5
(py5)rabi@688penningA:~/git/m-labs/artiq$ conda install artiq
```

----
**10/12** Changes in configuration files: https://github.com/m-labs/artiq/commit/97accd254042933a069000b892c31f7f0e312271

* ddb.pyon -> device_db.pyon
* pdb.pyon -> dataset_db.pyon

----
**10/3** Changes in program files: https://github.com/m-labs/artiq/commit/50a5a3baf0b3e4524b2f5b7d47ce62b4bf4212f1
* attr_device() -> setattr_device()
* attr_argument() -> setattr_argument()

**Comment by sbourdeauducq** [comment]
This should be posted on the mailing list, not in a issue I guess?
The *db.pyon rename is only part of that change, ``set/get_result()`` and ``set/get_parameter()`` should also be replaced with ``set/get_dataset()`` (see my post on the list).
