### ISSUE TITLE
compiler: Classes with same qualname but different layout crash LLVM IR generator

### ISSUE THREAD

**Issue by dnadlinger** [m-labs/artiq#1395]
On latest master (almost, f2f7170d20709c77b2521f27fe8141dda86df006), this

```py
from artiq.experiment import *


def make_foo(num_fields):
    class Foo:
        def __init__(self):
            self.mem = list(range(num_fields))

        @kernel
        def print_all(self):
            for m in self.mem:
                print(m)

    return Foo


class ClassQualname(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.foo3 = make_foo(3)()
        self.foo4 = make_foo(4)()

    @kernel
    def run(self):
        self.foo3.print_all()
        self.foo4.print_all()
```

leads to

```
TypeError: Can only insert {i8*, void (i8*, %"I.artiq_worker_class_qualname.make_foo.<locals>.Foo.1"*)*} at [0] in {{i8*, void (i8*, %"I.artiq_worker_class_qualname.make_foo.<locals>.Foo.1"*)*}, %"I.artiq_worker_class_qualname.make_foo.<locals>.Foo.1"*}: got {i8*, void (i8*, %"I.artiq_worker_class_qualname.make_foo.<locals>.Foo"*)*}
```

The problem is that the type is looked up by name in llvm_ir_generator (or earlier stages, although they seem to handle the rest fine), but the two classes share the same `__qualname__`.

If lookup by name is necessary, the mangled string should probably include the Python object ID to guard against this (or some form of content hash if separate compilation is ever going to be supported).

**Comment by sbourdeauducq** [comment]
NAC3 does not support this construct (you cannot type-annotate ``foo3`` and ``foo4``, so it's fairly clear to the user that this is not possible).
Unless it is really important to have this kind of dynamic class definition (which seems pretty tricky to do in the type system - something like const generics would have similar functionality and is probably a better way), I propose that we close this.
