### ISSUE TITLE
NDSP docs for Thorlabs T-Cube

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#141]
There is not an example of the proper device_db.pyon entry for Thorlabs T-Cube. It took me an hour to figure out that the target_name is "tdc001". Please update the controller usage examples to show the proper device_db.pyon entry. 

```python
    "thor_fun": {
        "type": "controller",
        "best_effort": true,
        "host": "host.domain.com",
        "comment": "this is a test of the Thorlabs TCube",
        "port": 3255,
        "target_name": "tdc001",
        "command": "thorlabs_tcube_controller -v -v -p {port} --bind {bind} -P TDC001 -d \"hwgrep://VID:PID=0403:faf0 SNR=83833889\" "
    },
```
http://www.m-labs.hk/artiq/manual/ndsp_reference.html?highlight=tdc001

**Comment by sbourdeauducq** [comment]
5947f54855dd2c67614b3cb4b1d4baf7ad7977fa and a5606768ad9c64c41ef9298ca05f0df68abeadf3 make this parameter optional for single-target servers (all controllers at the moment), and display the list of targets when an incorrect target is specified.
