### ISSUE TITLE
GUI data_set pane, can't change width of Value column to show data

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#143]
<img width="659" alt="screen shot 2015-10-17 at 7 30 20 pm" src="https://cloud.githubusercontent.com/assets/5688774/10562064/9b7249e2-7505-11e5-8d9f-4c45e13f120c.png">

**Comment by sbourdeauducq** [comment]
What data do you want to show? test_str?

**Comment by sbourdeauducq** [comment]
d7b41207da12c6a406995c2a4d54d217e466e919 and 661b9bfbfacda64b6bf00a0d51e321601d9dbcf8 should improve your display already...

**Comment by jboulder** [comment]
Yes. :)
