### ISSUE TITLE
Metlino and Sayma have different Si549 with different addresses

### ISSUE THREAD

**Issue by marmeladapk** [m-labs/artiq#1430]
# Bug Report

## One-Line Summary

Metlino and Sayma have different Si549 with different addresses

## Issue Details

Si549 on Sayma has address 0x55, on Metlino (LVDS version) it's 0x67. Kasli will also have LVDS version.

### Expected Behaviour

Choosing Si549 type during compilation? Trying both addresses?

### Your System (omit irrelevant parts)

* ARTIQ version: 2a90983
* Hardware involved: Metlino, Sayma, Kasli

**Comment by sbourdeauducq** [comment]
We can test both addresses at runtime, it's not very difficult. I suspect future Sayma may also use other Si549 addresses...

**Comment by sbourdeauducq** [comment]
Not really a problem for now so closing.
