### ISSUE TITLE
Confilct with matplotlib at artiq 5 about pyqt5

### ISSUE THREAD

**Issue by KaifengC** [m-labs/artiq#1441]
# Bug Report

## One-Line Summary

Installing `matplotlib` in an ARTIQ 5 environment break PyQt and give out `DLL load failed` error

## Issue Details

After I installed matplotlib using `conda install matplotlib`, `artiq_browser` won't start and gives out the following error:
```bash
(artiq501) D:\InWork\NIST_coding\artiq_MgAl>artiq_browser
Traceback (most recent call last):
  File "D:\Anaconda3\envs\artiq501\Scripts\artiq_browser-script.py", line 5, in <module>
    from artiq.frontend.artiq_browser import main
  File "D:\Anaconda3\envs\artiq501\lib\site-packages\artiq\frontend\artiq_browser.py", line 9, in <module>
ImportError: DLL load failed: The specified module could not be found.
```

It works pretty well just before I install matplotlib. Using `conda list --revisions` I can list out the changes:
```bash
2019-12-25 12:20:06  (rev 3)
    +artiq-board-kc705-nist_qc2-5.7085.ae4f4b33 (https://conda.m-labs.hk/artiq)

2020-04-12 11:47:40  (rev 4)
     binutils-or1k-linux  {2.27 (m-labs) -> 2.25.1 (m-labs)}
     ca-certificates  {2019.11.27 -> 2020.4.5.1 (conda-forge/label/main)}
     certifi  {2018.8.24 -> 2018.8.24 (conda-forge/label/main)}
     curl  {7.67.0 -> 7.62.0}
     hdf5  {1.10.2 -> 1.8.17 (conda-forge/label/main)}
     icu  {58.2 -> 58.1 (conda-forge/label/main)}
     jpeg  {9b -> 9c (conda-forge/label/main)}
     krb5  {1.16.4 -> 1.14.2 (conda-forge/label/main)}
     libcurl  {7.67.0 -> 7.62.0}
     libgit2  {0.27.8 (conda-forge) -> 0.27.0 (conda-forge/label/main)}
     libiconv  {1.15 -> 1.14 (conda-forge/label/main)}
     openssl  {1.1.1d -> 1.1.1f (conda-forge/label/main)}
     python-dateutil  {2.8.1 -> 2.8.1 (conda-forge/label/main)}
     qt  {5.9.7 -> 5.9.7 (conda-forge/label/main)}
     six  {1.11.0 -> 1.14.0 (conda-forge/label/main)}
     tbb  {2019.4 -> 2018_20171205 (conda-forge/label/main)}
     tk  {8.6.8 -> 8.5.19 (conda-forge/label/main)}
     zlib  {1.2.11 -> 1.2.11 (conda-forge/label/main)}
    +cycler-0.10.0 (conda-forge/label/main)
    +freetype-2.10.1 (conda-forge/label/main)
    +kiwisolver-1.0.1 (conda-forge/label/main)
    +matplotlib-3.0.0
    +pyparsing-2.4.7 (conda-forge/label/main)
    +pytz-2019.3 (conda-forge/label/main)
    +tornado-5.1.1 (conda-forge/label/main)
```
Ant this won't get fix even I tried to use `conda install --revision 3` or install a brand new conda environment. 

One workaround to make it back to work is using the following steps from [#1331](https://github.com/m-labs/artiq/issues/1331):
1. `conda install --revision 3` to rollback to the previous version. I guess this step is not necessary.
2. using `artiq_install.py` to install a brand new environment with a different name
3. This new environment will not work, so I use `pip install pyqt5` and then the new environment is back.
4. `deactivate` the old environment and `activate` it again. Now the old environment is back.

One guess is that installing `matplotlib` removed some `DLL` on the disk. So I think if I manually remove all qt-related package and reinstall them may make both of them. But can we get a better way to make `matplotlib` working together with ARTIQ?

### Steps to Reproduce

1. Install ARTIQ 5
2. Using `conda install matplotlib` to get matplotlib
3. Try to run `artiq_browser` or `artiq_dashboard`

### Expected Behavior

We should have the ability to use `matplotlib` and ARTIQ together.

### Actual (undesired) Behavior

See the details above

### Your System (omit irrelevant parts)

* Operating System: Windows 10
* ARTIQ version:artiq 5.7085.ae4f4b33

**Comment by sbourdeauducq** [comment]
Try with the latest Python 3.7 packages for ARTIQ-6.
