### ISSUE TITLE
Documentation: Zotino overflows inside +-10 V range

### ISSUE THREAD

**Issue by pathfinder49** [m-labs/artiq#1443]
# Bug Report

## One-Line Summary

Writing voltages close to (but smaller than) +10 V to Zotino leads to overflow in the driver. 

## Issue Details
[Zotino](https://github.com/sinara-hw/Zotino/wiki) is designed to provide +-10 V output range. It seems reasonable to expect voltages in the range [-10, +10] to be supported in the driver. Minimally, voltages in the range (-10, +10) should work. However, values approaching +10 V result in incorrect voltages.

In the current voltage_to_mu implementation voltages from +9.999847412109375 V lead to overflow. I expect this to result in -10 V being applied to the output. (I currently don't have physical hardware access to verify the output voltage.)

https://github.com/m-labs/artiq/blob/85e92ae28cd2de8d68ba15990a33aea1a62a516f/artiq/coredevice/ad53xx.py#L83-L97

### Steps to Reproduce
To reproduce on Zotino, write a voltage close to 10 V to a channel.

```python
self.zotino.write_dac(10 - 1e-5)
```

Or working from `voltage_to_mu()`
```python
offset_dacs=0x2000
vref=5.
voltage=10-1e-5
hex(int(round(0x10000*(voltage/(4.*vref)) + offset_dacs*0x4)))  # gives 0x10000 > 0xffff
```

### Expected Behavior

All voltages between +-10 V should be valid. 
```python
int(0xffff*(voltage/(4.*vref)) + offset_dacs*0x4)
```
seems like the correct conversion. This works for all voltages in the range [-10, +10].

**Comment by pathfinder49** [comment]
When fixing this, it might be worthwhile to also address https://github.com/m-labs/artiq/issues/1341

**Comment by pathfinder49** [comment]
I'm happy writing up a PR for this, #1341 and #1444. Please let me know if the suggested changes are accepable.

**Comment by jordens** [comment]
No. 10 V is not a valid output. The maximum output voltage is one LSB less. Please read the datasheet.

**Comment by pathfinder49** [comment]
> 
> 
> No. 10 V is not a valid output. The maximum output voltage is one LSB less. Please read the datasheet.

@jordens Thanks for pointing this out. The datasheet of the AD5372 does indeed say:
> VOUT = 4 × VREFx × (DAC_CODE – (OFFSET_CODE × 4))/216 + VSIGGND
In that case, this seems like a documentation issue. The [Zotino Wiki](https://github.com/sinara-hw/Zotino/wiki) clearly states a +-10 V range. This seems like it's worth adding to the docstring?

To me this also reinforces the need for #1444.

**Comment by dtcallcock** [comment]
>The Zotino Wiki clearly states a +-10 V range. 

As far as I know, there hasn't been an attempt to systematically ensure the Sinara Wiki pages are up to date.  The Zotino one is in a pretty sad state (doesn't seem to have been updated since v1.1).  Maintenance is reliant on people pitching in so if you have a bit of time to go through and improve it, that'd be great.  I understand that Creotech test bench coverage (like for [Urukul](https://github.com/sinara-hw/Urukul/wiki#production-unit-test-data)) will address some of the issues in the future.

**Comment by hartytp** [comment]
@pathfinder49 I think it's also fine for a Wiki to state +-10V for a DAC which goes to 1LSB below 10V; I wouldn't expect that level of detail from the Wiki.

I do agree that this is exactly the kind of gotcha that trips people up over and over again. I'd be in favor of documenting and adding input validation (which is something that's generally missing in ARTIQ IMO).
