### ISSUE TITLE
Coredevice Input Validation

### ISSUE THREAD

**Issue by pathfinder49** [m-labs/artiq#1446]
# ARTIQ Feature Request

## Problem this request addresses
Many coredevice drivers provide and/or use a conversion from SI units to machine-units. Many of these are vulnerable to machine-unit code over/underflow. This can result in silent undesired hardware responses (see #1443 & #1444).

## Describe the solution you'd like

Before returning a code, it should be checked for validity. Invalid codes should raise a `ValueError`. For many devices, codes are shorter than the default internal 32-bit integer representation. The majority of invalid codes can therefore be detected by checking the code bounds. For a 16-bit code I imagine somehting like:
```Python
code = do_conversion(*args)
if code < 0x0 or code > (1<<16)-1:
    raise ValueError("Invalid input!")
return code
```
This is both straight-forwad to implement and has minimal performance overheads (see #1445).

## Relevant coredevice methods/functions
It seems useful to compile a list of relevant coredevice methods/functions here. Feel free to add any that I've missed.

I've annotated the code size.

Edit (on advice from @jordens): Some of these conversions should over-flow and are marked in *italics*. In these cases documentation may be desirable. It also seems worthwhile checking for over/underflow data-collision. 

- [x] urukul.CPLD.set_att (8-bit)

- [x] AD9910.amplitude_to_asf (14-bit)

- [x] *AD9910.frequency_to_ftw (32-bit -> would need to work with int64 or do floating point math)*

- [x] *AD9910.turns_to_pow (16-bit)*

- [x] *AD9912.frequency_to_ftw (48-bit -> already using int64)*

- [x] *AD9912.turns_to_pow (16-bit)*

- [x] AD9914.amplitude_to_asf (12-bit)

- [x] *AD9914.frequency_to_ftw (32-bit)*

- [x] *AD9914.frequency_to_xftw (63-bit -> an int64 check might be a bit weak here...)*

- [x] *AD9914.turns_to_pow (16-bit)*

- [x] suservo.Channel.set_y (17-bit)

**Comment by jordens** [comment]
For DDS frequency and phase there should be no input validation. Frequencies outside the first Nyquist zone alias correctly according to Nyquist-Shannon. Preventing them also prevents convenient access to the other Nyquist zones and makes computation needlessly complicated. Phase wraps around modulo 2*pi radian (or 1 turn). Both are always valid. Please don't touch those and please don't restrict the input range. Adding a sentence to the docstring ist certainly worth though. The one thing that needs to be ensured is that overflow and sign bits don't collide with other data.

**Comment by pathfinder49** [comment]
> The one thing that needs to be ensured is that overflow and sign bits don't collide with other data.

In these cases, it might be nice to mask the code? Example: `code = do_conversion(*args) & 0xffff`

**Comment by jordens** [comment]
Yes. Absolutely.
