### ISSUE TITLE
docs: calling core.close() before scheduler.pause()

### ISSUE THREAD

**Issue by charlesbaynham** [m-labs/artiq#1452]
The docs (at https://m-labs.hk/artiq/manual/management_system.html#pauses) write that `self.core.close()` should be called before `self.scheduler.pause()`, however the comments in #390 imply that this is now handled automatically. Is this right? If so, I can make a PR for the docs.

**Comment by sbourdeauducq** [comment]
No, this was reverted before the 2.0 release. The manual is correct.
https://github.com/m-labs/artiq/commit/b9c3edd49f66a63f8a14878358e26741fcf9786f
