### ISSUE TITLE
create separate packages for core device binaries

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#146]
We should have 4 binary packages:
* python part of ARTIQ + artiq_flash.sh
* bitstream + BIOS + runtime for Pipistrello/QC1
* bitstream + BIOS + runtime for KC705/QC1
* bitstream + BIOS + runtime for KC705/QC2

**Comment by whitequark** [comment]
Done. Bitstreams &c are now available as `artiq-pipistrello-nist_qc1`, `artiq-kc705-nist_qc1` and `artiq-kc705-nist_qc2`.
