### ISSUE TITLE
How to check DHCP status?

### ISSUE THREAD

**Issue by cyqian97** [m-labs/artiq#1475]
# Question
How to check DHCP status?

## Description
I was trying to connect the Kasli board to a Ethernet port on the wall and control it from remote. The IT department has assigned an ip address to the mac address of the board, but when I connected it I was still not able to ping its ip. The artiq_dashboard was not working also. I was thinking that this might be caused by the DHCP setting but I don't know how to check it. I will be very appreciated if you can give me some advice on my problem!

**Comment by dnadlinger** [comment]
DHCP is not supported on the core device (Kasli).

**Comment by dnadlinger** [comment]
(Use something like `artiq_mkfs storage.img -s mac <…> -s ip <…>` and `artiq_flash … -f storage.img storage start` to configure the IP address; there is probably documentation somewhere.)

**Comment by sbourdeauducq** [comment]
DHCP support is https://github.com/m-labs/artiq/issues/1085

**Comment by cyqian97** [comment]
> 
> 
> DHCP is not supported on the core device (Kasli).

Thank you very much for your quick reply! I guess then I have to connect Kasli to my PC.
