### ISSUE TITLE
 IPv6 address in network device support packages reference

### ISSUE THREAD

**Issue by kgilmo** [m-labs/artiq#148]
In controller usage examples (and presumably elsewhere) "::1" is used, mapping to localhost

See #134

**Comment by sbourdeauducq** [comment]
True. What is the problem with that?

**Comment by kgilmo** [comment]
For pedagogical reasons, writing examples with the full domain name / IP address would be much clearer. Since the localhost may not be the correct server and someone new to this sort of thing may not recognize "::1" as corresponding to the localhost, being a bit more clear in the documentation would be helpful.

**Comment by sbourdeauducq** [comment]
The IP address and hostnames are obviously site-dependent, such examples would work only on one machine.

**Comment by jboulder** [comment]
https://github.com/m-labs/artiq/commit/ceb18d05b3ebf47bc2a02875b2b869fc0f6297ad

ACK

Another new ARTIQ user ran into this problem. It would help if NDSP
examples use an obvious placeholder for fully specified DNS name. e.g.
artiqmaster.mydomain.com
