### ISSUE TITLE
Fastino wide interface configuration

### ISSUE THREAD

**Issue by pathfinder49** [m-labs/artiq#1481]
# ARTIQ Feature Request
Add configuration option for Fastino interface for use in `gateware.target`

## Problem this request addresses

Reading the source code, it looks like Fastino is hard coded to use the narrow interface. This arragnement forces all Fastino boards in an installtion to use the same interface width. 
https://github.com/m-labs/artiq/blob/f265976df62ec5bc358de68f8808ade96198ae15/artiq/gateware/eem.py#L621-L626

## Describe the solution you'd like
The wide interface options like `log2_width` should be arguments to `gateware.eem.Fastino.add_std()`

**Comment by pathfinder49** [comment]
@jordens Is it correct that `log2_width=5` is the only change needed to use the wide interface with the current implementation?

**Comment by jordens** [comment]
No. You also need to use a different API in kernels. See the documentation and the relevant [commit](https://github.com/m-labs/artiq/commit/e803830b3b3cc791fd98425ac30a4efb1c210485#diff-6c527b06ec83bd78f3a1e9b785d616d6)

**Comment by pathfinder49** [comment]
Thanks, so `log2_width=5` to build the correct kasli gateware and the "group" api for writing to Fastino?

**Comment by jordens** [comment]
This setting was added for you to evaluate, test, and characterize the impact on RTIO fabric and performance of wide vs narrow RTIO channels. Before making it a stable API with documentation, integration, tests etc. could you share the results. Also depending on the results it might be much better to just choose one value.

**Comment by hartytp** [comment]
@jordens my preference would be to keep the wide RTIO interface even if it doesn't work with DMA for now.
