### ISSUE TITLE
Artiq 5 can't be installed through Conda

### ISSUE THREAD

**Issue by stodaro** [m-labs/artiq#1482]
# Bug Report

## One-Line Summary

Artiq 5 is unavailable through the conda channel.

## Issue Details

I'm attempting to install Artiq 5 through conda, and it defaults to downloading 6.7251.91c93e1a.beta.  

### Steps to Reproduce

1. I'm following the install commands as listed [here](https://m-labs.hk/artiq/manual/installing.html#installing-via-conda-windows-linux):
```
$ conda config --prepend channels https://conda.m-labs.hk/artiq-beta
$ conda config --append channels conda-forge
$ conda create -n artiq artiq
```
After this, the output of `artiq-client --version` is `6.7251.91c93e1a.beta`.

### Expected Behavior

I would expect to be able to roll back to Artiq 5.0 by either creating my environment with `conda create -n artiq artiq=5.0` or by using `conda install artiq=5.0` on an already-created environment.

### Actual (undesired) Behavior

The output of `conda install artiq=5.0`:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - artiq=5.0

Current channels:

  - https://conda.anaconda.org/m-labs/linux-64
  - https://conda.anaconda.org/m-labs/noarch
  - https://conda.m-labs.hk/artiq-beta/linux-64
  - https://conda.m-labs.hk/artiq-beta/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

The output of `conda search artiq -c  https://conda.m-labs.hk/artiq-beta` is

```
Loading channels: done
# Name                       Version           Build  Channel             
artiq                            2.0 py_0+gita9bef3c  m-labs              
artiq                            2.1 py_0+git453b29a  m-labs              
artiq                            2.2 py_0+gitf5cd092  m-labs              
artiq                            2.3 py_0+gitc78aa86e7272  m-labs              
artiq                            2.4 py_0+gite06b9063  m-labs              
artiq                            2.5 py_0+gitb8469987  m-labs              
artiq                            3.0 py_0+git04a9a0ce  m-labs              
artiq                            3.1 py_0+git4c2f25e8  m-labs              
artiq                            3.2 py_1+gita4337944  m-labs              
artiq                            3.3 py_1+git59fe69a4  m-labs              
artiq                            3.4 py_0+git9db30ce8  m-labs              
artiq                            3.5 py_0+git59fdb32b  m-labs              
artiq                            3.6 py_0+git394b66cd  m-labs              
artiq                            3.7 py_0+gitf96084e8  m-labs              
artiq                            4.0   0+gitbf50dcf7  m-labs              
artiq                6.7251.91c93e1a.beta               0  artiq-beta
```
I would expect to see something with a 5 in this list.  My interpretation of this is that 6.7251.91c93e1a.beta is an unreleased beta.   
 (If this is an inaccurate interpretation of that number, I'm happy to be corrected!)  I'd vastly prefer to work with the stable release.

### Your System (omit irrelevant parts)

* Operating System: Ubuntu 14.04
* ARTIQ version: 6.7251.91c93e1a.beta
* Output of `conda list`: [artiq_conda_list.txt](https://github.com/m-labs/artiq/files/4891563/artiq_conda_list.txt)

**Comment by sbourdeauducq** [comment]
The correct channel URL for the stable channel is https://conda.m-labs.hk/artiq and not https://conda.m-labs.hk/artiq-beta - I will fix the manual.
If you are using Linux you really should not be using conda.
