### ISSUE TITLE
thorlabs_tcube.driver.get_encoder_counter() returns None

### ISSUE THREAD

**Issue by kgilmo** [m-labs/artiq#149]
Confirmed that get_encoder_counter() returns int when using stand-alone thorlabs_tcube_controller and artiq_rpctool. However, when accessing device in experiment a call to self.thor_tcube.get_encoder_counter() returns None. This is also true of self.thor_tcube.get_dc_status_update().

**Comment by jboulder** [comment]
```python
from artiq import *


class ThorFun(EnvExperiment):
    """Thorlabs Fun"""

    def build(self):
        #self.init_logger()
        #  self.setattr_device("scheduler")
        self.thor_tcube = self.get_device("thor_tcube")

    def run(self):
        move = self.thor_tcube.move_relative(10000)
        count = self.thor_tcube.get_encoder_counter()
        count2 = self.thor_tcube.get_encoder_counter()
        # x = count*2.9e-9
        s = "Distance in m: {}".format(type(count2))
        print(s)
```

**Comment by sbourdeauducq** [comment]
Are you using "best_effort: true" in device_db?

**Comment by sbourdeauducq** [comment]
My guess is you are, and it fails to connect and therefore can only return None (it should print a warning in the log too). I just checked that BestEffortClient returns the correct values when the connection is successful.

**Comment by kgilmo** [comment]
Yes, I was using "best_effort:true" in device_db. I see, so it's a connection issue that's suppressed with BestEffortClient and returns None.

**Comment by sbourdeauducq** [comment]
If you have confirmed that, can you close the issue?
