### ISSUE TITLE
Exception object causes memory corruption

### ISSUE THREAD

**Issue by pca006132** [m-labs/artiq#1491]
# Bug Report

## One-Line Summary

Exception objects are dangling pointers and could cause memory corruption.

## Issue Details

https://github.com/m-labs/artiq/blob/2a2f5c4d58c5146479e52359943c0c9b5bd15548/artiq/firmware/ksupport/eh_artiq.rs#L166-L169

The exception object is actually a dangling pointer pointing to somewhere in the stack and can be overwritten by other code.

If we copy the exception object before raising the exception, we could avoid memory corruption, but we would get memory leak as we cannot deallocate the object after caught. 

Update: This cannot be solved by prohibiting the user to capture the exception object. See example 2.

### Example 1

```python
from artiq.experiment import *

class TestException(EnvExperiment):
    def build(self):
        self.setattr_device("core")

    @kernel
    def run(self):
        try:
            raise ValueError
        except ValueError as e:
            try:
                raise IndexError
            except:
                pass
            try:
                raise e
            except ValueError as e2:
                print("ValueError")
            except IndexError as e3:
                print("Should not happen")
```

#### Expected Behavior

Prints `ValueError`.

#### Actual (undesired) Behavior

Prints `Should not happen`, as the memory for `e` is overwritten in the second `raise`. 

### Example 2
```python
from artiq.experiment import *

class TestException(EnvExperiment):
    def build(self):
        self.setattr_device("core")

    @kernel
    def run(self):
        try:
            try:
                raise ValueError
            finally:
                try:
                    raise IndexError
                except IndexError:
                    pass
        except ValueError:
            print("ValueError")
        except IndexError:
            print("Should not happen")
```

Expected and actual behavior are the same as example 1.

**Comment by pca006132** [comment]
Update: We don't have to capture the exception object.

```python
from artiq.experiment import *

class TestException(EnvExperiment):
    def build(self):
        self.setattr_device("core")

    @kernel
    def run(self):
        try:
            try:
                raise ValueError
            finally:
                try:
                    raise IndexError
                except IndexError:
                    pass
        except ValueError:
            print("ValueError")
        except IndexError:
            print("Should not happen")
```
Same behavior.

**Comment by sbourdeauducq** [comment]
Adding to ARTIQ-7 milestone as we want to keep runtime compatibility with NAC3.
