### ISSUE TITLE
artiq_sinara_tester: Enter keypress detection with while loops gets stuck

### ISSUE THREAD

**Issue by HarryMakes** [m-labs/artiq#1519]
# Bug Report

## One-Line Summary

Given an ARTIQ experiment (e.g. the `SinaraTester` class in artiq/frontend/artiq_sinara_tester.py) containing a while loop checking keypress of "Enter" (e.g. see [these lines](https://github.com/m-labs/artiq/blob/b2572003acfef50b32aa00cd17388f00fed5f87a/artiq/frontend/artiq_sinara_tester.py#L118-L126)), when the user runs it on ARTIQ commit b2572003acfef50b32aa00cd17388f00fed5f87a or above, the loop seems to stop after a few iterations, while this does not happen before this commit.

### Steps to Reproduce

1.  Git-clone ARTIQ as local repo, and include it in PYTHONPATH with `export`.
2.  Checkout commit b2572003acfef50b32aa00cd17388f00fed5f87a on the local repo.
3.  Prepare a standalone Kasli with or without any peripherals, generate its device_db.py.
3.  Do: `artiq_sinara_tester`
4.  The first LED (on SFP1) blinks for 5 or 6 times, then stops.
5.  Try hitting Enter on the running `artiq_sinara_tester`. It doesn't respond.
6.  Ctrl-C killing the tester and re-run will repeat steps 4-5.

### Expected Behavior

Instead of step 4, the LED should blink continuously. Once the user hits Enter, the second LEd (on SFP2) will blink instead.

By git-cloning ARTIQ in step 1, the expected behaviour can be easily reproduced by replacing step 2 with checking out older commits on the local repo.

### Your System (omit irrelevant parts)

* Operating System: NixOS 20.03.2869.0d60b0b10ea (Markhor)
* ARTIQ version: commit b2572003acfef50b32aa00cd17388f00fed5f87a
* ARTIQ Log shows NO errors.

**Comment by HarryMakes** [comment]
Here is a simpler experiment that also shows the inability to keep detecting Enter keypress: https://gist.github.com/HarryMakes/f619d195bbfcbc92cf0fc89fb92ea09d

In commits before b2572003acfef50b32aa00cd17388f00fed5f87a, e.g. 69f0699ebd8db2232a705f61a5655f99fba96edc, when running this experiment, the current LED will stay on until the user press Enter, which is when the next LED will be lit up and stay on until the user press Enter again and end the experiment.

**Comment by pca006132** [comment]
The reason for this is due to missing type conversion which raise an exception, cannot concat bool to bytearray.
I'm checking if there is any other problems as well.

**Comment by pca006132** [comment]
This patch should be sufficient.
```diff
diff --git a/artiq/coredevice/comm_kernel.py b/artiq/coredevice/comm_kernel.py
index babf035b..98211d59 100644
--- a/artiq/coredevice/comm_kernel.py
+++ b/artiq/coredevice/comm_kernel.py
@@ -316,7 +316,7 @@ class CommKernel:
         self._write(self.pack_float64(value))
 
     def _write_bool(self, value):
-        self._write(1 if value == True else 0)
+        self._write(b'\x01' if value else b'\x00')
 
     def _write_bytes(self, value):
         self._write_int32(len(value))
@@ -425,7 +425,7 @@ class CommKernel:
         elif tag == "b":
             check(isinstance(value, bool),
                   lambda: "bool")
-            self._write_int8(value)
+            self._write_bool(value)
         elif tag == "i":
             check(isinstance(value, (int, numpy.int32)) and
                   (-2**31 < value < 2**31-1),
```

I think we should generate an exhaustive list of RPC with various type for testing... This kind of type error is annoying. I wish there is compile time check :(

**Comment by HarryMakes** [comment]
Test successful with the change. Thanks for the fix!
