### ISSUE TITLE
clock settings Kasli v2.0

### ISSUE THREAD

**Issue by SingularitySurfer** [m-labs/artiq#1528]
https://github.com/m-labs/artiq/blob/9214e0f3e25dc8f0036970213acf90ee0cc56fb5/artiq/firmware/runtime/rtio_clocking.rs#L78
https://github.com/sinara-hw/Kasli/issues/82
Input clockdivider (n31 reg) of CKIN1 has to be set to 6 for 10MHz external reference on Kasli v2.0

**Comment by sbourdeauducq** [comment]
Good catch. Did it work after fixing that?

**Comment by SingularitySurfer** [comment]
Yep, the si5324 locks with just this change. I'm not sure if there need to be further changes, but as 75/6=12.5 it would make sense when the old setting was for 125MHz.
