### ISSUE TITLE
Incorrect exit order for `with` statement with multiple context

### ISSUE THREAD

**Issue by lriesebos** [m-labs/artiq#1547]
# Bug Report

## One-Line Summary

When opening multiple context in a single `with` statement in a kernel, the exit call order is incorrect.
Probably the fix for #1478 introduced this bug.

### Steps to Reproduce

```python
from artiq.experiment import *


class MyContext:
    def __init__(self, name):
        self.name = name

    @portable
    def __enter__(self):
        print('enter')
        print(self.name)

    @portable
    def __exit__(self, exc_type, exc_val, exc_tb):
        print('exit')
        print(self.name)


class MinimalContextExperiment(EnvExperiment):

    def build(self):
        self.setattr_device('core')
        self.context_a = MyContext('a')
        self.context_b = MyContext('b')

    @kernel
    def run(self):
        with self.context_a:
            with self.context_b:
                print('in both context, multiple with statements')

        with self.context_a, self.context_b:
            print('in both context, single with statement')
```

### Expected Behavior

Opening both context in separate `with` statements should behave the same as opening both context in a single `with` statement.

1. enter a
1. enter b
1. exit b
1. exit a

### Actual (undesired) Behavior

Exit order of single `with` statement with multiple context is incorrect.

1. enter a
1. enter b
1. exit a
1. exit b

### Your System (omit irrelevant parts)

* Operating System: Ubuntu 20.04
* ARTIQ version: 5.7134.68582b8d

**Comment by sbourdeauducq** [comment]
>  Probably the fix for #1478 introduced this bug.

Indeed it did. Reverted.
