### ISSUE TITLE
auto generation of empty *.pyon

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#156]
Find that ARTIQ does not automatically generate an empty dataset_db.pyon if dataset_db.pyon is missing. Auto generation is better default behavior vs throwing exception. Same goes for artiq_gui.pyon and device_db.pyon.

artiq_gui.pyon might better be called gui_db.pyon to match new naming scheme.

**Comment by sbourdeauducq** [comment]
Ok for dataset_db.

I do not see the point of having an empty device_db.pyon. How would you use ARTIQ with no devices?
Note that this file is read-only for the master, i.e. the way to add new devices is to modify this file and trigger a rescan.

The GUI already creates artiq_gui.pyon when it is not present.

**Comment by jboulder** [comment]
For both debugging and to eliminate accumulated dead datasets, it's
convenient to simply delete dataset_db.pyon and fire up ARTIQ again.

Thank you for making this change.
