### ISSUE TITLE
Mirny: RF fail after power cycle

### ISSUE THREAD

**Issue by occheung** [m-labs/artiq#1560]
# Bug Report
## One-Line Summary

Some RF channels do not generate RF signal at the first time running a python script, right after a power cycle.

## Issue Details

A RF channel may fail to generate the required RF signal when running a python script right after power cycle. After running the same script for the second time onward, the RF channel will generate RF signal properly.

### Steps to Reproduce

1. Power cycle.
2. Run the below script. (with reference to the code snippet in #1530)
3. Measure the RF signal. (I used gqrx with HackRF)
4. Run the script again.
5. Make another measurement.

#### Script
```python
from artiq.experiment import *
from pprint import pprint

class TestMirny(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.setattr_device("mirny0_ch0")

        self.ch = self.mirny0_ch0

    @kernel
    def run(self):
        self.core.reset()
        self.ch.cpld.init(True)
        self.ch.init()

        self.ch.set_att_mu(160)
        self.ch.sw.on()
        self.core.break_realtime()

        self.ch.set_frequency(1006*MHz)     # For easier observation
        delay(5*ms)
        print(self.ch.read_muxout())

    def analyze(self):
        pprint(self.ch.info())
```

### Expected Behavior

Mirny should generate an RF signal at frequency 1006 MHz at anytime after running the script above.

### Actual (undesired) Behavior

Run the script the first time:
- PLL lock LED is off
- RF switch LED is on
- RF signal may not be generated
- Text output:
```
True
{'f_outA': 1006000000.0,
 'f_outB': 8048000000,
 'f_pfd': 125000000,
 'f_vco': 4024000000,
 'output_divider': 4,
 'pll_frac1': 3221225,
 'pll_frac2': 59,
 'pll_mod2': 125,
 'pll_n': 32,
 'prescaler': '4/5',
 'ref_counter': 1,
 'ref_divider': False,
 'ref_doubler': False,
 'sysclk': 125000000.0}
```
Run the script again:
- PLL lock LED is off
- RF switch LED is on
- RF signal (of 1006 MHZ) is generated
- Text output: (Identical text output)
```
True
{'f_outA': 1006000000.0,
 'f_outB': 8048000000,
 'f_pfd': 125000000,
 'f_vco': 4024000000,
 'output_divider': 4,
 'pll_frac1': 3221225,
 'pll_frac2': 59,
 'pll_mod2': 125,
 'pll_n': 32,
 'prescaler': '4/5',
 'ref_counter': 1,
 'ref_divider': False,
 'ref_doubler': False,
 'sysclk': 125000000.0}
```
### Your System (omit irrelevant parts)

* Version of the gateware and runtime loaded in the core device: 6.7512.1ce505c5.beta
* Hardware involved: Mirny v1.1

Follow-up: #1530 @airwoodix

**Comment by airwoodix** [comment]
I can reproduce this, thanks. Seems to be linked to the ADF5356 init. Is it fixed if you do a blind init? If so, could you please check that #1596 fixes it as well (non-blind)?
