### ISSUE TITLE
Use pytest to run all the unit tests

### ISSUE THREAD

**Issue by aaditkamat** [m-labs/artiq#1567]
# ARTIQ Feature Request

## Problem this request addresses

As I see it, there isn't currently a way to run all the unit tests at once.

## Describe the solution you'd like

I would like the current unit tests to be compatible with the `pytest` framework which provides a way to run all the tests at once.
We can then set up a [GitHub workflow to run the tests, linters etc.](https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python) so that contributors can see the results of the CI run on GitHub itself.

## Additional context

@whitequark had previously tried to [run ARTIQ tests through pytest]( https://github.com/m-labs/artiq/issues/657) unsuccessfully. Hence, I thought it's useful to run tests using `pytest`.  It's also one of the most popular Python testing frameworks out there.

**Comment by sbourdeauducq** [comment]
https://git.m-labs.hk/m-labs/nix-scripts (see it in action on nixbld.m-labs.hk) already runs all the Python tests via ``python -m unittest discover`` and more, e.g. hardware-in-the-loop tests.

Using pytest would potentially be ok, though ``unittest`` is included in the standard library and is good enough IMO; in fact, it's not clear to me what improvement pytest will really bring.

If you care about this, please send PRs here and in nix-scripts (I can create you an account on git.m-labs.hk if you want). I'm not interested in GitHub workflows which are non-reproducible and depend on proprietary software, among other problems.
