### ISSUE TITLE
artiq_ddb_template base 16 counting

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#1583]
device_db.py generated by artiq_ddb_template.py lists channel numbers in base-16. Please use base-10 as this is both ARTIQ convention and easier to read. 

https://github.com/m-labs/artiq/blob/c675488a99ec9bf18220138460509500bb3f1d5f/artiq/frontend/artiq_ddb_template.py#L95

**Comment by sbourdeauducq** [comment]
> Please use base-10 as this is both ARTIQ convention

Where is it convention?

> and easier to read.

Base 10 is definitely not easier for DRTIO satellite channel numbers.

**Comment by jbqubit** [comment]
OK. I can see how this is easier since the advent of DRITIO satellites.
