### ISSUE TITLE
compiler: Move _artiq_raise_assert to runtime

### ISSUE THREAD

**Issue by dnadlinger** [m-labs/artiq#1587]
For assertions, the compiler currently synthesizes a function, `_artiq_raise_assert`, to build the exception object with the given message/… and raise it. This is a remnant from an earlier design, where more parameters were baked into the emitted code rather than passed to `_artiq_raise_assert`. Now, however, the function is the same for each module, and should be moved into the runtime library instead.

**Comment by sbourdeauducq** [comment]
Adding to ARTIQ-7 milestone as we want to keep runtime compatibility with NAC3.

**Comment by sbourdeauducq** [comment]
Seems NAC3 would not use such a function.
