### ISSUE TITLE
minor improvements after Python 3.5.1 is out

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#159]
* always bind localhost addresses so that tools can always be used locally without specifying the host (needs http://bugs.python.org/issue23630)
 * remove artiq.tools.workaround_asyncio263

**Comment by jordens** [comment]
3.5.1 has precipitated
http://docs.continuum.io/anaconda/changelog

**Comment by sbourdeauducq** [comment]
Done.
