### ISSUE TITLE
documentation: HDFView > 3.x

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#1607]
ARTIQ manual [mentions](https://m-labs.hk/artiq/manual/getting_started_mgmt.html?highlight=hdf5) existence of HDFView but doesn't recommend version number. Older versions of HDFView show ARTIQ hdf5 archives as [empty](https://github.com/m-labs/artiq/issues/1340). Please consider updating manual to specify HDFView >=3.x and/or adding supported version to nix shell. This is an easy pitfall that one of my students just encountered.

**Comment by dhslichter** [comment]
This seems like something that is HDFView's fault.  Why would a student install an old version of HDFView instead of the latest version?

**Comment by sbourdeauducq** [comment]
nixpkgs has an old version (2.14). Do you happen to know if hdf_java needs to be updated as well?

**Comment by sbourdeauducq** [comment]
I think that's not a "documentation" issue, this should be just updated in nixpkgs.

**Comment by jbqubit** [comment]
> Why would a student install an old version of HDFView instead of the latest version?

Depending on the Ubuntu distro version different versions of HDFView are installed as noted in the [old Issue](https://github.com/m-labs/artiq/issues/1340). It's not uncommon for Ubuntu to be full release numbers behind on tools like HDFView. 

> I think that's not a "documentation" issue, this should be just updated in nixpkgs.

Agreed that it will be easier to maintain (vs documentation) if the right version is included the default ARTIQ nixpkgs.

**Comment by jbqubit** [comment]
> Do you happen to know if hdf_java needs to be updated as well?

I've never explicitly used hdf_java. I don't know if it is a dependency of HDFView.

**Comment by astro** [comment]
> nixpkgs has an old version (2.14). Do you happen to know if hdf_java needs to be updated as well?

> I think that's not a "documentation" issue, this should be just updated in nixpkgs.

There has never been a version other than hdfview-2.14 and hdf_java-3.3.2 in nixpkgs. They are already the [latest official releases](https://support.hdfgroup.org/products/java/index.html) unfortunately.

**Comment by sbourdeauducq** [comment]
OK, it's merged now and should be updated in nixpkgs 21.03 (in a couple months). How important is it to support older nixpkgs?

**Comment by jbqubit** [comment]
It's OK if it takes a month or two for this fix to hit artiq nix.

**Comment by astro** [comment]
It is [going to be May 2021](https://github.com/NixOS/rfcs/pull/80).

**Comment by sbourdeauducq** [comment]
Confirmed hdfview-3.1.2 in nixpkgs 21.05 (used for ARTIQ 6 and 7).

**Comment by jbqubit** [comment]
Thanks @astro @sbourdeauducq !
