### ISSUE TITLE
get functions for frequency, amplitude, phase parameters of AD9910

### ISSUE THREAD

**Issue by fanmingyu212** [m-labs/artiq#1616]
# ARTIQ Feature Request

## Problem this request addresses

There is no an explicit function to get the frequency, amplitude, or phase from a AD9910 device. I understand that the values can be get using `read32` function with the corresponding registry addresses, but I think having those explicit get functions for the AD9910 device helps reducing some of the code duplication that I imagine many labs using urukul have. Please let me know if this is already addressed somewhere or this idea does not make sense.

## Describe the solution you'd like

Add `get_ftw`, `get_asf`, `get_pow` functions in `artiq.coredevice.ad9910.AD9910` class, and add `get_frequency`. `get_amplitude`, and `get_phase` as corresponding counterparts in natural units.

**Comment by lriesebos** [comment]
By coincidence, I have made that code earlier this week and I expect to get it tested soon. Once I have it I will make a pull request for it.
