### ISSUE TITLE
EEM JSON schema documentation

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#1624]
Update documentation to reflect new JSON schema for gateware/firmware build and device_db.py auto-generation. 

* The Issue where JSON file format is discussed is here. #1474 

* The Kasli generic JSON schema is here: artiq/gateware/targets/kasli_generic.schema.json 

* Example JSON files for different lab setups are [here](https://git.m-labs.hk/m-labs/sinara-systems ).

**Comment by sbourdeauducq** [comment]
Is this still important? It doesn't seem very difficult to figure it out from the examples, the schema, and the code.
