### ISSUE TITLE
bool list converts to int list during RPC data transfer

### ISSUE THREAD

**Issue by lriesebos** [m-labs/artiq#1635]
# Bug Report

## One-Line Summary

When sending a list of bool from the kernel to the host using an RPC function, the list arrives as a list of ints.
This happens since ARTIQ 6.
@sbourdeauducq is this expected behavior?

### Steps to Reproduce

```python
from artiq.experiment import *

class ArtiqTestExperiment(EnvExperiment):

    def build(self):
        self.setattr_device('core')

    @kernel
    def run(self):
        self.foo([True])
        self.foo([False])

    def foo(self, val):
        print(f'val={val[0]}, type={type(val[0])}')
```

### Expected Behavior

Output of the program:
```
val=True, type=<class 'bool'>
val=False, type=<class 'bool'>
```

### Actual (undesired) Behavior

The values arrive as a list of integers. Output of the program:
Output of the program:
```
val=1, type=<class 'int'>
val=0, type=<class 'int'>
```

This behavior is only observed for bool lists. Sending a single bool value over RPC works as expected.

### Your System (omit irrelevant parts)

* Operating System: Ubuntu 20.04
* ARTIQ version: ARTIQ v6.7582.c2248278

**Comment by sbourdeauducq** [comment]
>  @sbourdeauducq is this expected behavior?

No.

**Comment by lriesebos** [comment]
Really appreciate the fix @dnadlinger !
