### ISSUE TITLE
Phaser: Rename `ndiv` -> `nint`.

### ISSUE THREAD

**Issue by pathfinder49** [m-labs/artiq#1638]
# Bug Report

## One-Line Summary

Phaser-Upconverter LO configuration seems to be missing options.

## Issue Details
I'm attempting to create a `device_db` for a phaser-upconverter. With the current coredevice driver, the registers inside the TRF372017 must be configured manually. The documentations references the TRF372017 data-sheet without further explanation. 
https://github.com/m-labs/artiq/blob/d04bcd8754f11780d02d179285712980701d6518/artiq/coredevice/trf372017.py#L1-L6
To avoid misunderstandings, I'll summarise my understanding of the required configuration options. Currently, all bar one of these options seem to be exposed.

From the data-sheet it seems like the following values must be configured to achieve a desired LO frequency:
* LO_DIV_SEL
* PLL_DIV_SEL
* NINT (**this name does not appear in the driver**, @jordens am I missing something obvious?)
* PRSC_SEL
* RDIV 

For "fractional mode" the following additional options are used
* NFRAC and
![image](https://user-images.githubusercontent.com/14295481/111631294-2273a280-87eb-11eb-933e-42d3a86a32c5.png)

If an external VCO/LO is provided the following options are needed:
* EN_EXTVCO
* NEG_VCO

### Expected Behavior
All the options above should be exposed and the names should match with the data-sheet. (Naming already matches for the exposed options)

**Comment by jordens** [comment]
`ndiv`?

**Comment by pathfinder49** [comment]
It looks like it does indeed correspond to NINT in your implementation.
https://github.com/m-labs/artiq/blob/d04bcd8754f11780d02d179285712980701d6518/artiq/coredevice/trf372017.py#L93-L97

Givent the documentation is the data-sheet, it seems best to match the names from the datasheet. Especially, as NDIV is used for something else in the data-sheet.
![image](https://user-images.githubusercontent.com/14295481/111708481-d56cec00-883d-11eb-8f8a-916c1cd7ae53.png)

**Comment by jordens** [comment]
No. That's exactly the same thing and not something else.
But do rename it.
