### ISSUE TITLE
compiler wishlist

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#1645]
I'm working on the specifications for the compiler improvement project and would like your feedback.

* Are there compiler issues previously reported on GitHub that you think are particularly important?
* Are there any bug or issues that were not reported, but you think are important?
* What workarounds for the current compiler's limitations do you use? For example, do you sometimes use string operations to generate kernel code to be compiled?

Please reply before April 7th.

**Comment by pathfinder49** [comment]
I found #1468 paticularly insideous/tricky to track down. I've also seen silent data-corruption from the lack of uint support (cc #1628), implementing #1524 would avoid such issues in future.
