### ISSUE TITLE
Phaser Upconverter: Improve default configuration.

### ISSUE THREAD

**Issue by pathfinder49** [m-labs/artiq#1648]
# Bug Report

## One-Line Summary
The Phaser upconverter phase-frequency detector is not configured at the frequency targeted by the hardware design.

## Issue Details
Phaser was designed [targeting a phase-frequency detector clock of 62.5 MHz](https://github.com/sinara-hw/Phaser/issues/49#issuecomment-555163525). This frequency should be kept high to keep phase noise low. However, the current default is a 6 MHz phase-frequency detector clock.

### Expected Behavior

Phaser defaults to a 125 MHz clock from Kasli, instead of an external reference. The phase-frequency detector should default to 62.5 MHz.

### Suggested Fix
Default to `rdiv = 2`.
To keep the calibration clock within it's 1 MHz spec, we will also need `cal_clk_sel = 0b1110 ` (DIV64)
https://github.com/m-labs/artiq/blob/8002fcf8bbeb3425f19d66244130c6f1b1f9b7a3/artiq/coredevice/trf372017.py#L7-L12

**Comment by jordens** [comment]
As discussed, the user needs to investigate and tune PLL parameters depending on the application. The current default ones are mostly just the ones [Greg found to simply work](https://github.com/sinara-hw/Phaser/issues/101#issuecomment-653691964).
