### ISSUE TITLE
influxdb logs everything by default

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#165]
The current influxdb_patterns.pyon implementation does: "Keys that math no pattern are logged." It seems a careless user will pollute the time-series database since every broadcast dataset will be automatically logged. Better default behavior is "Keys that match no pattern are ignored." Then inclusion is explicit. 

The default behavior makes database maintenance more difficult. 

Comment: The current code is based on "filtering out" datasets. A more nonsensical approach would be "filtering for inclusion".

**Comment by sbourdeauducq** [comment]
Having ``-*`` as the very first pattern in the filter changes the behavior to exclude by default.

When no pattern is specified, including everything enables quick startup without the user having to define patterns.
