### ISSUE TITLE
Tool to Check the Firmware Version of Urukul

### ISSUE THREAD

**Issue by rgresia-umd** [m-labs/artiq#1653]
# ARTIQ Feature Request

## Problem this request addresses

#1652 

## Describe the solution you'd like

A tool or an addition to an existing tool to be able to determine the current firmware version of Urukul and possibly other devices. Another solution could be an automated check that alerts the user `current firmware: X  on Y device is  incompatible`.

## Additional context

Earlier versions of Urukul, v1.2-3, requires a specific [patch](https://github.com/sinara-hw/Urukul/wiki/patch2019) and there are a variety of [firmware versions](https://github.com/quartiq/urukul/releases) for Urukul CPLD.

**Comment by sbourdeauducq** [comment]
> Earlier versions of Urukul, v1.2-3, requires a specific [patch](https://github.com/sinara-hw/Urukul/wiki/patch2019)

What does this have to do with the Urukul CPLD gateware?

**Comment by sbourdeauducq** [comment]
> Another solution could be an automated check that alerts the user `current firmware: X on Y device is incompatible`.

AFAIK that's what the ``proto_rev`` check does on Urukul.

**Comment by pathfinder49** [comment]
IIRC, `proto_rev` is shared between protocol-compatible CPLD versions. (Not quite the same as the firmware version)
