### ISSUE TITLE
influxdb_patterns.pyon not documented

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#166]
Suggested documentation addition. Sample contents of influxdb_patterns.pyon.
{"+patternA","-patternB","patternC"}

Dataset name -> action
* patternA -> logged
* patternB -> not logged
* patternC -> not logged
* patternD -> logged

**Comment by sbourdeauducq** [comment]
Please provide input on this:
https://ssl.serverraum.org/lists-archive/artiq/2015-October/000572.html

**Comment by sbourdeauducq** [comment]
@jordens Again this breaks a user API (see ML thread) so I would defer this to 2.0.

**Comment by jordens** [comment]
I am pretty sure the impact would be minimal. I don't know of anyone other than me and Joe who would be affected. But ok to delay it.
