### ISSUE TITLE
build failed 9826b19

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#176]
Latest git commit is 9826b19 on 11/19 but last build was 108aed5 11/17. .

**Comment by fallen** [comment]
I think the build failed on travis, see: https://github.com/m-labs/artiq/issues/171#issuecomment-158339783
https://travis-ci.org/m-labs/artiq/builds

**Comment by sbourdeauducq** [comment]
Yes, we know about this. It seems Continuum Analytics updated conda in a way that broke the ARTIQ build script. Please do not report travis build errors here - there are already IRC notifications for this.
