### ISSUE TITLE
slow scan when repository contains lots of non-experiment Python files

### ISSUE THREAD

**Issue by fanmingyu212** [m-labs/artiq#1766]
# ARTIQ Feature Request

## Problem this request addresses

`ExperimentDB` scans the whole repository when looking for experiments. This is extremely slow on a relatively large repo (takes ~10 mins to scan our experiment repository).

## Describe the solution you'd like

Add an experiment subdirectory when starting `artiq_master`, and `ExperimentDB` should only scan experiments in this subdirectory.

See https://github.com/m-labs/artiq/compare/master...Jayich-Lab:mf/artiq_master_experiment_subdir?expand=1 for a patch that implements this solution. It should be backward compatible (default `experiment_subdir=""`), and we can run experiments from the explorer GUI. I can create a PR for this if it looks good.

**Comment by fanmingyu212** [comment]
In the repository we also have analysis code which we would rather not move elsewhere. We also have test code, GUIs, etc.

Certainly the problem can be solved by moving other files away. If defining an experiment subdirectory is supported, users can be more flexible about code organization though which I think is a good thing. It seems that the `_RepoScanner` was designed probably with this issue considered: `subdir` is already an argument of `_RepoScanner._scan` function but it is currently not used in `ExperimentDB`.

**Comment by sbourdeauducq** [comment]
Are the bulk of the files that make it slow Python *.py files, or something else?

**Comment by fanmingyu212** [comment]
Yes they are python files (I think non-py files are skipped in the scan).

**Comment by sbourdeauducq** [comment]
Would opening the file and eliminating it immediately (before spawning the worker) if it doesn't contain the strings "import artiq" or "from artiq import" resolve this?
What is slow is creating the worker processes. Recycling worker processes would also improve scan speeds generally.

**Comment by fanmingyu212** [comment]
By recycling the worker, do you mean this? https://github.com/m-labs/artiq/compare/master...Jayich-Lab:mf/recycle_exp_scan_worker?expand=1

**Comment by sbourdeauducq** [comment]
Yes, though you do want to handle errors and probably restart the worker after some experiments have been scanned (either fixed number or based on memory consumption) to avoid using too much memory (otherwise all your Python files get loaded at the same time).

**Comment by fanmingyu212** [comment]
I did not see a significant improvement from recycling the worker (it has been running for 7 mins now and has not finished, and I shut `artiq_master` down due to high memory usage (as you mentioned it would be an issue).

**Comment by sbourdeauducq** [comment]
If your machine began swapping, it would slow things down.

**Comment by fanmingyu212** [comment]
Yes I agree. I think even ~1 min to scan a repository (before it has to use the swap) seems really slow though.

**Comment by fanmingyu212** [comment]
It seems that nearly all the time is spent importing the modules

https://github.com/m-labs/artiq/blob/35d21c98d384620f4cc92bb02cf111cb72d60df7/artiq/master/worker_impl.py#L161

I tested adding a `if` statement so the above line is run only if `file` is in the experiment subdirectory of the repository, and the total run time is reduced to ~seconds. This indicates that creating the processes is not the bottleneck at least for our setup. If I put the condition after this line, the total run time is not much reduced, so the bottle neck is really the line of code above.

@sbourdeauducq as you said, adding a check on `import artiq` would probably solve this problem. It seems to me that supporting an experiment subdirectory can solve this problem in a backward compatible way though.

**Comment by pca006132** [comment]
> It seems that nearly all the time is spent importing the modules
> 
> https://github.com/m-labs/artiq/blob/35d21c98d384620f4cc92bb02cf111cb72d60df7/artiq/master/worker_impl.py#L161
> 
> I tested adding a `if` statement so the above line is run only if `file` is in the experiment subdirectory of the repository, and the total run time is reduced to ~seconds. This indicates that creating the processes is not the bottleneck at least for our setup. If I put the condition after this line, the total run time is not much reduced, so the bottle neck is really the line of code above.

Just wondering, are the Python files scripts (that does some non-trivial things) or libraries? If they are scripts, do they have
```python
if __name__ == "__main__":
    # body
    pass
```
to prevent the code from being executed when the module is imported?

**Comment by dnadlinger** [comment]
We have many experiments here that don't `from artiq import *`, as ndscan has a wrapper (`from ndscan.experiment import *`) for the (from artiq.experiment import *` convenience helper.
