### ISSUE TITLE
Reduce import of spurious dependencies/modules

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#181]
With the new compiler, ``from artiq.protocols import pyon`` results in a lot of unnecessary modules (regex, levenshtein, ...) being pulled in from the compiler through ``artiq.language``. There are many cases where one would use pyon (or another ARTIQ library) without needing the compiler: controllers, GUI...

Loading those modules anyway unnecessarily increases memory consumption and dependency hell.

**Comment by whitequark** [comment]
Is there any convenient way to see what modules are loaded?

**Comment by sbourdeauducq** [comment]
```
>>> import sys
>>> a = set(sys.modules.keys())
>>> from artiq.protocols import pyon
>>> b = set(sys.modules.keys())
>>> b - a
```

**Comment by whitequark** [comment]
Note that this does nothing to alleviate "dependency hell", although it does slightly reduce memory consumption and much more importantly startup times.

**Comment by sbourdeauducq** [comment]
What I mean with alleviate dependency hell is things like: if you install ARTIQ manually to work on a specific part of it on a new machine, you don't have to install every dependency or touch conda.
