### ISSUE TITLE
sequence error with strictly increasing timestamps

### ISSUE THREAD

**Issue by fanmingyu212** [m-labs/artiq#1829]
# Bug Report

## One-Line Summary

Sequence error with strictly increasing RTIO timestamps.

### Steps to Reproduce

The following experiment produces a sequence error on channel 15 (corresponding to `ttl15`) on a Kasli 2.0 system.

```python
from artiq.experiment import *


class TestSequenceError(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        ttl_out_names = [f"ttl{kk}" for kk in [4, 5, 6, 7, 12, 13, 14, 15]]  # TTL output channels
        self.ttl_out_chs = []
        for channel in ttl_out_names:
            self.ttl_out_chs.append(self.get_device(channel))

    @kernel
    def run(self):
        self.core.reset()
        self.core.break_realtime()
        delay_mu(1000000)  # a
        self.ttl_out_chs[0].on()  # b

        for ttl in self.ttl_out_chs:
            self.core.break_realtime()
            ttl.off()
```

Removing either the line commented with "a" or the line commented with "b" eliminates the sequence error.

### Expected Behavior

No error.

### Actual (undesired) Behavior

Sequence error notification in the dashboard log, and `[  5210.218209s] ERROR(runtime::rtio_mgt): RTIO sequence error involving channel 15` in the core device log.

### Your System (omit irrelevant parts)

* Operating System: Windows 10
* ARTIQ version: Latest master (3f812c4c).
* Version of the gateware and runtime loaded in the core device: `7.7926.3f812c4c.beta;ucsb`
* If using Conda, output of `conda list` (please submit as a file attachment, as this tends to be long)
* Hardware involved: Kasli 2.0, DIO boards.

**Comment by sbourdeauducq** [comment]
``self.core.break_realtime()`` won't increase the time cursor position if it's already after (RTIO counter + margin). Since you added the large delay before, it's likely the RTIO counter hasn't caught up and all your ``ttl.off()``, as well as ``self.ttl_out_chs[0].on()``, are at the same time. Their timestamps would be equal and not strictly increasing. You can confirm that with the RTIO analyzer.

How did this code come about?

**Comment by fanmingyu212** [comment]
@sbourdeauducq thank you for the quick response! I forgot that `break_realtime` won't advance the timestamp if there is already enough slack.

This code was a minimal working example of an more complicated experiment (initialize the states of all DDSes and TTLs). Therefore the code looks strange and does not do anything useful.
