### ISSUE TITLE
Master quits after ~1 hr without interaction

### ISSUE THREAD

**Issue by justboh** [m-labs/artiq#184]
I will start the master pc and GUI at the start of the day.  Then I leave it alone for ~1-4 hours typically.  I don't notice the GUI close, but when I come back to use the GUI again, the master and GUI have quit and I have to restart them.

Sorry I can't provide more details.

**Comment by sbourdeauducq** [comment]
Any error log on the terminal where the master was running? Did you have a master log file and what are its last entries? Can you reproduce the crash (I've run the master for days here without problem) or was it a one-off issue?

**Comment by sbourdeauducq** [comment]
And were you running something in particular? It also seems surprising that both the master and GUI quit at the same time. Are you certain your computer was not simply rebooted?

**Comment by sbourdeauducq** [comment]
Without more details, we cannot do anything about this. If the problem occurs again, please pay attention to what exactly happened and submit a useful report.
