### ISSUE TITLE
Fastino read register method has rtio_output without mandatory argument "data"

### ISSUE THREAD

**Issue by marmeladapk** [m-labs/artiq#1842]
# Bug Report

## One-Line Summary

Fastino read register method has rtio_output without mandatory argument "data".

## Issue Details

```
<artiq>/coredevice/fastino.py:81:20-81:48: error: mandatory argument 'data' is not passed
        rtio_output(self.channel | addr | 0x80)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
<synthesized>:1:1-1:43: note: the called function is of type [ffi 'rtio_output'](target:numpy.int32, data:numpy.int32)->NoneType
`<function rtio_output at 0x7f2156b290d0>`
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Your System (omit irrelevant parts)

* ARTIQ version: master, dd3279e

**Comment by jordens** [comment]
https://github.com/m-labs/artiq/blob/dd3279e50622b5ceb1c24b4d1891f442cc0acce3/artiq/coredevice/fastino.py#L76
https://github.com/quartiq/fastino/issues/2

The entire readback functionality has never been tested and is unlikely to work.
