### ISSUE TITLE
support PCA9547 (Kasli-SoC assembly option) in i2c.py

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#1857]
Suggestion: expose the I2C switch functions from the runtime to the kernels, and use them in i2c.py instead of reimplementing them as is currently done. The artiq-zynq runtime already supports PCA9547/PCA9548 autodetection.
Needs support in DRTIO aux as well.

**Comment by Spaqin** [comment]
Should it encompass only PCA954X series of i2c switches, or ``TCA6424A`` too, replacing all the i2c switch classes with just one generic one? Autodetect would be probably limited to PCAs on Kasli and Kasli-SoC only as well, since only they have a i2c reset pin - so should the type be overrideable?

**Comment by sbourdeauducq** [comment]
TCA6424A is not a I2C switch and not relevant here.
