### ISSUE TITLE
Qt fails to properly lay out log when long words are present

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#187]
This can be demonstrated by the following code:
```python
import logging

from artiq import *


logger = logging.getLogger("qtfail")


class QtFail(EnvExperiment):
    def build(self):
        pass

    def run(self):
        logger.warning("_".join(str(i) for i in range(200)))
```

Here is the result. Note that WARNING, the source and the time are also cut.
![qtfail](https://cloud.githubusercontent.com/assets/720864/11612730/515db44c-9c40-11e5-804c-d4498e67411d.png)

**Comment by sbourdeauducq** [comment]
I just saw the columns break again, after your patch. (Qt4 anaconda)

**Comment by whitequark** [comment]
That one does look like a layout bug, yes.

**Comment by jboulder** [comment]
Column break bug with the latest conda version.

![columnbreak](https://cloud.githubusercontent.com/assets/5688774/12369292/fa65ba2c-bbb1-11e5-82cb-fbb2ee4b8ad8.png)

**Comment by whitequark** [comment]
@jboulder can you try the new conda package?

**Comment by sbourdeauducq** [comment]
:+1: Works here. We'll probably want to get Qt properly fixed and remove all those workarounds at some point...

**Comment by sbourdeauducq** [comment]
Columns are still breaking.
![colbreak](https://cloud.githubusercontent.com/assets/720864/12627519/957c43ec-c53e-11e5-8a13-75c225ddd7d8.png)
