### ISSUE TITLE
I2C bus abstraction

### ISSUE THREAD

**Issue by kaolpr** [m-labs/artiq#1877]
# ARTIQ Feature Request

## Problem this request addresses

At ELHEP (@gkasprow team) we're working on support for [EFC - EEM FMC Carrier](https://github.com/sinara-hw/EEM_FMC_Carrier). There are some I2C devices that will be controlled from EFC FPGA. 

It would be nice to use I2C drivers (coredevices) developed for ARTIQ. However, they currently support only syscall based operation defined in `coredevice/i2c.py`.

## Describe the solution you'd like

I'd like to propose creating abstraction of the I2C bus. We could define an I2C bus controller base class that would define an interface for implementation. For compatibility and ease of adoption currently available I2C functions can be used as interface definition.

Current I2C implementation can be than wrapped into sth like SystemBusController that would have one or more instances (depending on number of I2C buses or in other words max value of busno-1). In `device_db` file we would use I2C controller instance instead of busno.

## Additional context

If such approach gains support I can implement that and submit PR.

**Comment by sbourdeauducq** [comment]
Please submit a PR or more details.
Note that coredevice/i2c is only for non-realtime I2C commands, independently of RTIO. Not sure if this is what you want.
