### ISSUE TITLE
Missing module for afws_client

### ISSUE THREAD

**Issue by steine01** [m-labs/artiq#1949]
# Bug Report

## One-Line Summary

The command `afws_client` does not run, because the module `tqdm` is missing.

### Steps to Reproduce

1. Follow the installation instructions for ARTIQ 7 according to https://m-labs.hk/artiq/manual/installing.html until https://m-labs.hk/artiq/manual/installing.html#obtaining-the-board-binaries
2. Activate the conda environment
3. Execute `afws_client`, `afws_client -h` or `afws_client [user] build [variant] [location]` in the anaconda environment. (With the appropriate user id and so on)

### Expected Behavior

A help message appears or the binaries are built and downloaded.

### Actual (undesired) Behavior

This error appears (it is the same for all three commands): 

```
(artiq-7-1) PS C:\Users\ybion443> afws_client -h
Traceback (most recent call last):
  File "C:\Users\ybion443\.conda\envs\artiq-7-1\Scripts\afws_client-script.py", line 5, in <module>
    from artiq.frontend.afws_client import main
  File "C:\Users\ybion443\.conda\envs\artiq-7-1\lib\site-packages\artiq\frontend\afws_client.py", line 13, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

Manually installing the package (`conda install tqdm`) resolves the error.

### Your System (omit irrelevant parts)

* Operating System: Windows 10
* ARTIQ version: ARTIQ v7.8111.59dfb9e
* Version of the gateware and runtime loaded in the core device: none yet
* Hardware involved: none
* Conda channels:
  - https://conda.m-labs.hk/artiq
  - defaults
  - quartiq
  - m-labs
  - conda-forge

[conda_list.txt](https://github.com/m-labs/artiq/files/9291791/conda_list.txt)

**Comment by sbourdeauducq** [comment]
Thanks - should be fixed in https://git.m-labs.hk/M-Labs/artiq-extrapkg/commit/3d41ed4fef9fd3c49534c9010688c47be195b4d9
