### ISSUE TITLE
logging strings in rtio_clocking.rs are wrong 

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#1983]
In `setup_si5324_as_synthesizer()` the following text string `using 10MHz reference to make 125MHz RTIO clock with PLL` is incorrectly logged when the parameter is set to `Ext0_Synth0_125to125` and `Ext0_Synth0_100to125`. 

https://github.com/m-labs/artiq/blob/69cddc6b862a85823d28e6339d3a94415e21eee9/artiq/firmware/runtime/rtio_clocking.rs#L137

**Comment by dnadlinger** [comment]
Fixed in 261dc6b9330e831720bcb0de116fab4ece2c8bf4.
