### ISSUE TITLE
LLVM IR parsing error with msys2

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#2050]
https://forum.m-labs.hk/d/546-llvm-ir-parsing-error-when-running-dma-example-from-artiq-manual

**Comment by thomasfire** [comment]
I think we can eventually upgrade to the LLVM- 4, since llvmlite 40 was released, and MSYS2 finally has fixed versions of LLVM 14 and 15

**Comment by thomasfire** [comment]
Closed by https://github.com/msys2/MINGW-packages/pull/17370
