### ISSUE TITLE
Performance regression in DMA playback since introduction of DDMA

### ISSUE THREAD

**Issue by SquidDev** [m-labs/artiq#2078]
# Bug Report

## One-Line Summary

Since the introduction of DDMA in e9a153b985d1c703338ad49bb0ac986ade29d21a, playing back a DMA sequence will consume all slack, even when the sequence is not using DDMA.

### Steps to Reproduce

The following experiment records a DMA sequence (which includes 128 RTIO events, 400ns apart), and attempts to play it back twice. It does not use DRTIO or DDMA (the fastino is attached to the master).

<details><summary><code>experiment.py</code></summary>

```python
import math

from artiq.coredevice.core import Core
from artiq.coredevice.dma import CoreDMA
from artiq.coredevice.fastino import Fastino
from artiq.language import EnvExperiment, delay_mu, kernel


def generate_voltages(samples: int):
    voltages = []
    for i in range(samples):
        voltages.append(math.sin((i / samples) * math.pi * 2))
    return voltages


class FastinoDma(EnvExperiment):
    def build(self):
        self.trace_name = "test_rtio"
        self.core: Core = self.get_device("core")
        self.core_dma: CoreDMA = self.get_device("core_dma")
        self.fastino: Fastino = self.get_device("fast0")

    def prepare(self):
        self.voltages_mu = [
            self.fastino.voltage_to_mu(v) for v in generate_voltages(128)
        ]

    @kernel
    def record_many(self):
        with self.core_dma.record(self.trace_name):
            for voltage in self.voltages_mu:
                self.fastino.set_dac_mu(0, voltage)
                delay_mu(400)

    @kernel
    def playback(self):
        handle = self.core_dma.get_handle(self.trace_name)
        self.core.break_realtime()

        self.core_dma.playback_handle(handle)
        self.core_dma.playback_handle(handle)

    @kernel
    def run(self):
        self.core.reset()
        self.record_many()
        self.core.break_realtime()
        self.playback()
```

</details>

1. Set up a system with a master and satellite, attaching the fastino `fast0` to the master.
1. Flash firmware prior to e9a153b985d1c703338ad49bb0ac986ade29d21a to the system and run the above experiment. It should complete without underflowing.
2. Repeat with the latest ARTIQ version. It will consistently underflow.

### Expected Behavior

When not using DDMA, the performance of DMA sequences should be the same as before.

### Actual (undesired) Behavior

The experiment consistently underflows

<details><summary>Traceback</summary>

```
2023-04-13 13:06:36,413 ERROR:root:Terminating with exception (RTIOUnderflow: RTIO underflow at channel 0xc0000:fast0, 158398097040 mu)
Core Device Traceback:
Traceback (most recent call first):
  File "ksupport/lib.rs", line 419, column 18, in (Rust function)
    <unknown>
                     ^
  File "experiment.py", line 53, in artiq_worker_repro.FastinoDma.run(..., ...) (RA=+0x2a4)
    self.playback()
  File "experiment.py", line 43, in ... artiq_worker_repro.FastinoDma.playback<artiq_worker_repro.FastinoDma>(...) (RA=+0x454)
    self.core_dma.playback_handle(handle)
  File "<artiq>/coredevice/dma.py", line 123, in ?? (RA=+0x560)
    dma_playback(now_mu(), ptr)
artiq.coredevice.exceptions.RTIOUnderflow(0): RTIO underflow at channel 0xc0000:fast0, 158398097040 mu

End of Core Device Traceback
Traceback (most recent call last):
  File "venv/lib/python3.8/site-packages/artiq/master/worker_impl.py", line 574, in main
    exp_inst.run()
  File "venv/lib/python3.8/site-packages/artiq/language/core.py", line 54, in run_on_core
    return getattr(self, arg).run(run_on_core, ((self,) + k_args), k_kwargs)
  File "venv/lib/python3.8/site-packages/artiq/coredevice/core.py", line 162, in run
    self._run_compiled(kernel_library, embedding_map, symbolizer, demangler, function.__name__)
  File "venv/lib/python3.8/site-packages/artiq/coredevice/core.py", line 143, in _run_compiled
    self._run_compiled_impl(kernel_library, embedding_map, symbolizer, demangler)
  File "venv/lib/python3.8/site-packages/artiq/coredevice/core.py", line 152, in _run_compiled_impl
    self.comm.serve(embedding_map, symbolizer, demangler)
  File "venv/lib/python3.8/site-packages/artiq/coredevice/comm_kernel.py", line 741, in serve
    self._serve_exception(embedding_map, symbolizer, demangler)
  File "venv/lib/python3.8/site-packages/artiq/coredevice/comm_kernel.py", line 723, in _serve_exception
    raise python_exn
artiq.coredevice.exceptions.RTIOUnderflow: RTIO underflow at channel 0xc0000:fast0, 158398097040 mu
```

</details>

### Your System

* Operating System: Linux (Ubuntu 22.04)
* ARTIQ (including gateware and runtime) version: 97161a3df24a749ef95f42c32eca57845c064bc5
* Hardware involved:
  Tested with the following setups:
  - Kasli 2.0 master, Kasli-SoC satellite, Fastino attached to the master.
  - Kasli-SoC master (using [this version of artiq-zynq](https://git.m-labs.hk/M-Labs/artiq-zynq/src/commit/bf50a44f763f65cb1737a30df0e0eda9d747b96b)), Kasli 2.0 satellite, Fastino attached to the master.

**Comment by Spaqin** [comment]
From this experiment I think I know why it would do that - at the end of local playback it's still trying to get remote results even if there's no DDMA involved - which takes some time, underflowing on second playback. I think we can pass ``enable_ddma`` to the playback function too to cut down unnecessary kernel-comms communication.

Does it also happen on Kasli-SoC?

**Comment by SquidDev** [comment]
> Does it also happen on Kasli-SoC?

Yes, though it may require more calls to playback_handle. The original experiment was calling `playback_handle` in a loop, and afraid I've only tested the simpler version on a Kasli 2.0.

> I think we can pass `enable_ddma` to the playback function too to cut down unnecessary kernel-comms communication.

I was a little surprised to see how many cross-CPU messages were sent when playing a DDMA sequence. I think I was expecting playback to be handled more on the gateware side than by firwmare. I'm sure there's a valid reason, just curious about the tradeoffs - is there a design doc for DDMA anywhere?

**Comment by SquidDev** [comment]
Oh yes, definitely agreed that handling recording and sending traces on the firmware side makes a lot of sense.

I think my main worry here is with playing sequences back. Because one of the kernel-comms round trips happens when the DMA sequence has played out, calls to `dma_playback` return with large amounts of negative slack, which definitely limits the cases where DDMA can be used.

That said, agreed that doing things on the firmware side is easier, and I'm definitely not familiar enough with the gateware side of things to have much of an informed opinion here :).
