### ISSUE TITLE
cleanup anaconda package installs

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#21]
AFAICT the various packages that are installed from anaconda can be combined into one:
https://github.com/m-labs/artiq/blob/master/.travis/get-anaconda.sh#L8
https://github.com/m-labs/artiq/blob/master/.travis.yml#L16
https://github.com/m-labs/artiq/blob/master/.travis.yml#L20

**Comment by fallen** [comment]
You mean combine those installations in a one liner?
like : `conda install jinja2 migen cython pip coverage binstar`

**Comment by jordens** [comment]
Yes Combine. Originally I had all conda packages installed at https://github.com/m-labs/artiq/blob/master/.travis/get-anaconda.sh#L10 with the arguments from https://github.com/m-labs/artiq/blob/master/.travis.yml#L16
But you can move them to wherever you like.

**Comment by fallen** [comment]
Done, thanks :)

**Comment by fallen** [comment]
In fact, installing conda-build and jinja2 is mandatory to take place in the "root" environment and cannot be done in the virtual env. I will add those in get-anaconda.sh.

**Comment by jordens** [comment]
ack
