### ISSUE TITLE
core device should be capable of sending 1MB in one RPC

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#215]
See _PayloadCoreSend1MB in speed_benchmark.py. Fails with this log since the new comms code:
```
session.c: write overrun while trying to write 4 bytes (2 remaining)
Failed to send RPC request (service 2, tag Oli:n)
```

**Comment by sbourdeauducq** [comment]
Also, we should probably unittest this.

**Comment by whitequark** [comment]
Do you suggest just increasing buffer size, or something more clever? It looks like the coredevice code won't yield to the latter without some serious refactoring.

**Comment by sbourdeauducq** [comment]
Then increase buffer size.

**Comment by sbourdeauducq** [comment]
But at some point the comms code will have to handle 10MB chunks of data to load into core device storage...

**Comment by whitequark** [comment]
This will be hard to implement. The crux of the issue is that the entire `session.c` has to be rewritten in using coroutines. C is not a language suited for doing this without allocation, quite ironically if you consider how it's supposed to be good for embedded work...

**Comment by whitequark** [comment]
`receive_rpc_value` and `send_rpc_value` are the worst offenders because they are recursive, potentially with unlimited depth.
