### ISSUE TITLE
Kick off buildbot on github push

### ISSUE THREAD

**Issue by whitequark** [m-labs/artiq#216]

**Comment by whitequark** [comment]
@sbourdeauducq I can't do this, since I don't have admin access to m-labs repositories. Hypothetically it should be enough to point a custom hook to `http://101.78.236.68/buildbot/change_hook/github?project=PROJECT` where `PROJECT` is `artiq`, `misoc`, `migen`.

**Comment by sbourdeauducq** [comment]
The server seems to return HTTP 500 to github.

**Comment by whitequark** [comment]
Hm:
```
2016-01-08 11:25:26+0800 [HTTPChannel,13,] Attempting to load module buildbot.status.web.hooks.github
2016-01-08 11:25:26+0800 [HTTPChannel,13,] processing changes from web hook
        Traceback (most recent call last):
        Failure: exceptions.KeyError: 'payload'
```

**Comment by sbourdeauducq** [comment]
Hmm maybe it works for actual pushes...

**Comment by whitequark** [comment]
Yeah, I recall something like that. Try it.

**Comment by sbourdeauducq** [comment]
Didn't work, still 500.

**Comment by sbourdeauducq** [comment]
Should I use json content type or x-www-form-urlencoded?

**Comment by whitequark** [comment]
`application/x-www-form-urlencoded`.

**Comment by sbourdeauducq** [comment]
OK that works now, can you disable auto build for non-master branches?

**Comment by whitequark** [comment]
Done
