### ISSUE TITLE
AD9914 output frequency is half of the set value

### ISSUE THREAD

**Issue by dleibrandt** [m-labs/artiq#217]
I'm running artiq on kc705 with qc2 hardware.  I have a couple AD9914s, which are clocked at 3.5 GHz.  When I set the output frequency as follows

    self.dds11.init()
    delay(10*ms)
    self.dds11.set(200*MHz, amplitude=1.00)

, the actual output frequency is 100 MHz.

**Comment by sbourdeauducq** [comment]
Have you set the correct sysclk in device_db?

**Comment by dleibrandt** [comment]
Yes, here is the relevant entry in the device_db.  I've also checked on a spectrum analyzer that the actual clock going into the DDSs is 3.5 GHz.

    "dds11": {
        "type": "local",
        "module": "artiq.coredevice.dds",
        "class": "AD9914",
        "arguments": {"sysclk": 3.5e9, "channel": 1}
    },

**Comment by sbourdeauducq** [comment]
Did you run ``dds11.init()`` at least once after power-up (e.g. at the beginning of your kernel, in another kernel, via the startup kernel)?

**Comment by sbourdeauducq** [comment]
Does this happen with all DDS cards or only one?

**Comment by dleibrandt** [comment]
@whitequark The root cause of this problem is your compiler breaks when computing the frequency tuning word. This is easily reproduced by running ``print(2**32*400e6/3.5e9)``: prints 245426702.514285 on the device, 490853405.25714284 in CPython.

**Comment by whitequark** [comment]
@dleibrandt Yes, that's actually expected, since all integers are by default 32-bit. (Arguably it was a bug in the old compiler that by accident provided correct result.) This prints the correct value:

    print(int(2, width=64)**32*400e6/3.5e9)

**Comment by sbourdeauducq** [comment]
It was not an accident, but requiring explicit size on all integers that require more than 32 bits is OK.

**Comment by sbourdeauducq** [comment]
a9cf892 should fix the problem. @dleibrandt can you test?

**Comment by whitequark** [comment]
@sbourdeauducq I'm aware that it worked because constant folding happened before inference of integer size. I still consider that a bug from language design perspective, because otherwise algebraically equivalent transformations would break code relying on that.

**Comment by dleibrandt** [comment]
Yes, I just tested and the DDSs now output the correct frequency.
