### ISSUE TITLE
dashboard dataset float64 bug

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#2179]
https://github.com/m-labs/artiq/issues/2174#issuecomment-1704391101

**Comment by fsagbuya** [comment]
> @fsagbuya @SimonRenblad What is the status of this?

Was fixed already in #2194.

cc: @SimonRenblad

**Comment by SimonRenblad** [comment]
Unable to reproduce the bug after #2194. If a reproducible case is provided after this patch, let's reopen the issue.
