### ISSUE TITLE
Core device storage

### ISSUE THREAD

**Issue by whitequark** [m-labs/artiq#219]
We need persistent storage in RAM of coredevice. Lists of integers up to 10M should be stored. Storage and retrieval is performed using string keys. Retrieval should not copy lists.

**Comment by whitequark** [comment]
API: `self.core.get_cache`/`self.core.set_cache`. On error return empty list. If a list was returned by `get_cache` then `set_cache` will refuse to set it until the current experiment terminates, to maintain memory safety.

**Comment by whitequark** [comment]
@sbourdeauducq Question: where should we stick the heap for the cache and how large should it be?

**Comment by whitequark** [comment]
Nevermind "where", lwip does not give much choice in this regard. But "how large" still stands.

**Comment by jboulder** [comment]
Please add to documentation.

**Comment by jboulder** [comment]
Would also be good to benchmark performance. 
* from Master PC to DRAM
* from DRAM to Core Device

**Comment by whitequark** [comment]
There is no DRAM to Core Device step: any data stored in the cache is used directly when you extract it.

**Comment by whitequark** [comment]
Documentation added.
