### ISSUE TITLE
rewrite/replace the pyqtgraph docking system

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#220]
There are a number of problems with it:
* the look-and-feel is mediocre. Double-click to detach tab is not very intuitive. Order of tabs cannot be changed. Compare with the tabs in Google Chrome or Sublime Text.
* it is buggy:
  * https://github.com/m-labs/artiq/commit/2199eadb9962811f19f0c78891c62d7c5a246fe2#diff-523ba5dbaffb3068cb299aaa89ab0456R215
  * it reproducibly explodes and makes the application unusable if the saved state references a non-existent dock
  * it randomly corrupts the dock save/restore state (#104, #158)
  * setting the initial size of a floating dock does not work (workaround is to set minimum size)
  * dropping a dock on top of an embedded window (ARTIQ applet) does not work
* pyqtgraph is generally hacky, e.g. it meddles with the PyQt namespaces (https://github.com/m-labs/pyqtgraph/blob/develop/pyqtgraph/Qt.py#L180). Removing the main GUI's dependency on pyqtgraph would contain the mess to those applets that use it.

**Comment by whitequark** [comment]
https://doc.qt.io/qt-4.8/qdockwidget.html ?

**Comment by sbourdeauducq** [comment]
The pyqtgraph dock says "Docking system that replaces/complements Qt’s dock system to allow more complex (and more predictable) docking arrangements". Not sure how much of that is true/actually provides something useful.

**Comment by sbourdeauducq** [comment]
When we have a decent docking system, we should also bring the corresponding experiment dock into focus when it is already open and the user double-clicks on the experiment in the explorer.

**Comment by sbourdeauducq** [comment]
https://woboq.com/blog/qdockwidget-changes-in-56.html seems to have most of the features of pyqtgraph docks, plus a few extras (e.g. tab reordering). It will be part of Qt 5.6 (release due March 3rd) and the company developing it offers commercial support.

**Comment by sbourdeauducq** [comment]
Replaced with QDockWidget.
