### ISSUE TITLE
package pyqt5

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#221]
Needed for window embedding features, and for fixing bugs inside Qt.

Anaconda only offers pyqt4 in the main repository; but there is this: http://stackoverflow.com/questions/25468397/using-anaconda-python-with-pyqt5

**Comment by whitequark** [comment]
Done.

**Comment by sbourdeauducq** [comment]
As discussed:
 * use host libxcb library (keyboard does not work at all on Linux)
 * qt4 + qt5 coexistence is needed (otherwise conflicts with many anaconda packages)

**Comment by whitequark** [comment]
This is now packaged, uses host libxkbcommon and coexists with Qt4.

**Comment by sbourdeauducq** [comment]
I tested it (with the single-command installation in the doc) on Linux on fresh Anaconda and on fresh Miniconda (since both are mentioned in the doc, we must make sure that it works with both). Have you done the same on Windows?

**Comment by whitequark** [comment]
I verified that it works in a fresh 64-bit Anaconda and Miniconda. However, only in Anaconda, the following message is displayed when closing artiq_gui:
![1903](https://cloud.githubusercontent.com/assets/54771/13219160/2ad35738-d966-11e5-8555-00faf95c1376.png)

**Comment by whitequark** [comment]
Ah nevermind, looks like I had a stale `artiq_gui.pyon`.
