### ISSUE TITLE
vivado fails to find libtinfo.so.5 with recent nixpkgs

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#2274]
On nixpkgs master
Good: 545857e74921a41af587931bd80dfed5541c3cbf
Broken: 3919f9de265b354aa9dc92316dce8ad75b89140a

**Comment by fsagbuya** [comment]
> Still need to find a solution for the vivado-env shell.

We can do a `nix flake update` and `vivado-env` shell can fetch the latest patch to fix it, and apply the `LD_LIBRARY_PATH` fix in artiq-main and beta.
