### ISSUE TITLE
rid scalability/uniqueness/sortability

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#234]
Scanning the entire output data filesystem does not scale. There are usually millions of files there (I checked).
If run-ids do not need to be sortable, they don't need to be monotonically increasing and they could be `uuids`. But sortability is nice for browsing the filesystem, so let's keep it.
Can't we just put the last/current run id into e.g. the dataset db?

https://github.com/m-labs/artiq/blob/master/artiq/master/worker_db.py#L90

**Comment by sbourdeauducq** [comment]
I would use a dedicated file for that and rewrite it at each RID assignment.

**Comment by jordens** [comment]
You will want to keep the current code to a) reconstruct that pointer file in case it gets lost and b) tarnsition old repos.
