### ISSUE TITLE
add floating point plotting support to GtkWave

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#242]
The core device analyzer outputs RTIO slack as a 64-bit float expressed in seconds. It is nice to plot it with an analog view in GtkWave, but the latter only supports integer values there, resulting in a unwanted logarithmic-ish scale.

**Comment by sbourdeauducq** [comment]
Example VCD file produced by the analyzer.
[foo.zip](https://github.com/m-labs/artiq/files/101701/foo.zip)

**Comment by jordens** [comment]
For this specific case, why not just use 64 bit integer multiples of 1 ns? The useful granularity of the slack is on the order of 10 ns (cpu clock) and will be for the foreseeable future.

For frequencies and voltages the story might be different.

**Comment by sbourdeauducq** [comment]
That's inconsistent with the way other numbers (e.g. DDS frequencies) are represented, plus this will be annoying when we have a board with a CPU frequency not a multiple of 1ns.

**Comment by jordens** [comment]
Then this bug is not just about the slack.
And anyway: slack is not a precision quantity. It's useful resolution is more like 10 ns independent of the cpu speed.

**Comment by dhslichter** [comment]
I think having slack in increments of machine units as a 64-bit integer would work, no?  "Logarithmic" scale is not that bad, this is a coarse debugging tool really.

**Comment by sbourdeauducq** [comment]
I'd like to keep everything consistent and user-interpretable in the VCD: SI units and floating point.

**Comment by sbourdeauducq** [comment]
Note that GtkWave can display floating point numeric values just fine, it just cannot plot them correctly.

**Comment by dhslichter** [comment]
I am fine with logarithmic scale of slack for the plotting, since for my purposes the only times it will matter is when it gets small, and then I can look at the actual floating point value.  Seems like this would be more effort to fix properly than it's worth.

**Comment by sbourdeauducq** [comment]
@jboulder Done. We now get the expected linear rise in RTIO slack.
![gtkfloat](https://cloud.githubusercontent.com/assets/720864/14168394/baed1992-f754-11e5-88cc-556ca285ad3c.png)

**Comment by sbourdeauducq** [comment]
Patch posted to the gtkwave-users ML.

**Comment by sbourdeauducq** [comment]
(I do not have a link for it because Sourceforge being what it is, there seems to be some delay before the archive pages are updated)

**Comment by sbourdeauducq** [comment]
[gtkwave_floating_point_plotting.diff.zip](https://github.com/m-labs/artiq/files/197171/gtkwave_floating_point_plotting.diff.zip)

**Comment by jboulder** [comment]
Thank you. -Joe
