### ISSUE TITLE
Qt fails to use monospace font for log on Windows

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#249]
The second column should use monospace font so that compiler diagnostics etc. are properly displayed.

Windows:
![colbreak](https://cloud.githubusercontent.com/assets/720864/12640427/116fe7cc-c5aa-11e5-8cd2-33740e2855ac.png)

Linux:
![logok](https://cloud.githubusercontent.com/assets/720864/12640475/64feb274-c5aa-11e5-95eb-360816d961bf.png)

**Comment by whitequark** [comment]
A more appropriate title is "I fail to use the support for selecting a monospace font appropriate for the platform that Qt explicitly provides by `QFont::Monospace`, and instead use some `setFamily` call".

**Comment by sbourdeauducq** [comment]
Doesn't seem to be that simple (http://stackoverflow.com/questions/1468022/how-to-specify-monospace-fonts-for-cross-platform-qt-applications) but we can try that.

**Comment by whitequark** [comment]
Ah yes, it's `QFontDatabase` on Qt5.

**Comment by sbourdeauducq** [comment]
Done in 1d92c08.

**Comment by sbourdeauducq** [comment]
Tested OK on Windows.
