### ISSUE TITLE
ppp runtime overflows storage area

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#250]
Needs a bit coordination and requires user action.
https://github.com/m-labs/artiq/tree/increase-runtime-size

**Comment by sbourdeauducq** [comment]
Do you want to merge this and tell people to reflash and reconfigure?

**Comment by jordens** [comment]
That would be the plan. Just allowing time for comments. Is 0x60000 sufficiently large for the runtime or should we move it further out?
