### ISSUE TITLE
default localhost binding causes "address already in use" error

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#253]
Happens on some systems only.

**Comment by jordens** [comment]
https://github.com/python/asyncio/issues/315

**Comment by sbourdeauducq** [comment]
http://bugs.python.org/issue26338

**Comment by sbourdeauducq** [comment]
Remove --no-localhost-bind from the example device_db after this is done
introduced here: c0bbd99bfa33a11557050ba021ad50fc25fdbaed

**Comment by sbourdeauducq** [comment]
Committed to CPython
https://hg.python.org/cpython/rev/bbc8cb86f05e
