### ISSUE TITLE
DNS entry for the buildserver

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#259]
The buildserver should get a human readable entry in DNS.

**Comment by whitequark** [comment]
Yes. There is a static IP that should be assigned to the server, but it's unclear whether the ISP has done that yet or not. This should be sorted out (it should've been sorted out months ago...)

**Comment by jordens** [comment]
Even if it is a dynamic IP currently, the best estimate is that is stable enough to give it a NS record.

**Comment by whitequark** [comment]
I think the issue was that the `m-labs.hk` DNS was very annoying to change because of some organizational issues. I can put it under `whitequark.org` DNS which can be changed with one click, though.

**Comment by jordens** [comment]
That would be fine by me.

**Comment by whitequark** [comment]
http://m-labs-buildserver.whitequark.org
