### ISSUE TITLE
compiler does not need to know about host function arguments when RPCing them

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#260]
Unpacking RPC argument is the job of CPython. This fixes the problem of ``*args`` and ``**kwargs`` on the host side making functions non-RPCable.

This should make this workaround unneccessary:
https://github.com/m-labs/artiq/commit/74a75841f6758b075a6e0ab0c8e2073205b00953#diff-cd7c8bf089e236086103cf4897c4794eR271

**Comment by whitequark** [comment]
Changed to 1.0 because that's the only way #366 can be fixed.

**Comment by sbourdeauducq** [comment]
Another (user relevant) situation where this will cause trouble is when calling methods of ``artiq.protocols.pc_rpc.Client`` from the core device (chained RPC).
