### ISSUE TITLE
support cancelling all experiments from a pipeline

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#262]
I propose doing this by right clicking on a experiment in the scheduler, and having a "request graceful termination of all experiments in the same pipeline as the one selected" option. A short text in the menu could be "Gracefully terminate all in pipeline".

**Comment by jordens** [comment]
Wouldn't this be more appropriately placed in the context menu in the scheduler? Terminating a complete pipeline only makes sense if there is something in that pipeline. That provides a nice context.

**Comment by sbourdeauducq** [comment]
Yes, I was talking about the context menu of the scheduler here: "propose doing this by right clicking on a experiment **in the scheduler**"

**Comment by jordens** [comment]
Ack. Nevermind then.
