### ISSUE TITLE
QC2 hardware documentation + install instructions for CLOCK

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#264]
@dhslichter

**Comment by sbourdeauducq** [comment]
Clock install instructions are done

**Comment by sbourdeauducq** [comment]
@dhslichter Can you please review the QC2 code (it has the two backplanes now), make any changes you need and submit a patch along with docs?

**Comment by dhslichter** [comment]
qc2 code appears to be correct from inspection, will verify on bench this week.  doc patch to arrive soon.

**Comment by dhslichter** [comment]
note that SPI has not been added yet, will submit patch with appropriate SPI lines.

**Comment by sbourdeauducq** [comment]
@dhslichter Please send us that patch soon.
