### ISSUE TITLE
applet bugs on Windows

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#269]
- [x] the contents aren't displayed until you resize the dock
- [x] there are white borders on two sides of the applets
- [x] windows intermittently fail to be embedded (seems to happen only when the applets are already present at GUI startup)
- [X] restarting the applet makes the applet appear off the widget and not embedded
- [x] applets fail to exit gracefully and are killed by the GUI process

**Comment by sbourdeauducq** [comment]
Screenshot of the "white borders" (which also contain grey and blue here) on @cr1901's machine. Also note the setGeometryDp errors in the console. On Linux, the "hello world" button fills the whole window.

![borders](https://cloud.githubusercontent.com/assets/720864/13111285/3c83e84c-d585-11e5-83ff-148d19827a22.PNG)

See this:
http://stackoverflow.com/questions/32612627/embedding-a-native-window-in-qt

**Comment by sbourdeauducq** [comment]
host.py/embedded.py
[embedding.zip](https://github.com/m-labs/artiq/files/135833/embedding.zip)

**Comment by sbourdeauducq** [comment]
This is what you can get by restarting a docked applet. Could be that those issues are all related the the failing ``setGeometryDp`` ...
![ploo](https://cloud.githubusercontent.com/assets/720864/13150030/36992c32-d664-11e5-8ece-42e6b35caf86.png)

**Comment by cr1901** [comment]
I'll test on my machine and see if I can duplicate within the next 24 hours.

**Comment by Evil-Spirit** [comment]
i think it's because window can't be resized due to some reason (like WM_GETMINMAXINFO response). Ive tried to set hook(SetWindowsHookEx) on it, but something goes wrong way (i don't know why it isn't set for me). in other words, you can interrupt winproc and return other minmax info instead of app-specified for ability to resize this window. with the resizable windows i have get a good result.

**Comment by Evil-Spirit** [comment]
example (doesn't work for me)

http://paste.ofcode.org/v4qexKaVJAtpPvA22vZggv

**Comment by sbourdeauducq** [comment]
Thanks and I see how we could work around this bug. Can you modify embedded.py so that it shows the window before sending the embedding request? Qt should make the window resizable after that (at least, you can resize it manually).

On Linux we had to use this sequence of operations to work around problems:
https://github.com/m-labs/artiq/blob/92c0ede689dcd8d8393b06a86cc748428305a012/artiq/applets/simple.py#L133
but likely the sequence that works on Windows is show applet window and then embed it.

**Comment by sbourdeauducq** [comment]
28c4d8c2a7ba4f59fa3582f26879970e82004c84 makes things better (contents are shown immediately and there are no more problems with restarting), but there are still issues. The white borders are still there, Qt keeps complaining about ``setGeometryDp``, and one occasion I resized the applet window and the contents were not resized.

The applets failing to be embedded on GUI startup is a race condition in ``pipe_ipc``, I'll fix it shortly.

Are you able to reproduce the "white border" problem @Evil-Spirit ?

**Comment by Evil-Spirit** [comment]
now i see it when running embedded.py and capture it by my qt program.

**Comment by sbourdeauducq** [comment]
Correction: __some__ of the applets failing to be embedded are due to a ``pipe_ipc`` bug, which comes __in addition__ to an embedding bug. Sigh.

**Comment by Evil-Spirit** [comment]
https://bugreports.qt.io/browse/QTBUG-40320

**Comment by sbourdeauducq** [comment]
The other (non-pipeipc related) "window fails to be embedded" bug happens, reproducibly, when the applet is supposed to be embedded in a ``QDockWidget`` that is detached at application start. 

Embedding is otherwise reliable when the ``QDockWidget`` is docked into the main window when the application starts.

**Comment by sbourdeauducq** [comment]
@Evil-Spirit Yes, see my comment in the ARTIQ code: "Qt window embedding is ridiculously buggy".

**Comment by sbourdeauducq** [comment]
All "window not embedded" bugs fixed.

**Comment by sbourdeauducq** [comment]
I suspect the white borders could be vestiges of the normal title bar and window border.

**Comment by sbourdeauducq** [comment]
Applets failing to exit is a pyqtgraph bug I had fixed a while ago, but the conda package was out of date. I have rebuilt the pyqtgraph package, but when installing it, it attempts do downgrade Qt to 4.x. @whitequark please remember to fix this.

**Comment by sbourdeauducq** [comment]
All fixed.
