### ISSUE TITLE
fix compiler error message colors on Windows

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#272]
Windows consoles do not support ANSI color codes and they just clutter the output. Disabling diagnostic colors on Windows is an acceptable solution.

**Comment by jordens** [comment]
Yes. Or pull in `colorama`.

**Comment by sbourdeauducq** [comment]
NB: The problem happens when running unittests that happen to print compiler diagnostics, and I guess ``artiq_compile`` and ``artiq_run`` are also affected.
