### ISSUE TITLE
readout of HDF5 files by plotting applets

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#275]
3rd mechanism for getting data in addition to sync_struct ``Subscriber`` and the GUI pipes.

**Comment by sbourdeauducq** [comment]
Obsoleted by browser.

**Comment by jordens** [comment]
This was more for dashboard applets that want to mix old on-disk data with live data. The browser doesn't do that.

**Comment by sbourdeauducq** [comment]
The idea of this feature was to run an applet standalone on HDF5 data (just like they can be run standalone outside the dashboard, with a direct master connection). The browser supersedes this entirely.
