### ISSUE TITLE
pyserial asyncio controllers

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#279]

**Comment by sbourdeauducq** [comment]
Experimental asyncio support for pyserial is here:
https://github.com/m-labs/pyserial

The file ``aio.py`` can be used independently from the rest of pyserial. I have sent a few things to pyserial, if by next week they have not reacted to them we will host ``aio.py`` somewhere else, possibly as a different project.

**Comment by sbourdeauducq** [comment]
Time's up. https://github.com/m-labs/asyncserial

**Comment by sbourdeauducq** [comment]
Implemented in the two serial controllers (tcube/novatech), untested. I will give the tcube devices a shot. @jboulder can you test your controller for the Novatech 409b after the changes I made (in the master branch)?

asyncserial is currently not working on Windows.

**Comment by sbourdeauducq** [comment]
Tcube driver OK.

**Comment by sbourdeauducq** [comment]
Windows problems fixed.

**Comment by sbourdeauducq** [comment]
Just waiting for the novatech test.

**Comment by sbourdeauducq** [comment]
@jboulder Can you give the new novatech controller a try?

**Comment by jbqubit** [comment]
I've ordered Novatech but they've not yet arrived. Will test when they're
on hand.

**Comment by sbourdeauducq** [comment]
@jbqubit Have they arrived?

**Comment by sbourdeauducq** [comment]
Testing this is the last known issue before 2.0.

**Comment by sbourdeauducq** [comment]
Fixed and working.
