### ISSUE TITLE
run CI unittests on the KC705

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#289]
Seems needed as they are broken basically every time I run them.

**Comment by whitequark** [comment]
Done. They're still broken since either there is no loopback or there is no JTAG.

**Comment by sbourdeauducq** [comment]
I see many failing ones that are not due to JTAG.

**Comment by whitequark** [comment]
No, they are due to JTAG, because the fix is in master but was not flashed yet. Except one test that I asked you about on IRC.

**Comment by whitequark** [comment]
(I've deliberately not flashed it manually so that we have an indication of flashing by buildbot starting to work.)

**Comment by sbourdeauducq** [comment]
lda, analyzer?

**Comment by whitequark** [comment]
Ah yes those are due to the missing `--no-localhost-bind` option. Not sure if we should add that or update Python.

**Comment by sbourdeauducq** [comment]
I would monkey-patch asyncio if python version == 3.5.1. Earlier versions are not supported and later ones should be fixed (patch is committed).

**Comment by sbourdeauducq** [comment]
What about the analyzer test failing? It seems the buildbot could not connect to the analyzer port on the core device.
