### ISSUE TITLE
targets, binary packages, and their contents should be named consistently

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#290]
We have `artiq-kc705-nist_qc1` as package but the adapter is named `qc1` and the files end up in `artiq/binaries/kc705-qc1`. It should be either `nist_qc1` or `qc1` everywhere. Maybe even the `_`/`-` stuff can be made less bumpy.

**Comment by sbourdeauducq** [comment]
The defaults should be consistent as well - ``gateware.targets.kc705`` has qc1, ``artiq_flash`` has qc2.

**Comment by sbourdeauducq** [comment]
Now defaults to CLOCK everywhere since this is what we have for testing.

**Comment by jordens** [comment]
lower case probably
