### ISSUE TITLE
scroll wheel behavior in experiment editor

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#303]
* wheel: scroll the area
* shift-wheel: change spinboxes/zoom scanwidget
* ctrl-wheel: nothing on spinboxes/npoints on scanwidget

**Comment by jordens** [comment]
Other UIs (browsers, pdf readers) have ctrl-wheel for zoom. Maybe we should swap the scanwidget behavior to zoom/npoints on ctrl/shift.
