### ISSUE TITLE
run and fix as needed unittests on Windows

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#306]

**Comment by sbourdeauducq** [comment]
Includes the hardware ones (with ``ARTIQ_ROOT``).

**Comment by sbourdeauducq** [comment]
OK to skip the timing tests that involve network round-trips if they fail due to VM slowness.

**Comment by whitequark** [comment]
The problem is not VM slowness but concurrent execution. VMs are near native speed (at least network-wise; copy-on-write disks are somewhat slow), but they are easily CPU-starved.

**Comment by whitequark** [comment]
Unittests on Windows are now run by CI.
