### ISSUE TITLE
move ethernet timing constraints of kc705 to MiniSoC

### ISSUE THREAD

**Issue by enjoy-digital** [m-labs/artiq#312]
To be done when we'll figure out a reliable way to apply constraint on signals with Vivado ("dont_touch" signal attribute?)

**Comment by sbourdeauducq** [comment]
What's the current status on that?

**Comment by enjoy-digital** [comment]
There are two things:
- 1)"attribute keep of foo is true" is not recognized by Vivado and we have to use "(* dont_touch = “yes” *) wire foo" and add support for that in migen.build.
- 2)Timings constraints for ethernet should be moved to MiniSoC target in MiSoC.

We could do 2) without 1) but we still have to fix 1) since I'm not sure timings constraints are correcly applied when building with Vivado (the Vivado log should show it when applying the XDC constraints, is there a log somewhere?)

**Comment by sbourdeauducq** [comment]
http://buildbot.m-labs.hk/builders/artiq-board/builds/134/steps/conda_build/logs/stdio

**Comment by sbourdeauducq** [comment]
Could this be the reason for the Ethernet bugs we are seeing with some switches?

**Comment by enjoy-digital** [comment]
Not sure but possible:

WARNING: [Vivado 12-507] No nets matched 'eth_clocks_rx'. [/var/lib/buildbot/slaves/debian-stretch-amd64-2/miniconda/conda-bld/work/misoc_nist_clock_kc705/gateware/top.xdc:1027]
CRITICAL WARNING: [Vivado 12-4739] create_clock:No valid object(s) found for '-objects [get_nets eth_clocks_rx]'. [/var/lib/buildbot/slaves/debian-stretch-amd64-2/miniconda/conda-bld/work/misoc_nist_clock_kc705/gateware/top.xdc:1027]

**Comment by sbourdeauducq** [comment]
Done.
