### ISSUE TITLE
coreanalyzer broken

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#324]
I went ahead and fixed the other two bugs. There are probably more:

```
(py35)rj@tito:~/.../artiq/run (master)$ artiq_coreanalyzer -d foo.dump -w fooo.vcd -p
Log channel: 25
Traceback (most recent call last):
  File "/home/rj/src/conda/envs/py35/bin/artiq_coreanalyzer", line 9, in <module>
    load_entry_point('artiq', 'console_scripts', 'artiq_coreanalyzer')()
  File "/home/rj/work/nist/artiq/artiq/frontend/artiq_coreanalyzer.py", line 51, in main
    print("DDS channel:", decoded_dump.dds_channel)
AttributeError: 'DecodedDump' object has no attribute 'dds_channel'
(py35)rj@tito:~/.../artiq/run (master)$
```

**Comment by whitequark** [comment]
FYI there's also the bug where you need an even total number of RTIO messages or some of them get dropped. We've discussed it and decided not to add a workaround in runtime before it's fixed in gateware because the workaround is quite ugly and tricky to get right.

**Comment by sbourdeauducq** [comment]
What two other bugs?

**Comment by sbourdeauducq** [comment]
And again: the messages are not dropped, they are not moved from the buffer at an appropriate time.

**Comment by jordens** [comment]
See the commit log.

**Comment by sbourdeauducq** [comment]
I already did, if I commented here that's because I didn't find analyzer-related commits.

**Comment by jordens** [comment]
The other two were multi DDS bus related.
