### ISSUE TITLE
gateware runtime API versions

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#326]
Once the 1.0 dust settles, instead of asking for exactly matching git hashes for gateware and software (both in packaging and in protocol negotiation), we may want to introduce an API version between the runtime and the gateware (and maybe one between the runtime and the rest of the world). It would need increasing if the csr or the memory layout or the behavior of the gateware changes. Looks like manually tracking it will be required.

But it would reduce the amount of waiting, gateware building, and flashing. The gateware-software hash mismatch warnings are excellent but they are not fatal (nor shoud they be) and ignoring them could become a habit.

C.f. #97

**Comment by dhslichter** [comment]
This seems reasonable to me but will obviously require considerably more manual effort on the part of m-labs to ensure that software and gateware remain compatible.  I am not extremely worried about this, whatever way people decide.

**Comment by sbourdeauducq** [comment]
Even if the current solution is pretty heavy-handed, it has the advantage of clearly marking user-modified ARTIQ gateware as such.

**Comment by sbourdeauducq** [comment]
I propose we keep it.

**Comment by jordens** [comment]
It could still mark user-modified gateware as such.

But ok. Not a real issue for end-users anyway.
