### ISSUE TITLE
Qt creates visual chaos when editing applet table

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#327]
With Gnome 3:

![qtedit](https://cloud.githubusercontent.com/assets/720864/13720401/8b9c7ba4-e842-11e5-89b6-5de0bbde5980.png)

I only notice this bug on Arch Linux. Ubuntu and Windows are not affected. @jordens @whitequark can you reproduce this?

**Comment by whitequark** [comment]
Theme-related perhaps?

**Comment by jordens** [comment]
Fine here with out conda qt. Looks like it breaks when switching between the wrapped rendering and the one-line editing.

**Comment by sbourdeauducq** [comment]
Bug is not present when run under KDE.

**Comment by sbourdeauducq** [comment]
Bug still present with Qt5.6.

**Comment by sbourdeauducq** [comment]
Fine now. Could be the upgrade to 5.7.
