### ISSUE TITLE
name manual deployments from CI after their branch

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#336]
... otherwise master CI builds override release doc builds etc.

**Comment by sbourdeauducq** [comment]
What about having the master CI upload docs in ``artiq/manual-dev`` and the releases in ``artiq/manual``? I don't think we need to keep all old manuals online.

**Comment by whitequark** [comment]
Why not?

**Comment by sbourdeauducq** [comment]
loads of files laying around, more complex folder structure. How would you name the paths?

**Comment by whitequark** [comment]
manual-$BRANCH

**Comment by sbourdeauducq** [comment]
And symlink manual to the latest?

**Comment by whitequark** [comment]
No symlinking. That would break any existing links or bookmarks every time we release.

**Comment by whitequark** [comment]
Instead, redirect.

**Comment by sbourdeauducq** [comment]
That needs to be a deep redirect then. How do you do that?

**Comment by whitequark** [comment]
Doesn't need to be. The manual itself uses relative links and something outside just links to `/manual`, which should appropriately redirect. Afterwards, all URLs will already point where they should.

**Comment by sbourdeauducq** [comment]
There are already a few links pointing inside ``/manual``, but OK.

**Comment by whitequark** [comment]
Yes, in that case a deep redirect is needed.

**Comment by whitequark** [comment]
It's trivial to do with any reasonable webserver, e.g. Nginx or Apache, by using their rewrite module.

**Comment by sbourdeauducq** [comment]
But I do not have access to the server configuration.

**Comment by whitequark** [comment]
Then get a better server. This is one of the simplest things that any host is supposed to support.

Changing the URL underneath will lead to link rot and confusion. I would know; I did this mistake on http://rxr.whitequark.org and now dozens of inbound links from stackoverflow etc point to either 404 or, even worse, subtly wrong results. This is unacceptable.

**Comment by jordens** [comment]
Currently it goes to `https://m-labs.hk/artiq/manual-%25(branch)s/index.html`. No variable replacement.

**Comment by jordens** [comment]
I put a redirect 301 into htaccess.
