### ISSUE TITLE
i2c.py bug

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#347]
line 102

` def set(self, outputs):`

Should be output or line 112 should be outputs.

Also the comment on line 109 should read that if the bit in the configuration register is set to 1, it's an input. At least that's how I understand it from page 24 of http://www.ti.com/lit/ds/symlink/tca6424a.pdf

**Comment by jordens** [comment]
They are all outputs (of this chip). This the value driven here and thus the direction of the TTL channel (of the buffer).
You could make the argument that this class should not explain what happens downstream of itself.
