### ISSUE TITLE
IPv6 on the core device

### ISSUE THREAD

**Issue by whitequark** [m-labs/artiq#349]
In practical terms, this makes it easier to work with a core device on an internal network from outside that network, as there is no longer any need to poke holes in NAT, or various tunneling solutions. It also permits IPv6-only deployments.

**Comment by sbourdeauducq** [comment]
If for once lwip works correctly, it should be easy. Try it on the master branch so we have plenty of time to notice if it breaks anything else.

**Comment by whitequark** [comment]
We have migrated from lwip; IPv6 support now depends on smoltcp: https://github.com/m-labs/smoltcp/issues/3.
