### ISSUE TITLE
feature request: DDS bus reset

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#35]
Command to reset all DDSs on DDS bus without requirement to reset FPGA.

**Comment by jordens** [comment]
Rationale?
I can only imagine needing to reset the DDSs (do you want the bus/phy logic or the DDS) if you hit a bug in ARTIQ.

**Comment by jboulder** [comment]
Use scenario: Artiq user suspects flakey DDS/TTL bus is resulting in erroneous frequency/phase. Reset of bus can test this. 
* pull rest pin on DDS
* reprogram configuration register
* continue with whatever experiment is scheduled next

**Comment by jordens** [comment]
Sounds like the tools that are planned and already there are much better at confirming/excluding flakey DDS/TTL hardware and bugs in ARTIQ than a DDS reset would ever be.

**Comment by sbourdeauducq** [comment]
There is ``artiq.coredevice.dds.DDS.init()``, but as Robert points out, you probably should not really need to use it.

**Comment by jboulder** [comment]
At present the reset button on the Kintex7 eval board is accessible with
the FMC connector attached. This may not be the case in the future if
things get boxed up.

At present the reset button on the Pipistrello is difficult to access when
the TTL/DDS bus adapter PCB is attached to its headers.

Its good to know about artiq.coredevice.dds.DDS.init(). -Joe

**Comment by jordens** [comment]
This is about DDS reset/init. FPGA reset/init is a different problem. But if somebody needs it it is always a bug and never a solution.

**Comment by sbourdeauducq** [comment]
I believe this can be resolved by using ``artiq.coredevice.dds.DDS.init()`` in the worst case. Please open a new issue if you have trouble resetting the FPGA.
