### ISSUE TITLE
Port OR1K backend to newer LLVM

### ISSUE THREAD

**Issue by whitequark** [m-labs/artiq#350]
We have LLVM 3.5 and we need at least LLVM 3.6 for, at least, [!nonnull metadata on loads](https://github.com/m-labs/artiq/issues/338#issuecomment-202199865).

**Comment by whitequark** [comment]
I've upgraded to LLVM 3.6. Unfortunately this broke debug info (i.e. backtraces) as LLVM 3.6 has changed format; since the format changes again in 3.7 and 3.7 is what upstream llvmlite uses, we should just upgrade to LLVM 3.7.

3.5→3.6 took a day, 3.6→3.7 shouldn't take longer. I might even consider 3.7→3.8 with accompanying llvmlite changes if that's profitable.

**Comment by sbourdeauducq** [comment]
This is done, isn't it? Maybe merge into release-1 and close this?
