### ISSUE TITLE
device_db.pyon linter/autogeneration

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#355]
I think it would be useful if an error message were generated if dds channels were duplicated. For example, I tried these entries in the device_db.pyon file, 

``` python
    "dds0": {
        "type": "local",
        "module": "artiq.coredevice.dds",
        "class": "AD9914",
        "arguments": {"bus_channel": 58, "channel": 0},
        "comment": "Comments work in DDS panel as well"
    },
    "dds1": {
        "type": "local",
        "module": "artiq.coredevice.dds",
        "class": "AD9914",
        "arguments": {"bus_channel": 58, "channel": 0},
    },
```

And the experiment I had ran without any issues, but in setting dds0 and dds1 the same dds was essentially being set twice.

**Comment by sbourdeauducq** [comment]
The more general feature should be a "device DB linter" that issues warnings for this and other potential issues (same problem with TTLs, no core device defined, etc.). The master and artiq_run could run the linter automatically after reading the DDB.

**Comment by sbourdeauducq** [comment]
@r-srinivas since the experiment ran without issues, we can close #305? Was frequency monitoring also OK in the GUI?

**Comment by jordens** [comment]
A linter can catch a few obvious errors but it will only be a small aid.

**Comment by r-srinivas** [comment]
Frequency monitoring meaning? I could run DDS Setter on windows and it seemed to work fine with the one working DDS I have left.

**Comment by sbourdeauducq** [comment]
The DDS panel that shows the current frequencies. Anyway, I tested it and it works.

**Comment by r-srinivas** [comment]
That DDS panel isn't showing up for me on the Windows GUI, but I can see it on the virtual box.

**Comment by sbourdeauducq** [comment]
Done for Kasli systems.

**Comment by sbourdeauducq** [comment]
Templates are now on Hydra
e.g.
https://nixbld.m-labs.hk/eval/114?
