### ISSUE TITLE
flterm not responding

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#357]
I was trying to use flterm but it's basically not responding. 

`rabi@68810MAGTRAPVM:~/artiq-dev$ flterm /dev/ttyUSB2`

I've tried the other USB ports and power cycling and resetting the FPGA but I'm not getting any response from it.

These are the USB ports listed,

```
rabi@68810MAGTRAPVM:~/artiq-dev$ flterm /dev/ttyUSB
ttyUSB0  ttyUSB1  ttyUSB2  
rabi@68810MAGTRAPVM:~/artiq-dev$ flterm /dev/ttyUSB
```
If I try /dev/ttyUSB0 I get 

```
rabi@68810MAGTRAPVM:~/artiq-dev$ flterm /dev/ttyUSB0
Traceback (most recent call last):
  File "/home/rabi/.local/lib/python3.5/site-packages/pyserial-3.0.1-py3.5.egg/serial/serialposix.py", line 291, in open
OSError: [Errno 5] Input/output error: '/dev/ttyUSB0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rabi/.local/bin/flterm", line 9, in <module>
    load_entry_point('misoc', 'console_scripts', 'flterm')()
  File "/home/rabi/artiq-dev/misoc/misoc/tools/flterm.py", line 255, in main
    flterm = Flterm(args.port, args.speed, args.kernel, args.kernel_addr)
  File "/home/rabi/artiq-dev/misoc/misoc/tools/flterm.py", line 129, in __init__
    self.port = asyncserial.AsyncSerial(port, baudrate=speed)
  File "/home/rabi/anaconda3/lib/python3.5/site-packages/asyncserial-0.1-py3.5.egg/asyncserial/asyncserial.py", line 11, in __init__
  File "/home/rabi/.local/lib/python3.5/site-packages/pyserial-3.0.1-py3.5.egg/serial/__init__.py", line 85, in serial_for_url
  File "/home/rabi/.local/lib/python3.5/site-packages/pyserial-3.0.1-py3.5.egg/serial/serialposix.py", line 294, in open
serial.serialutil.SerialException: [Errno 5] could not open port /dev/ttyUSB0: [Errno 5] Input/output error: '/dev/ttyUSB0'
```

But no response from ttyUSB1 or 2. The user (rabi) has been added to dialout.

**Comment by whitequark** [comment]
Can you get any output using `cat /dev/ttyUSBN`?

**Comment by r-srinivas** [comment]
I get this if I try that,

```
rabi@68810MAGTRAPVM:~/artiq-dev$ cat /dev/ttyUSB1
rabi@68810MAGTRAPVM:~/artiq-dev$ cat /dev/ttyUSB2
rabi@68810MAGTRAPVM:~/artiq-dev$ cat /dev/ttyUSB3
cat: /dev/ttyUSB3: No such file or directory
rabi@68810MAGTRAPVM:~/artiq-dev$ cat /dev/ttyUSB0
cat: /dev/ttyUSB0: Input/output error
rabi@68810MAGTRAPVM:~/artiq-dev$ 
```

**Comment by whitequark** [comment]
Right, I forgot you can't do this to ttys using `cat`. Nevermind what I said.

**Comment by sbourdeauducq** [comment]
Works fine here.

**Comment by sbourdeauducq** [comment]
Are you sure this isn't just some VM USB bug? This happened regularly when I visited NIST. Try rebooting the VM.

**Comment by r-srinivas** [comment]
I tried it briefly on a linux computer that we have and had the same problem but I'll look into it again tomorrow.

**Comment by jordens** [comment]
Please first identify which serial device you want to use instead of guessing. E.g. a) use the one that appears if you plug in the relevant cable, b) use `ls /dev/serial/by-id`, c) use `dmesg` etc.
All version numbers (gateware, runtime, artiq) as well, please.

**Comment by sbourdeauducq** [comment]
Can you also try with gtkterm and/or the C flterm?

**Comment by jordens** [comment]
And also are you actually booting the device when you do this? Do the leds blink?

**Comment by r-srinivas** [comment]
Okay, so it works now after I restarted the virtual machine again. Not sure why it didn't when I had restarted it before. Thanks.
