### ISSUE TITLE
GUI crashes on windows if I open a new log dock and close the log dock

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#362]
If I create a new log dock, and then try to close the new log dock that pops up I get a message saying Python has stopped working. You're then forced to close the programme and restart the gui. I can't do a keyboard termination on the command prompt with the gui so I can't seem to get a traceback, sorry.

If I dock the new window first somewhere it's fine, it's only if it's floating and I close it that it generates the error.

**Comment by sbourdeauducq** [comment]
``Unhandled exception at 0x000000006D688040 (Qt5Core.dll) in python.exe: 0xC0000005: Access violation reading location 0x0000000000000290.``
Looks like the result of pyqt's typical lousy memory management.
