### ISSUE TITLE
reimplement ARTIQ in C/C++

### ISSUE THREAD

**Issue by dhslichter** [m-labs/artiq#367]
NIST IT security has just pushed a new policy that any and all software developed by outside contractors must be in C or C++ only.  Apparently they are going to run some sort of scanning software on the source to look for malicious code and this will only work on code written in C or C++.  All other programming languages are banned.  So we will need to reimplement the entirety of ARTIQ in C or C++.

**Comment by whitequark** [comment]
I agree. This will make using Qt much easier.

**Comment by sbourdeauducq** [comment]
It's already done because Oxford requested a MS-DOS port. Will release the sources soon.
![msdos](https://cloud.githubusercontent.com/assets/720864/14226842/bcb76c32-f920-11e5-98d2-569a1e211dba.jpg)
