### ISSUE TITLE
Display experiment time/name and results of fit in applet

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#376]
How do I go about getting the applet to display various data? For example, it would be useful if the time when the experiment ran or its RID was displayed in the applet title or somewhere. The results of a fit that is done is also useful to have. In the context of the flopping simulation, the resonant frequency f0 for example would be useful to display on the applet.

**Comment by jordens** [comment]
You have to write that applet.

**Comment by sbourdeauducq** [comment]
With the next commits:
```
$python -m artiq.applets.plot_xy --embed $ipc_address --title "Freq: {flopping_freq}" flopping_f_brightness
```
But yes, you should dig into the applet source and look into how to customize them. Not all options can be put into the command lines.

RID is another issue.
