### ISSUE TITLE
position and size of floating applets is not saved upon GUI restart

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#378]
When an applet is floating, it incorrectly gets back its default size and position upon GUI restart. When an applet is docked, Qt correctly restores its size and position (minus the bug described in #287).

Log docks (which are also dynamically created by the GUI) do not have this problem.

Commenting out ``self.resize`` in ``_AppletDock.__init__`` does not solve this problem.

``objectName`` appears to be correctly set.

The sequence of function calls to Qt for docking and restoring state appears to be identical between log and applet docks.

**Comment by sbourdeauducq** [comment]
@jordens can you reproduce that? Might be another WM-related bug, as this seems to be assorted with a window focus issue.

**Comment by sbourdeauducq** [comment]
Problem not present on Windows 7 (also tested with 1d94cfd8ed4684ecb10c3601659c8b53d8bcb482). Looks like another Qt bug.

**Comment by jordens** [comment]
Works fine here. Floating applets are restored to position and size.

**Comment by sbourdeauducq** [comment]
Can't reproduce this anymore (Qt 5.7). Closing for now.
