### ISSUE TITLE
Memory leak in artiq_gui

### ISSUE THREAD

**Issue by cjbe** [m-labs/artiq#379]
Using Artiq 1.0rc2 on Ubuntu 15.10, with the examples/master device_db, and the kc705-clock gateware, artiq_gui leaks memory. 

Over 1000 minutes, the RSS linearly increased from 87 MB to 1500 MB.

I don't think this is a regression - I believe I have seen this issue in earlier versions of artiq_gui.

**Comment by sbourdeauducq** [comment]
Were you running something in particular or is the memory consumption increasing while nothing is happening?

**Comment by cjbe** [comment]
I was not running anything. I just started the master, ctrlmgr, and gui, and monitored the memory usage

**Comment by sbourdeauducq** [comment]
Were there any logging messages emitted by e.g. ctlmgr?

**Comment by cjbe** [comment]
No logging messages were emitted

**Comment by jordens** [comment]
Reproduced. Comes in chunks of about 6MB and valgrind doesn't see it. It's probably not strictly a "leak" then.

**Comment by sbourdeauducq** [comment]
Python has some functions to print the state of the GC (number of live objects, etc.). What do they say if you call them regularly with a timer?

**Comment by jordens** [comment]
http://mg.pov.lt/objgraph.py

**Comment by jordens** [comment]
10 Qtimers, 10 functions, 10 tuples, and 30 cells per second.

**Comment by jordens** [comment]
probably https://github.com/harvimt/quamash/issues/62

**Comment by jordens** [comment]
was quamash.
@sbourdeauducq or @whitequark could you please copy the package over?

**Comment by sbourdeauducq** [comment]
Already there.

**Comment by jordens** [comment]
There is a bunch of `Exception ignored in: Exception ignored in: ` pairs with the new quamash one for each applet. https://bugs.python.org/issue22836
