### ISSUE TITLE
artiq_master -g crashes on windows

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#386]
I was trying to go through the steps of git integration on windows. I've done the following,

- copied my repository folder into another folder called artiq_work
- made a new folder called repository
- initialised an empty repository there

```
rabi@68810NEWASSY MINGW64 /c/Anaconda3/artiq_test/repository
$ git init --bare
Initialized empty Git repository in C:/Anaconda3/artiq_test/repository/
```

I tried running `artiq_master -g` from ` /c/Anaconda3/artiq_test/` and I get an error message saying Python has stopped working.

I should add that I had installed git bash to put in the git commands.

**Comment by sbourdeauducq** [comment]
Probably pygit2 crashing when interfacing with libgit.

**Comment by sbourdeauducq** [comment]
This is sufficient to cause the crash:
```python
import pygit2
x = pygit2.Repository("some_repos")
```

**Comment by sbourdeauducq** [comment]
The crash happens in ``msvcr120.dll`` called by ``git2.dll``.

**Comment by whitequark** [comment]
What's the exact backtrace?

**Comment by sbourdeauducq** [comment]
I don't know, visual studio DRM bullshit prevents me from seeing it.

**Comment by whitequark** [comment]
To make VS work, set the date to Feb 1.

This is how it crashes:
![2150](https://cloud.githubusercontent.com/assets/54771/14917442/92e00dd0-0e0e-11e6-898f-d3d7c7fbdf51.png)

Looks like a libgit2 bug...

**Comment by sbourdeauducq** [comment]
I suppose enabling debugging symbols in libgit2 would give more info.

**Comment by whitequark** [comment]
It was an ABI mismatch; libssh2, libgit2 and pygit2 were built with VC12 but at some point conda upgraded Python to VC14 (or something like this).

It is fixed now. Note that I ripped out openssl from libssh2 because openssl is built with old VC, no idea whether this materially affects ARTIQ.

**Comment by jordens** [comment]
Other conda packages seem to tie down the msvc_runtime abi of their python.

**Comment by whitequark** [comment]
I think it does something mostly right when Python is a dependency but in our case it isn't, and CMake needs explicit specification of the toolset.

**Comment by jordens** [comment]
pygit2 should have python as a dependency, right?

**Comment by whitequark** [comment]
I guess.
