### ISSUE TITLE
renaming selected experiment in subfolder causes GUI crash

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#388]
I have this experiment here,

```python
from artiq.experiment import *


class DDS0_Start(EnvExperiment):
    def build(self):
     
        self.setattr_device("core")
        self.setattr_device("core_dds")
        self.setattr_device("dds0")

    @kernel
    def run(self):
        self.dds0.init()
        delay(10*ms)
        self.dds0.set(100*MHz)
```

I did the following,

-open experiment
-change experiment name from `DDS0_Start` to `DDS0_Start2`
-GUI crashes

There's some sort of traceback on the command prompt but it's hard to capture before it closes. 

This sequence also crashes the GUI,

-open experiment
-close experiment
-change experiment name from `DDS0_Start` to `DDS0_Start2`
-GUI crashes

The master is running fine in the meantime. This doesn't happen to me on the virtual machine.

**Comment by sbourdeauducq** [comment]
If you run the GUI in a ``cmd`` window, not with ``start artiq_gui``, the traceback should stay. We do need tracebacks in most cases to debug something.

**Comment by sbourdeauducq** [comment]
How did you change the name? Did you also run a repository re-scan?

**Comment by r-srinivas** [comment]
I changed the name in the python script then scanned the repository through
the GUI.

**Comment by r-srinivas** [comment]
Sorry, I should have specified that it's the scanning of the repository
that triggers the crash. I've been having the artiq_gui open in a cmd
window but it closed before I could see the traceback.

**Comment by sbourdeauducq** [comment]
``cmd`` windows should not close when the application terminates. How exactly did you start the GUI?

**Comment by r-srinivas** [comment]
I had a .cmd file that starts the gui.

Something like,

```
cd c:\anaconda3\artiq_test
activate artiq-2016-04-04
artiq_gui
```

I guess I should have just done it manually for the traceback. Maybe I cmd
/k at the end would help.

**Comment by jordens** [comment]
Yes. The effect of that `.cmd` could be achieved much easier with just a shortcut.

**Comment by sbourdeauducq** [comment]
@r-srinivas On an unrelated note, you should probably call ``dds.init`` once in the startup kernel and not in every experiment.

**Comment by sbourdeauducq** [comment]
@r-srinivas I cannot reproduce the problem so please post your traceback.

**Comment by r-srinivas** [comment]
So just to clarify, this is the sequence of events.

-double click on `DDS0_Start` in GUI to open experiment panel
-change name of experiment to `DDS0_Start2` in Spyder
-right click on experiment explorer and click `Scan repository HEAD`
-GUI Closes with the following traceback
```
Traceback (most recent call last):
  File "C:\Anaconda3\envs\artiq-2016-04-04\lib\site-packages\artiq\gui\models.py
", line 258, in index
    parent_item.children_by_row[row])
IndexError: list index out of range
```

**Comment by sbourdeauducq** [comment]
Are you sure opening the experiment is necessary? This should not touch any models.

**Comment by sbourdeauducq** [comment]
Is your experiment at the root of the repository or in a subfolder? Can you post the full contents of your repository?

**Comment by r-srinivas** [comment]
It's in a subfolder. For the file it's in repository/dds/dds0_start.py Yes, if I don't open the experiment then scanning the repository just updates the file name without crasing the gui.

**Comment by sbourdeauducq** [comment]
Reproduced. The actual conditions are:

  1. the renamed experiment must be in a subfolder
  2. the renamed experiment must be selected in the explorer (opening is not necessary)

**Comment by sbourdeauducq** [comment]
This is also independent of Windows/Linux.

**Comment by r-srinivas** [comment]
Probably the reason why I couldn't reproduce it on the windows machine was because the experiment wasn't in a subfolder. I didn't think that would have been an issue.

**Comment by sbourdeauducq** [comment]
Qt trees are very complicated.
