### ISSUE TITLE
py2llvm: unroll loops based on necessity and not size

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#42]
Loops should be unrolled in py2llvm when required by control flow (e.g. interleaving). Other unrollings should be left to LLVM.

**Comment by whitequark** [comment]
new-py2llvm does/will not unroll loops unless necessary.

**Comment by sbourdeauducq** [comment]
Does it handle this properly:
```python

    @kernel
    def run(self):
        for t in range(10):        
            t2 = t*100
            with parallel:
                self.ttl0.pulse(t2)
```

**Comment by whitequark** [comment]
Closing as unrolling is merged; your comment will be addressed in a separate issue.
