### ISSUE TITLE
Increasing current drive for nist_qc2 DDS bus signal integrity

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#421]
We had some issues when loading the backplane with 11 DDS`. They started failing to programme starting from DDS0, which seems to be due to some bus signal integrity issues. This can be fixed by increasing the current drive from 12 to 24 mA. This enables us to handle a fully loaded bus. Could we apply the following patch to gateware/nist_qc2.py? Are there any issues with raising the current?

```diff
diff --git a/artiq/gateware/nist_qc2.py b/artiq/gateware/nist_qc2.py
index 12c775f..a7bd746 100644
--- a/artiq/gateware/nist_qc2.py
+++ b/artiq/gateware/nist_qc2.py
@@ -43,7 +43,7 @@ def get_fmc_adapter_io():
                 Subsignal("wr_n", FPins("FMC:LA24_P")),
                 Subsignal("rd_n", FPins("FMC:LA25_N")),
                 Subsignal("rst", FPins("FMC:LA25_P")),
-                IOStandard("LVTTL")),
+                IOStandard("LVTTL"),  Misc("DRIVE=24")),
 
             ("i2c_fmc", next(i2c_fmc),
                 Subsignal("scl", FPins("FMC:IIC_SCL")),
```

**Comment by sbourdeauducq** [comment]
There are no particular issues. Did you get the backplane to work with 11 DDSes?

**Comment by r-srinivas** [comment]
Yes, 11 seemed to work fine with flterm. The io_update signal at least looked better on the scope as well.

**Comment by dhslichter** [comment]
Note that we only used 11 DDS cards because one of the slots on the backplane wasn't working correctly; we will test with a full load of 12 at a later stage.

**Comment by r-srinivas** [comment]
Tested with 12 DDS boards with flterm and it seems to work.
