### ISSUE TITLE
Experiment panel inaccessible if title bar too high

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#427]
Using 1.0 rc3 on Windows, bit of a stupid bug but if you accidentally move one of the experiment panels too high such that the title bar is obscured by the GUI title bar, you can't access it. You're then forced to reset the gui through its pyon file. Could the experiment panels have a limit to how high they can be moved?

**Comment by sbourdeauducq** [comment]
Doesn't a scroll bar appear in this case?

**Comment by sbourdeauducq** [comment]
That's what it does here, note the scroll bar on the right.
![scroll](https://cloud.githubusercontent.com/assets/720864/15080776/4737b880-13f2-11e6-93e5-fcde27db770f.png)

**Comment by r-srinivas** [comment]
You're right, thanks.
