### ISSUE TITLE
Python compiler: place compile-time constants into .rodata when possible

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#43]
that would reduce code size for experiments needing large tables of data (e.g. randomized benchmarking).

**Comment by whitequark** [comment]
Done in new-py2llvm (although only truly immutable data, such as strings, currently goes to `.rodata`).

**Comment by sbourdeauducq** [comment]
We are going to need to upload other types as rodata, though this is a low-priority feature.

**Comment by whitequark** [comment]
The new compiler uploads embedded lists and such as `.data`.
