### ISSUE TITLE
passing lists into XYPlot

### ISSUE THREAD

**Issue by vmsch** [m-labs/artiq#436]
I am trying to use XYPlot including the fit argument, however it only appears to work if the x parameter is a ndarray, not if this is a list, ie
{python} -m artiq.applets.plot_xy --embed {ipc_address} p --x t --fit P_fit
works if t is a ndarray, but does not plot the fit if t is a list.
The error seems to occur in l.51 of plot_xy, when calling x[xi].

Is there a reason why the argument for x has to be a ndarray, or is this a bug?

**Comment by sbourdeauducq** [comment]
Only Numpy arrays are supported for array datasets.

**Comment by vmsch** [comment]
Ok, thanks.
