### ISSUE TITLE
put artiq_*.pyon GUI state files into standard locations

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#438]
See discussion in https://github.com/m-labs/artiq/commit/d4ba525c9df4d6c951d9633f50e0f32e4511a967

**Comment by jordens** [comment]
I'd follow (and rip out) the heuristics from e.g. https://github.com/joyent/python-manta/blob/master/manta/appdirs.py#L31 maybe even pull in appdirs.
@whitequark @sbourdeauducq ok/comments?

**Comment by sbourdeauducq** [comment]
I'm fine with those heuristics, the only thing that worries me is handling cases like the pyon folder or its parent not existing.
