### ISSUE TITLE
add info about setting gateware and netmask to installation doc

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#441]
Is there any way of specifying the subnet mask on the KC705? We can't connect to the board unless we're on the same subnet, which is not always the case for even computers in the same room. We can work around this but it be easier if we could specify the subnet on the KC705.

**Comment by jordens** [comment]
subnet mask is not the limiting factor here. needs a default gateway.

**Comment by jordens** [comment]
both (`netmask` and `gateway`) are storage entries like `ip`. try that.

**Comment by r-srinivas** [comment]
Okay. Could this be added to the installation page, then?

**Comment by r-srinivas** [comment]
Adding the subnet and gateway worked, thanks.
