### ISSUE TITLE
doc: write "Concepts of ARTIQ-RTIO (timeline, now, fifo...)"

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#451]
#449 and similar pitfalls

**Comment by sbourdeauducq** [comment]
Slides I made for a presentation at NIST about this.
[aq_timing.zip](https://github.com/m-labs/artiq/files/305945/aq_timing.zip)

**Comment by sbourdeauducq** [comment]
Moving to 2.0:
 * let's get 1.1 out soon
 * this will be changed (inter-experiment seamless handover)
 * there are my slides in the meantime
