### ISSUE TITLE
AD9858  PHASE_MODE_CONTINUOUS broken 

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#46]
On 6/19 PHASE_MODE_CONTINUOUS was working but PHASE_MODE_TRACKING was broken.
On 6/20 PHASE_MODE_TRACKING was fixed but PHASE_MODE_CONTINUOUS was not retested.
On 6/21 PHASE_MODE_TRACKING works but PHASE_MODE_CONTINUOUS is broken.

![ddd](https://cloud.githubusercontent.com/assets/5688774/8274451/af58f220-184f-11e5-9853-030653b494f9.png)

```python
class TestDDSPhase(Experiment, AutoDB):
	class DBKeys:
		core = Device()
		dds_bus = Device()
		dds0 = Device()
		dds1 = Device()
		ttl0 = Device()
		ttl1 = Device()

	@kernel
	def run(self):
		self.dds0.set_phase_mode(PHASE_MODE_CONTINUOUS)
		self.dds1.set_phase_mode(PHASE_MODE_CONTINUOUS)
		for i in range(10):
			# force DDSs to be phase synchronized at outset of experiment
			# this is a temporary override of the default phase mode
			with self.dds_bus.batch:
				self.dds0.set(3*MHz, phase_mode=PHASE_MODE_ABSOLUTE, phase_offset=0)
				self.dds1.set(3*MHz, phase_mode=PHASE_MODE_ABSOLUTE, phase_offset=0)

			# emit experiment start pulse on TTL0
			self.ttl0.pulse(1*us)

			# demonstrate simple spin-echo type pulse sequence
			self.dds0.set(3*MHz, phase_offset=0, phase_mode=PHASE_MODE_CONTINUOUS)
			self.ttl1.pulse(1*us) # first pi/2 pulse
			self.dds0.set(3*MHz, phase_offset=0.25, phase_mode=PHASE_MODE_CONTINUOUS)
			delay(2*us) # arm time
			self.ttl1.pulse(2*us) # middle pi pulse
			self.dds0.set(3*MHz, phase_offset=0, phase_mode=PHASE_MODE_CONTINUOUS)
			delay(2*us) # arm time
			self.ttl1.pulse(1*us) # final pi/2 pulse

			# delay to let Core_uP catch up
			delay(1*ms)

**Comment by jboulder** [comment]
Here's a clearer illustration. 

![tek00017](https://cloud.githubusercontent.com/assets/5688774/8274560/6f37877c-1851-11e5-812e-451947a7125e.PNG)


```python
class TestDDSPhase(Experiment, AutoDB):
	class DBKeys:
		core = Device()
		dds_bus = Device()
		dds0 = Device()
		dds1 = Device()
		ttl0 = Device()
		ttl1 = Device()

	@kernel
	def run(self):
		self.dds0.set_phase_mode(PHASE_MODE_CONTINUOUS)
		self.dds1.set_phase_mode(PHASE_MODE_CONTINUOUS)
		for i in range(10):
			# force DDSs to be phase synchronized at outset of experiment
			# this is a temporary override of the default phase mode
			with self.dds_bus.batch:
				self.dds0.set(3*MHz, phase_mode=PHASE_MODE_ABSOLUTE, phase_offset=0)
				self.dds1.set(3*MHz, phase_mode=PHASE_MODE_ABSOLUTE, phase_offset=0)

			# emit experiment start pulse on TTL0
			self.ttl0.pulse(1*us)

			# demonstrate simple spin-echo type pulse sequence
			# self.dds0.set(3*MHz, phase_offset=0, phase_mode=PHASE_MODE_CONTINUOUS)
			self.ttl1.pulse(.5*us) # first pi/2 pulse
			self.dds0.set(3*MHz, phase_offset=0.25, phase_mode=PHASE_MODE_CONTINUOUS)
			
			delay(1*us) # arm time
			
			self.ttl1.pulse(1*us) # middle pi pulse
			self.dds0.set(3*MHz, phase_offset=0, phase_mode=PHASE_MODE_CONTINUOUS)
			
			delay(1*us) # arm time
			
			self.ttl1.pulse(0.5*us) # final pi/2 pulse

			# delay to let Core_uP catch up
			delay(1*ms)

**Comment by jboulder** [comment]
Quick test to see if this behavior is related to the timing of the FTW. 
1) reset power on DDS box and reset DDS
2) run program above
3) look on scope

![tek00003](https://cloud.githubusercontent.com/assets/5688774/8292359/7c3322c4-18ec-11e5-9cca-21c4f38f4d96.PNG)
![tek00005](https://cloud.githubusercontent.com/assets/5688774/8292338/611d8bdc-18ec-11e5-824b-6e5b7a25a6a0.PNG)
![tek00006](https://cloud.githubusercontent.com/assets/5688774/8292337/611d487a-18ec-11e5-9e83-a0d7c8130086.PNG)
![tek00007](https://cloud.githubusercontent.com/assets/5688774/8292339/6120029a-18ec-11e5-84e6-3c6d07a19697.PNG)

**Comment by sbourdeauducq** [comment]
Do you still have any issue with a board flashed with the latest runtime from the conda packages? I pushed the bugfixes only recently. Do you have this commit: https://github.com/m-labs/artiq/commit/87ea1433d3bef86ad5b3a06651b6d4d880cdc343

**Comment by jboulder** [comment]
I will try to two suggestions you made. It will be a day or two. We are
back running on the old DDS system at the moment. -Joe

**Comment by jboulder** [comment]
OK. Resolved in today's conda build. 

![untitled picture](https://cloud.githubusercontent.com/assets/5688774/8336093/24dc0cce-1a5f-11e5-975e-84ae5d71abee.png)

**Comment by sbourdeauducq** [comment]
Good. Thanks for the quick re-test!
