### ISSUE TITLE
scientific spinbox

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#460]
See discussion in #457 

Other points:
* dealing with ``step``
* using ``ScientificSpinBox`` for non-integer ``NumberValue``

**Comment by sbourdeauducq** [comment]
Regarding ``step``:

@jordens Your scientific spinbox design modifies the coefficient part by a fixed amount (whatever the exponent) when the arrows are clicked. ARTIQ/Qt has a ``step`` parameter that modifies the floating point value by a fixed amount. What shall we do?

**Comment by jordens** [comment]
I had put a couple thoughts on that general topic in comments in the code in the scanwidget. I would like to consistently link the four sources of "step/resolution/tick/snap": the ticker step, the spinboxes value resolution, the spinbox step size, the ticker step modified by npoints. But I have not decided yet what the best approach is and whether it is actually doable.

**Comment by jordens** [comment]
The current implementation looses the unit suffix most of the time when ctrl- or shift-wheeling on a spinbox.

**Comment by jordens** [comment]
An intuitive coupling of `singleStep` and `relativeStep` with the ticker step is still desirable but not urgent.

**Comment by jordens** [comment]
Forked issue.
