### ISSUE TITLE
coreanalyzer log broken

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#461]
If an experiment executes e.g. ``rtio_log("foo", 32)`` then coreanalyzer will fail in analyzer.py with:
``channel_name, log_message = log_entry.split("\x1E", maxsplit=1)`` Too many values to unpack

**Comment by whitequark** [comment]
Cannot reproduce. What I did:
```python
from artiq.experiment import *

class Test(EnvExperiment):
    def build(self):
        self.setattr_device("core")

    @kernel
    def run(self):
        rtio_log("foo", 32)
```
```
$ artiq_run test.py
$ artiq_coreanalyzer -p
```

**Comment by whitequark** [comment]
Ah, needs `-w test.vcd`.
