### ISSUE TITLE
scan widget colored handle size too small

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#463]
ARTIQ 1.0 on Windows

Upper and lower scan bounds handles have colored markers. The markers are too small to see.

**Comment by sbourdeauducq** [comment]
only happens sometimes such as some UMD PCs.

**Comment by jordens** [comment]
Those sizes are derived the same way as e.g. the default window sizes. Are those also too small?
Is this some "theme" issue (the scientific spinbox etc not seeing the same themed font)?

**Comment by sbourdeauducq** [comment]
It seems like the actual size is correct, but their bottom part is cut because the widget is not large enough.

**Comment by jordens** [comment]
Got a screenshot?

**Comment by sbourdeauducq** [comment]
Could be related to hi-DPI (that's on a Windows Surface).
<img width="724" alt="capture" src="https://cloud.githubusercontent.com/assets/720864/15809796/928b7576-2b65-11e6-98c0-ec28c6ce0d01.PNG">

**Comment by jordens** [comment]
@jboulder  can you still reproduce this? The scientific spinboxes were dropped after 1.0 and look very different than the other spinboxes in the screenshot. Do you have access to artiq on a windows surface? OK to defer this issue till after 2.0 or is it actively hurting somebody right now?

**Comment by jbqubit** [comment]
I don't currently have access to a high-dpi display like a Microsoft
surface.

**Comment by jordens** [comment]
timed out

**Comment by jbqubit** [comment]
Thanks for the reminder. I now have access to a Windows 10 machine with a high-resolution display (2560x1140). The scan widget and spin boxes are sized correctly and handles are easy to operate.

![image](https://cloud.githubusercontent.com/assets/20543958/22377144/bb85b888-e47e-11e6-86fc-bc8108129f1e.png)

In a multi-display setup I can also have the ARTIQ Dashboard lying half on a high-resolution display and half on a low-resolution display and everthing is rendered correctly. Nice.
