### ISSUE TITLE
minor edits for "Getting started with the core language documentation"

### ISSUE THREAD

**Issue by kellyjoe39** [m-labs/artiq#501]
It would be helpful to give more information about how to find the examples/master directory.  Under a conda installation, this directory is buried deep: all the way down in anaconda3/envs/<env name>/lib/python3.5/site-packages/artiq/examples.  I realize different users will have different installations, but I expect anaconda windows will be your most common setup out there in the user community so please help those people.

Edit "The LED of the device should turn on." to "The process should terminate quietly and the LED of the device should turn on."

**Comment by sbourdeauducq** [comment]
The examples folder is already documented here:
https://m-labs.hk/artiq/manual-release-1/faq.html#find-artiq-examples
