### ISSUE TITLE
Python 3.5.2 cannot connect to ::1 on Windows

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#506]
Currently http://buildbot.m-labs.hk/builders/artiq-win64-test/builds/256/steps/python_unittest/logs/stdio

Initial failures: http://buildbot.m-labs.hk/builders/artiq-win64-test/builds/244/steps/python_unittest/logs/stdio

**Comment by sbourdeauducq** [comment]
Not user-visible and only with Python 3.5.2, so not that serious.

**Comment by whitequark** [comment]
Well, we need to fix the CI anyway, because there is no point in even having it if it's always red.

**Comment by whitequark** [comment]
(Also, right now docs aren't updated at the end of the build, because win64 fails first.)

**Comment by sbourdeauducq** [comment]
Yes. But it still runs the other tests and the same ones on Linux.

**Comment by whitequark** [comment]
It is still useless because of how hard to notice it is that the kind of failure has changed.

**Comment by jordens** [comment]
IMHO all that and if it is not serious then we don't need to hold 1.2.

**Comment by sbourdeauducq** [comment]
http://bugs.python.org/issue27500

**Comment by sbourdeauducq** [comment]
Workarounds: use ``127.0.0.1`` or ``localhost``.

**Comment by cr1901** [comment]
Problem commit/line is: https://github.com/python/cpython/commit/03df54d549173e17e1cf9a767199de32a363aa6b#diff-08afa52ab2b1511bee8527814ad44d80R138

Python 3.5.2 tries to skip calling `getaddrinfo()`, and the function which does that (`_ipaddr_info()`) should be returning a 4-tuple for AF_INET6 family. Instead it only returns 2, and the Windows function `ConnectEx()` doesn't like that some IPv6 fields are missing.
