### ISSUE TITLE
Change order of applets in GUI

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#514]
Using 1.1 on windows, is there an easy way of changing the order of applets on the gui, or to insert a new applet after a specific applet instead of at the end?

**Comment by sbourdeauducq** [comment]
No, there is not.

**Comment by sbourdeauducq** [comment]
This is in the next contract:
"in the dashboard, creating applet groups, renaming groups, moving applets from one group to another (drag-and-drop)."

**Comment by r-srinivas** [comment]
Including moving applets within a group?

**Comment by sbourdeauducq** [comment]
It's not there, but it's probably efficient to do it at the same time as we implement this. I'll see what I can do.
