### ISSUE TITLE
Missing instructions in "Install from source"

### ISSUE THREAD

**Issue by jmizrahi** [m-labs/artiq#516]
There are some errors and missing instructions in the "install from source" section of the documentation:

1) "Install OpenRISC binutils" should include the line "cd binutils-2.26" before "mkdir build"

2) Before "download and install MiSoC," need "download and install asyncserial":
```bash
$ git clone https://www.github.com/m-labs/asyncserial
$ cd asyncserial
$ python3.5 setup.py install
```
3) Before "download and install ARTIQ" need "download and install pythonparser":
```bash
$ git clone https://www.github.com/m-labs/pythonparser
$ cd pythonparser
$ python3.5 setup.py install
```
4) Under "Installing host side software":
`$ git checkout artiq`
should be:
`$ git checkout artiq-3.8`

**Comment by jordens** [comment]
thanks!
