### ISSUE TITLE
Idle kernel turns on during seamless handover 

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#521]
Using artiq 2.0.dev+485.gc0d5914 on windows, I have an idle kernel that turns ttl_bdd(ttl3) on,

```python
from artiq.experiment import *

class IdleKernel(EnvExperiment):
    
    def build(self):
        self.setattr_device("core")
        self.setattr_device("ttl3")

    @kernel
    def run(self):
        self.ttl3.on()
```

I'm trying to run the following experiment at priority -1 in the background, 

```python
from artiq.experiment import *


class Pause_Test(EnvExperiment):
    
    def build(self):
        self.setattr_device("core")
        self.setattr_device("ttl_bdd")
        self.setattr_device("ttl14")
        self.setattr_device("scheduler")

      
    def run(self):
        self.reset_core()
        while True:
            self.pulse_loop()
            self.core.comm.close()
            self.scheduler.pause()
        

    @kernel
    def pulse_loop(self):
        while not self.scheduler.check_pause():
            with parallel:
                self.ttl_bdd.off()
                self.ttl14.pulse(100*ms)
            delay(100*ms)   
            
    @kernel
    def reset_core(self):
        self.core.reset()
        delay(600*ms)
```

I need to call self.core.comm.close() here in order to have this experiment restart once another experiment is completed. If not I get a `ConnectionResetError("Connection closed")`.

I interrupt this background experiment Pause_Test with an experiment that pulses a ttl once.

```python
from artiq.experiment import *

class Handover_Test(EnvExperiment):
    
    def build(self):
        self.setattr_device("core")
        self.setattr_device("ttl13")

    @kernel      
    def run(self):
        self.ttl13.pulse(100*ms)
        delay(100*ms)
```

Triggering on `ttl13` on the scope, with `ttl13` green, `ttl14` yellow and `ttl_bdd` blue, I get the following waveform,

![](https://s31.postimg.org/g5pp0s8rv/Poster_v6.png)

The seamless handover seems to occur perfectly between ttl13 and ttl14. However, the idle kernel turns on after the background experiment terminates. Is there a way to prevent that? If I remove `self.core.comm.close()`, the idle kernel doesn't turn on when 'ttl13' pulses, but the background experiment doesn't turn on after that.

**Comment by sbourdeauducq** [comment]
Yes, it's supposed to, as I explained on the mailing list a few weeks ago. Do this: https://github.com/m-labs/artiq/blob/master/artiq/examples/master/idle_kernel.py#L11
