### ISSUE TITLE
Browser crashes if maximised when no pyon file exists

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#524]
Using artiq 2.0.dev+485.gc0d5914 on windows, if you start the browser for the first time and immediately maximise it, it crashes with the following error message,

```
[artiq-dev-master] c:\artiq-dev-master\artiq-magtrap>python -m artiq.frontend.ar
tiq_browser
INFO:browser:artiq.gui.state:State database 'C:\Users\rabi\AppData\Local\m-labs\
artiq\2\artiq_browser.pyon' not found, using defaults
QWidget::repaint: Recursive repaint detected 
```

If you resize it manually first and then maximise, it's fine. Once the pyon file exists maximising seems to be fine. The issue only comes up if you start it for the first time without the pyon file.

**Comment by jordens** [comment]
I can reproduce this. Same version, windows 7, same recipe. Could you try a) reproduce it with a newer version (there were changes related to the log painting)? And then b) could you delete/comment out the `paintEvent()` method (https://github.com/m-labs/artiq/blob/aa1f32a5df4dcf76ad271e804081b683c49895e9/artiq/browser/experiments.py#L419) and see whether this changes anything?

**Comment by r-srinivas** [comment]
I used `2.0.dev py_503+git2099344` and I still see this issue. Commentin out the `paintEvent()` method didn't fix it.

**Comment by jordens** [comment]
Thanks. I'll try to reproduce but it doesn't smell like a deeper Qt bug. Any chance you could get a stack trace using ms visual c++?
@whitequark can you help or do you see something to test?

**Comment by jordens** [comment]
Maybe https://bugreports.qt.io/browse/QTBUG-48823
Could you try your recipe with `python -m artiq.frontend.artiq_browser --browse-root c:\artiq-dev-master\artiq-magtrap c:\artiq-dev-master\artiq-magtrap`?

**Comment by r-srinivas** [comment]
That seems to maximise without any issues.

**Comment by jordens** [comment]
Ok. Sounds like funky icons and that Qt bug then.
@whitequark @sbourdeauducq do we plan to land qt 5.6.1?

**Comment by jordens** [comment]
depends on #261 (in all likelihood)
we could try finding a work around but since this usually only happens once there would be little benefit.

**Comment by sbourdeauducq** [comment]
Fixed.
