### ISSUE TITLE
"Repeat single value" option in `scannable`

### ISSUE THREAD

**Issue by dtcallcock** [m-labs/artiq#532]
When we are tweaking something manually on the experiment (eg. a mirror mount) we often want to continuously repeat a single experiment, without changing anything else, to see the effect of the tweaking.  In hfGUI this was called a 'dummy' scan.  Currently we do this in artiq by doing a linear scan but making the range so small there is effectively no change in the parameter.  Whilst this generally works fine it is a bit annoying to set up and I think we do this often enough in the lab to merit a single-click implementation.  A couple of possible implementations might be:

- Add a new type of `ScanObject` to `scannable` for 'repeat single value'.  This would have 'value' and 'number of repetitions' arguments.

- Add a 'repetitions' argument to the existing 'No scan' `ScanObject`.  The problem with this is that when you go to scan another variable you will have to remember to set this back to '1' to avoid doing a 2D scan.

**Comment by jordens** [comment]
+1 for the latter

**Comment by sbourdeauducq** [comment]
Agreed.

The "disable other scans" button (in 2.x) can also set the repeat count to one.

**Comment by jordens** [comment]
You can always add as many dummy variables as you want. How you handle them is your choice. But that's a use case and not a distinct feature, right?
If you want to plot against indices, just generate an indices dataset.
If you want the applet to magically ignore the abscissa values and use indices, you might have to change the applet code.

**Comment by sbourdeauducq** [comment]
The experiment can also detect when this feature is used (the code would be something like ``isinstance(scan, NoScan) and scan.repeat > 1``) and generate the corresponding datasets for applet consumption.

**Comment by sbourdeauducq** [comment]
@r-srinivas 7efd9905412cd96db9744abcce06c1233b3b43df was necessary to avoid unnecessary typing and keep backwards compatibility. You could have found the problem by running (or just scanning) the arguments_demo example.

**Comment by r-srinivas** [comment]
Okay. I had actually thought about it but the other scan options didn't have default values, but I suppose they don't have arguments like repetitions that are not as necessary.

**Comment by r-srinivas** [comment]
Could this be added to 2.0 or would it be considered a new feature that you don't want to introduce in a version?

**Comment by jordens** [comment]
i am ok with making an exception

**Comment by dhslichter** [comment]
@sbourdeauducq, thoughts?  This would be very nice to have in 2.0, and AFAICT shouldn't break back compatibility with existing code.

**Comment by sbourdeauducq** [comment]
Ok.
