### ISSUE TITLE
Asynchronous RPC from the core device

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#551]
This addition allows RPCs from the core device which do not require a return value from the master/worker to return immediately, without incurring the cost of a network round trip plus latencies associated with the master/worker processes. This frees the core device kernel CPU to process further code, reducing experimental dead times.
- [x] Core device RPCs for set_dataset() and mutate_dataset() shall be implemented as background RPCs.
- [x] Multiple background RPC requests may be queued in a FIFO manner. The runtime shall make data copies as appropriate to place in this queue to ensure that later mutations of the RPC arguments on the core device do not impact the RPC.
- [x] Regular (non background) RPCs shall wait for the background FIFO to empty before proceeding.
- [x] Mechanisms for handshaking between the kernel CPU and comms CPU shall be devised to enable data to be added to the FIFO queue and for the kernel CPU to return, even when the comms CPU is busy.
- [x] All such background RPCs shall be marked with a special Python decorator.

**Comment by sbourdeauducq** [comment]
Let's call those "background RPCs" instead.

**Comment by whitequark** [comment]
Needs testing:
  * interleaving of async and sync RPCs
  * exceptions in async RPCs

**Comment by whitequark** [comment]
All done, tested, and documented.
