### ISSUE TITLE
VADJ rail in doc

### ISSUE THREAD

**Issue by dhslichter** [m-labs/artiq#554]
We should probably specify that one needs to change the KC705 VADJ rail using PMBus in the "common problems" listing in the core_device.rst documentation file, instead of/in addition to having it where it currently is at the bottom of the QC2 documentation.

**Comment by jordens** [comment]
That seems to imply that the QC2 documentation is usually not read or ignored when setting up a QC2 system. Is that the case?

**Comment by sbourdeauducq** [comment]
Doesn't the "clock" design also require the same PMBus programming by the way? The doc currently does not say that.

**Comment by dhslichter** [comment]
Yes, the point is that this is required for CLOCK and QC2, not just QC2, and so it should be mentioned in a place where people doing CLOCK also will look for it.  I don't know of anyone using KC705/QC1 currently -- I think we should move to deprecate it pending a check that nobody is using that combination.

**Comment by sbourdeauducq** [comment]
What is the Penning lab using?

**Comment by dhslichter** [comment]
HFGUI :P

**Comment by dhslichter** [comment]
Penning confirms they are not using KC705/QC1 anymore. @jboulder are you using KC705/QC1 in any of your experiments these days?

**Comment by sbourdeauducq** [comment]
What's their excuse?

**Comment by dtcallcock** [comment]
They are too busy writing rubbish like this: http://science.sciencemag.org/content/352/6291/1297

**Comment by jbqubit** [comment]
I missed that this was directed at me. I'm not using KC705/QC1. If Penning
moves to use ARTIQ I'd guess it will be after Sayma-Metlino become
available. Justin, thoughts? -Joe

-------
Joe Britton
Sensors and Electron Devices
Army Research Lab
2800 Powder Mill Rd
Adelphi, MD 20783
301-394-3130
joseph.w.britton5.civ@mail.mil

**Comment by dhslichter** [comment]
Justin has confirmed they are not using KC705/QC1, so it should be removed from the CI.

**Comment by justboh** [comment]
For completeness, I will confirm we have no plans for QC1, and are setting up to use QC2 when we make the switch.

**Comment by sbourdeauducq** [comment]
Do we drop AD9858 support as well or is someone using it (or planning to)?

**Comment by sbourdeauducq** [comment]
That being said, if you want to give ARTIQ QC1 a quick test, it should work quite easily. Many of the first tests were done on it.

**Comment by dhslichter** [comment]
I don't know of anyone planning to use AD9858.  That said, I don't think it is necessary to remove it from ARTIQ in case someone changes their mind.  It just won't be instantiated in any of the currently-compiled bitstreams.
