### ISSUE TITLE
process termination in controller manager is broken

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#56]
This line raises an exception: 
https://github.com/m-labs/artiq/blob/master/artiq/frontend/artiq_ctlmgr.py#L69 
as it ends up doing https://github.com/m-labs/artiq/blob/master/artiq/tools.py#L98  but the process is created with stdout=None

**Comment by fallen** [comment]
Merging this branch would fix this bug: https://github.com/fallen/artiq/tree/ping_controllers
Does it seem clean enough for merging?
