### ISSUE TITLE
support kintex ultrascale

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#563]
- [x] OpenOCD support for Kintex Ultrascale
- [x] Dual flash support
- [x] JESD204 for Kintex Ultrascale (GTH)
- [ ] JESD204B SC1 synchronization and group-delay/latency alignment
- [ ] port of DRTIO to KintexUltrascale #562 
- [x] Kintex Ultrascale DDR3
- [ ] High-resolution IOSERDES TTLs for Kintex Ultrascale

**Comment by jordens** [comment]
Funded by UMD except the IOSERDES port.

**Comment by jbqubit** [comment]
Please also include JESD204B Subclass 1 in the list.

**Comment by sbourdeauducq** [comment]
It's already there, 4th item.

**Comment by sbourdeauducq** [comment]
IOSERDES is also funded now (Joe/ARL).

**Comment by sbourdeauducq** [comment]
Let's break the remaining items into separate issues.

**Comment by sbourdeauducq** [comment]
#794 #793 #792
