### ISSUE TITLE
misoc "automatically generated csr" changes breaks artiq release-2

### ISSUE THREAD

**Issue by jasonamini** [m-labs/artiq#565]
Artiq release-2 bitfile creation with misoc master:
_>> python3.5 -m artiq.gateware.targets.kc705 -H nist_clock --toolchain vivado_
_..._
  _File "/home/qatest/artiq/artiq-dev/artiq/artiq/gateware/targets/kc705.py", line 115, in _NIST_Ions
    csr_map.update(MiniSoC.csr_map)
AttributeError: type object 'MiniSoC' has no attribute 'csr_map'_

Misoc commit 26ecb6a8331571fe4c33bbf06738e50f5dbd3c2c is OK while the following commit 6af3e1b456876aaab85d4b40c7a2746e42d34d1d to "automatically generate csr and interrupt maps" is not.

**Comment by sbourdeauducq** [comment]
Yes, use misoc 0.3 (from the conda main channel) with ARTIQ 2.0.
