### ISSUE TITLE
moninj OE stuck at 0

### ISSUE THREAD

**Issue by whitequark** [m-labs/artiq#574]
Setting OE=1 doesn't seem to do anything (in particular OE remains at 0 as read by monitor).

**Comment by sbourdeauducq** [comment]
@whitequark any progress on this?

**Comment by whitequark** [comment]
No. I have no idea where even to start.

**Comment by cjbe** [comment]
I think I have seen this issue too: The injection monitoring does not work until rtio_init() has been called - this is only observable if one does not have a startup kernel that calls core.reset().

**Comment by cjbe** [comment]
Sure - this is just a gotcha when you are setting new hardware up: If you flash the board, and the first thing you try to do is toggle a TTL using the override it does not work.

**Comment by sbourdeauducq** [comment]
@whitequark did you see a problem specifically on OE, or was moninj simply not responding at all (until there was at least one core reset)?

**Comment by whitequark** [comment]
@sbourdeauducq it was definitely responding because I've seen some other pins at 1

**Comment by sbourdeauducq** [comment]
Works fine as per my test. Sending injection commands on OE does cause the device to send OE change notifications on a monitored channel. @whitequark maybe you used output-only (TTLOut) channels? Those do not have a OE probe or injector.

**Comment by whitequark** [comment]
> maybe you used output-only (TTLOut) channels? Those do not have a OE probe or injector.

I've definitely not used output-only channels. Not only I specifically looked them up in ddb but for good measure I verified every single one anyway.
