### ISSUE TITLE
default arguments in scheduler.submit()

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#577]
* from experiment: values for the current run
* from RPC: usual values (pipeline_name="main", priority=1, etc.)

**Comment by r-srinivas** [comment]
Would it be possible to have the option of getting the default values from the GUI for that particular experiment?

**Comment by sbourdeauducq** [comment]
What if there are multiple GUI connected with different values?

**Comment by r-srinivas** [comment]
That's true. We can live without that but if we could use `self.scheduler.submit` with experiments without specifying all the defaults that would be a big help already.
