### ISSUE TITLE
support submitting experiments by content

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#579]
Would be limited to single-module experiments.
Maybe with a small text editor in the dashboard for quick tests?

**Comment by jordens** [comment]
Ack. As a workaround, e.g. the IPython notebook example is just writing out into files on the master. But that has obvious problems.

**Comment by sbourdeauducq** [comment]
Funded by Duke for Urukul "injection".
Done.
Text editor would be part of the "cells" GUI revamp.
