### ISSUE TITLE
drtio: enable Si5324 freerun mode and automatic clock switching

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#589]
https://github.com/m-labs/artiq_drtio/commit/e7dbed3b02920ea4f17ba7a768e0864b5e7a0d23#diff-bf501806640f38bbd7d094a03ee4d0d2R15

**Comment by sbourdeauducq** [comment]
I need this to begin DRTIO hardware tests.

**Comment by whitequark** [comment]
Done.

**Comment by sbourdeauducq** [comment]
Where did you put the code?
