### ISSUE TITLE
make sure ARTIQ 3.0 depends on pythonparser > 0.0_py6

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#600]
The current artiq 3.0.dev crashes with pythonparser 0.0-py_5 and works with 0.0-py_6, but updating artiq won't automatically update pythonparser.

**Comment by whitequark** [comment]
Unfortunately a greater-than dependency on build number is inexpressible in conda, but pythonparser is rarely updated, so for now I'll specify a dependency on a specific build. Eventually pythonparser should gain a release.

**Comment by sbourdeauducq** [comment]
Why not make that release now and have 3.0/master depend on it?
