### ISSUE TITLE
document ARTIQ_UNPARSE

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#61]
add to documentation

§ Compilation toolchain introspection. Here's how to see what the compiler is doing. Use this when submitting bug reports about poorly optimized code. 
```bash
$ ARTIQ_UNPARSE=final artiq_run repository/ext_trig.py

**Comment by whitequark** [comment]
There's no more `ARTIQ_UNPARSE`, and for the time being the easiest way to debug poorly optimized code is to send the source.

There are `ARTIQ_DUMP_IR` and `ARTIQ_DUMP_LLVM`, but these would be of little comprehension to the end-user, so I don't think it is valuable to list those.

In any case, let's see what the real-world performance problems with the new compiler are and how they can be better solved, to see what would be the most suitable alternative to `ARTIQ_UNPARSE`.
