### ISSUE TITLE
super() on core device

### ISSUE THREAD

**Issue by dleibrandt** [m-labs/artiq#617]
I'm running artiq 2.0 and I get an error when I try to use 'super()' on the core device.  I assume this is because it has not been implemented.  How difficult would it be to add?

**Comment by whitequark** [comment]
Depends. Can you show the code you would like to run?

**Comment by dleibrandt** [comment]
What I was trying to do is basically this:
```
from artiq.experiment import *

class C():
    @kernel
    def run(self):
        print("C.run")

class B():
    pass

class A(B, C, EnvExperiment):
    def build(self):
        self.setattr_device("core")
    
    @kernel
    def run(self):
        super().run()
```

**Comment by sbourdeauducq** [comment]
Transferred to NAC3
