### ISSUE TITLE
DRTIO switch support for Sayma RTM

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#619]
see mailing list thread:
https://ssl.serverraum.org/lists-archive/artiq/2016-November/001040.html

**Comment by sbourdeauducq** [comment]
For supporting the Sinara hardware, switches should be capable of data rate conversion, as the AMC-RTM link has lower bandwidth than the backplane links.

**Comment by jbqubit** [comment]
@sbourdeauducq Do you have enough information to propose an implementation and quote this feature?

**Comment by sbourdeauducq** [comment]
Funded by ARL for the purposes of supporting the RTM FPGA.

**Comment by hartytp** [comment]
@sbourdeauducq am I right in thinking that this is no longer needed, since we will use transceivers for RTM DRTIO on v2.0 hw? In which case, does that free up some funding for other purposes?

**Comment by sbourdeauducq** [comment]
@hartytp DRTIO switching is partly funded through your contract and through the Sayma contract (this Issue is about switching support, not transceiver-related issues).
Indeed, we don't need rate conversion support anymore; though that's not particularly hard to do upper in the stack with the current DRTIO switching architecture, the Ultrascale IOSERDES turned out to be a major source of problems (TPWS+BUFGCE_DIV).

**Comment by hartytp** [comment]
ack

So, if we scrap rate conversion then this item is complete and the issue can be closed?

**Comment by sbourdeauducq** [comment]
Yes, it'll be regular DRTIO switching on the RTM.
