### ISSUE TITLE
Increase RTIO FIFO depths in class NIST_CLOCK

### ISSUE THREAD

**Issue by dleibrandt** [m-labs/artiq#623]
I've had to increase the RTIO FIFO depths in the NIST_CLOCK gateware in order to get my sideband cooling pulse sequence to run without underflow errors.  Could you please incorporate the changes in the diff below so that I don't have to continue compiling my own gateware in the future?  (I'm not aware of anyone else using the NIST_CLOCK gateware, so I don't think this would adversely affect anyone.  If I'm wrong, please comment here.)

[nist_clock_fifo_patch.txt](https://github.com/m-labs/artiq/files/600545/nist_clock_fifo_patch.txt)

For reference, even with my increased FIFO depths the block ram usage is only 47%.

As an aside, I know that @r-srinivas is doing the same thing for NIST_QC2 (see #530), so it might be convenient to him to change those FIFO depths also.

**Comment by sbourdeauducq** [comment]
What is that sideband cooling pulse sequence that causes trouble?

**Comment by sbourdeauducq** [comment]
@dleibrandt your patch fails timing.

**Comment by sbourdeauducq** [comment]
...on master, but passes on release-2.

**Comment by sbourdeauducq** [comment]
So this will stay in release-2 and be available with 2.1 unless we have problems with it again, and will not be in 3.x.

**Comment by r-srinivas** [comment]
@sbourdeauducq any idea why the timing fails?

**Comment by dleibrandt** [comment]
@sbourdeauducq, the sideband cooling pulse sequence is up to 1000 pulses.  The pulse durations change during the sequence, but the majority are roughly 1 us.  Each pulse consists of turning a ttl on and off and setting a dds frequency and amplitude twice (once at the start and once at the end of the pulse; we do this so that we can keep the AOM on but detune the light from the atomic resonance, thus keeping the temperature of the AOM constant).

I suspect that my underflow problem will be solved once DMA is finished.  Will DMA be included in 3.x, or will it come later?

**Comment by sbourdeauducq** [comment]
DMA should be in 3.0.

**Comment by sbourdeauducq** [comment]
Support for AD9914 DDS phase modes in DMA sequences is currently unclear though.

**Comment by r-srinivas** [comment]
@sbourdeauducq I was thinking of submitting a patch for the nist_qc2 gateware as well. Why does the timing fail in 3.0 exactly?

**Comment by sbourdeauducq** [comment]
> Why does the timing fail in 3.0 exactly?

Failing timing is a regular, semi-random and annoying problem with FPGA tools. I didn't keep the Vivado timing report, you can run the synthesis again to get it and see where the critical paths are in the design.
