### ISSUE TITLE
disable_applet not working

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#633]
(From #630)
@r-srinivas Please a ``print`` into the dashboard (here: https://github.com/m-labs/artiq/blob/master/artiq/dashboard/applets_ccb.py#L190) to check that it correctly receives the applet deletion request.

**Comment by sbourdeauducq** [comment]
Or better, dump all calls to ``ccb_notify``, so you can see the applet creation request as well which confirms you have modified the file correctly.

**Comment by r-srinivas** [comment]
I'm using artiq `3.0.dev py_252+git5b7e068` so it should have the fix for #629, and indeed it can create new groups now.

Adding `print(service)` to `ccb_notify`, on the dashboard I see,

```
create_applet
disable_applet
```
So it looks like it's getting the command. Just to clarify, `create_applet` doesn't enable the applet. While the `code_applet.py` is running, I check it to see the countdown. Then at the end it should disable it and the applet should disappear, right?

**Comment by sbourdeauducq** [comment]
Stupid question, does right click -> global/group CCB policy -> Create and enable applets fix the problem?

**Comment by sbourdeauducq** [comment]
> it should disable it and the applet should disappear, right?

Yes.

**Comment by r-srinivas** [comment]
>Stupid question, does right click -> global/group CCB policy -> Create and enable applets fix the problem?

Looks like that works, plus the #630 error message. Modifying the global CCB policy doesn't change the command entry for a particular group though. 

Is having the create+enable on required for disabling to work how it's intended to work?

**Comment by sbourdeauducq** [comment]
That's how it's intended to work. "Create" could be changed to a term that means "mess with the user's windows", if we can find a good one.

**Comment by r-srinivas** [comment]
Okay, thanks. Maybe modify? User customisable?

**Comment by sbourdeauducq** [comment]
It is user customizable already: ARTIQ is open source, you can patch your local installation :)
And this is a terrible idea. The purpose of a better name is to teach first-time users, asking them to customize it right away actually makes things worse.
I went for "enable/disable". "Modify" is too vague, as it can also mean that the applet list is being modified.

**Comment by r-srinivas** [comment]
I should clarify that I meant user customisable as a name, as in the user can customise how the applets appear. Enable/disable seems fine, though slightly confusing with also being able to enable/disable applets, but is to enable/disable ccb? Maybe something along the lines of experiment controlled as more descriptive?
