### ISSUE TITLE
startup_kernels hang

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#641]
In current master (even trivial) startup kernels hang, AFAICT after completing the `run()`.
Tested with the phaser target at least from 708c25b to 15b48be.

**Comment by sbourdeauducq** [comment]
This is not specific to startup kernels. The kernel CPU crashes in ``attribute_writeback`` and this happens with any kernel compiled with ``artiq_compile``. You can reproduce the problem with ``artiq_run some_kernel.elf``.

**Comment by jordens** [comment]
Thanks.
