### ISSUE TITLE
make runtime management interface independent from kernel interface

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#649]
As soon as the network is up, we want to be able to access the flash storage and the log from the network. This independently of a startup kernel running/crashing, the RTIO clock working, or anything else.

The only reason it was coupled in the C runtime is because reusing the session code was somewhat tricky, but I believe Rust should make this easier.

**Comment by whitequark** [comment]
OK. The only reason I implemented it like that in Rust is for feature parity.
