### ISSUE TITLE
unittest soft-FP/DDS

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#661]
The existing DDS pulse rate test is only supposed to test the performance of emission speed. Since we use soft-FP, many realistic use scenarios will have soft-FP latency dominate emission latency. To optimize them, we need a benchmark as a guide.

@r-srinivas I remember you ran into speed problems with sideband cooling. Could you give us the relevant part of your code?

(duplicate: #660)

**Comment by sbourdeauducq** [comment]
The current DDS test was written to measure the speed of the C routines. This is why there is no sweep or other computations.

**Comment by r-srinivas** [comment]
bermudez_cooling() in cooling.py requires about 600 - 1000 us of slack to
run. I think these files would be all you need. I think it's not the most
demanding sideband cooling sequence because some of our pi times for those
modes are pretty long.

**Comment by jordens** [comment]
addressed by #1777
