### ISSUE TITLE
smoltcp checklist

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#662]
- [x] gateways
  - [x] tcp keepalive

**Comment by whitequark** [comment]
smoltcp populates the ARP table from every incoming IP packet (such as the TCP SYN), so it never actually needs to resolve a MAC if all you're doing is listening. Therefore it has no special support for gateways.

**Comment by jordens** [comment]
@whitequark you have keep-alive in smoltcp. does it still need wiring in artiq?

**Comment by whitequark** [comment]
Yes.

**Comment by whitequark** [comment]
Timeouts and keepalive turned on, and tested by adding a `-A OUTPUT -d $CORE_DEVICE -j DROP` rule to iptables.
