### ISSUE TITLE
PDQ3

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#664]
Support for new NIST PDQ features will be part of ARTIQ 3.0.
https://github.com/m-labs/pdq2/milestone/1

**Comment by jordens** [comment]
* [x] read and write working in testbenches and hardware (kc705 RTIO-SPI)
* [x] register access implemented, tested in hardware
* [x] memory access implemented, tested in hardware
* [x] configuration (config register, frame select, checksum) layer implemented, tested
* [x] memory serialization implemented, documented, tested
* [ ] unify/merge SAWG spline point code with PDQ API
* [ ] quick-and-simple configuration API
* [ ] merge wavesynth API with SAWG API
* [ ] documentation
