### ISSUE TITLE
Problem with Pipistrello board

### ISSUE THREAD

**Issue by trxw** [m-labs/artiq#674]
Hi everyone, 
After installation via Conda I was able to flash Pipistrello board but I keep getting the following error when running led.py (copied from artiq manual) in artiq-main directory. How could I solve this problem?

![errormessage](https://cloud.githubusercontent.com/assets/4351036/23334620/7c07d17e-fb70-11e6-9374-08062ccb2fce.png)

thanks

**Comment by sbourdeauducq** [comment]
Did you establish the PPP link?

**Comment by trxw** [comment]
Hi Sébastien, 
I have added two files to the ~/miniconda3/envs/artiq-main directory, one is device_db.pyon and another is led.py from the manual. Here's the command that I run on one tab while I run   source activate artiq-main  while in the artiq-main directory:

sudo pppd /dev/ttyUSB1 115200 noauth nodetach local nocrtscts novj 10.0.0.1:10.0.0.2

which I am guessing is PPP that you are referring to. After which I run the command artiq_run on file led.py  
However I still get the same error.
thanks again for your help.

**Comment by sbourdeauducq** [comment]
The device_db.pyon and led.py files can be put in any folder, they do not need to be in the conda environment folder.

Is the PPP connection succeeding? Have you edited device_db.pyon to set the IP address of the board (10.0.0.2)?

**Comment by trxw** [comment]
Thanks for your rapid answer. Yes, I set one to 10.0.0.2, and it didn't work. I also set all of them to the same address and got exact same error as before.

![1](https://cloud.githubusercontent.com/assets/4351036/23391039/f9cb9ca0-fd3f-11e6-9bd9-a2ee64e712c2.png)

**Comment by sbourdeauducq** [comment]
You are editing the wrong entries, you should only edit the ``comm`` entry. Can you ping the board?

**Comment by trxw** [comment]
Hi Sébastien,
Thanks for your help. We got it work but I also had to replace the device_db.pyon file from miniconda3 with the respective file from conda installation, or else it wouldn't work. 
![22](https://cloud.githubusercontent.com/assets/4351036/23584009/860d0eb6-0122-11e7-93aa-a703db9f8e03.png)

**Comment by sbourdeauducq** [comment]
> I also had to replace the device_db.pyon file from miniconda3 with the respective file from conda installation

What do you mean?

**Comment by sbourdeauducq** [comment]
Miniconda3 itself doesn't come with a device_db.pyon.

**Comment by trxw** [comment]
I see what you're saying. I just assumed that I need to put that file in the directory where I run the script.
