### ISSUE TITLE
Link Scannable LinearScan and RandomScan ranges

### ISSUE THREAD

**Issue by cjbe** [m-labs/artiq#679]
It would be useful for the LinearScan and RandomScan min/max/nsteps to be linked, so that when one changes from LinearScan to RandomScan the scan parameters are copied across.

This seems to match typical use cases better than the current behavior (RandomScan and LinearScan parameters independent, so that if you set up your scan nicely, then want to change mode, you have to set the parameters again).

**Comment by sbourdeauducq** [comment]
We can rename the "Linear" scan to a "Range" scan, add a "randomize" checkbox, and remove the "Random" scan. The user experience is the same IMO and it is easier to program.

**Comment by cjbe** [comment]
Agreed - this is clearly the right solution
