### ISSUE TITLE
Support RPCs from core device with constant strings as arguments

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#68]
Even though the compiler may not support strings, it is desirable to support RPC calls with constant strings in the arguments, so that the upcoming parameter database API can be used directly from the core device (e.g. ``self.set_parameter("parameter_name", value)``).

This can be implemented in the current transforms system by replacing RPC calls containing string arguments with closures that do not take those arguments and inject the strings.

**Comment by jboulder** [comment]
Due to #68 the example photon_histogram.py does not work. Please update with example code of how to use the closure trick. This is too cryptic for me to implement: "replacing RPC calls containing string arguments with closures that do not take those arguments and inject the strings."

**Comment by sbourdeauducq** [comment]
https://github.com/m-labs/artiq/commit/820ff2da2c69a280f9bb3a031fa10cefc5c28da8 (already referenced above) is an example of how to work around the problem.

**Comment by sbourdeauducq** [comment]
And the "closure trick" as you call it is one way to improve the compiler so that such a work around is not necessary.

**Comment by whitequark** [comment]
Done in new-py2llvm by passing strings over the wire directly.

**Comment by jboulder** [comment]
Here's an example of this work around. 
```python
from artiq import *

def print_underflow():
    print("RTIO underflow occured")

class WhatsWrongHere(EnvExperiment):
    """Should be able to set_result from @kernel decorated method. But this
    is broken with the current compiler. Here's the work around 
    until the new compiler is ready. 
    """

    def set_testval(self, val):
        self.set_result("testval", val, store=False, realtime=True)

    def build(self):
        self.attr_device("core")

    @kernel
    def run(self):
        #self.set_result("test", 0, store=False, realtime=True)
        self.set_testval(0)
```

**Comment by whitequark** [comment]
Closing since new compiler was merged.
