### ISSUE TITLE
user-friendly API for Allaki RF switch

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#689]
Can we do better than exposing a simple TTL? Based on how the NIST DDS hardware is used, it seems not.

**Comment by dhslichter** [comment]
I would argue this is all one wants/needs for this.  

The most obvious other way to do this would be to just make the switch a part of the SAWG driver, and turn the switch on when the SAWG is playing and off when it is not playing.  While this is OK for some applications (essentially you are "double bagging" the output from the SAWG to reduce leakage in the off state), in others you will want to have the switch open and/or close at times other than the start or end of a SAWG waveform (e.g. in case you worry about transient behavior of the switch, you'd rather turn it on early so this does not affect the rising edge of your pulse).
