### ISSUE TITLE
Method to set default experiment priority / log level / pipeline

### ISSUE THREAD

**Issue by cjbe** [m-labs/artiq#692]
It would be really useful to have a method that can be called from build that sets the default priority for the experiment. It would potentially also be useful to be able to set a default log level and pipeline. This default would be used when the experiment is first opened in a GUI, or used if the user clicks "recompute all arguments".

An example where this is useful is for servo experiments. One often has 3 or so servo experiments that interrupt the running experiment to tweak parameters, with the servos each running at different priorities so they interrupt each other appropriately. At the moment the user needs to set these experiments to have the correct priority in each instance of the GUI they use - this is fragile.

**Comment by sbourdeauducq** [comment]
@cjbe Would Oxford fund this?

**Comment by cjbe** [comment]
@sbourdeauducq it might be possible to tack this on to a future contract, else one of us will implement it.
