### ISSUE TITLE
Installing release 2 from source documentation

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#695]
Could the git clone instructions here,

```
Download and install ARTIQ:

$ cd ~/artiq-dev
$ git clone --recursive https://github.com/m-labs/artiq
$ cd artiq
$ python3.5 setup.py develop --user
```
be updated to 

```
$ git clone --recursive https://github.com/m-labs/artiq -b release-2
```
?

It seems to install the master branch by default otherwise.

**Comment by sbourdeauducq** [comment]
No, because this creates additional maintainance at every major release, and will be forgotten. But we can add a note telling developers that they should be careful which branch they are on.
