### ISSUE TITLE
Using SPI Protocol with Pipistrello

### ISSUE THREAD

**Issue by StanleyEDavidsdavid30** [m-labs/artiq#697]
Hello!

I am able to make the Pipistrello board send different kinds of square pulses to different pins. I can verify this operation using a logic analyzer. I will eventually need to be able to connect the Pipistrello board with another device which uses the SPI protocol. I know that there is an SPImaster class within ARTIQ, but I am not completely sure how to begin using this class.

Can you give any suggestions on how to proceed with this? 

Thanks!

**Comment by jordens** [comment]
The standard gateware for Pipistrello has one SPI bus: https://github.com/m-labs/artiq/blob/master/artiq/gateware/targets/pipistrello.py#L205 If you need more, you'll have to build your own.
Determine the RTIO channel number by counting channels (might be 20). And write a corresponding device_db.pyon entry. Then request the device as usual.
