### ISSUE TITLE
m-labs.hk/artiq/manual not up to date

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#71]
For example EnvExperiment is not in it. This came to my attention when a prospective user from U. Wisconsin emailed me asking why the documentation is not up to date. Automated updates would be good.

**Comment by sbourdeauducq** [comment]
fixed

**Comment by jboulder** [comment]
Manual is not up to date again.

**Comment by whitequark** [comment]
Yes, I'm working on that SFTP upload. It should be done today.
