### ISSUE TITLE
iterate over binary data

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#714]
To transfer binary data via SPI, it would be useful to be able to iterate over a `bytes()` object in ARTIQ-Python, instead of having to pass 32 bit integer arrays around.

**Comment by jordens** [comment]
maybe `bytearray()` would be better here since it is mutable (reading SPI data).

**Comment by whitequark** [comment]
Why not both.

**Comment by jordens** [comment]
ack. "better" just when prioritizing. the `.extend()` ability of `bytearray()` might make it more problematic again. what i'd like is a fixed size bytes/bytearray where i can set elements.

**Comment by whitequark** [comment]
> the .extend() ability of bytearray() might make it more problematic again

We just skip all such methods already. E.g. mutators of `list`.

**Comment by whitequark** [comment]
done
