### ISSUE TITLE
potentially reduce kernel compile time by replacing InstCombine with InstSimplify

### ISSUE THREAD

**Issue by whitequark** [m-labs/artiq#720]
Idea gleaned from http://lists.llvm.org/pipermail/llvm-dev/2017-April/112026.html.

**Comment by whitequark** [comment]
@sbourdeauducq If this is for contract, then #723 should also be.

**Comment by dnadlinger** [comment]
LLVM performance doesn't currently seem to be the limit in my experiment: https://github.com/m-labs/artiq/issues/1380

**Comment by dnadlinger** [comment]
(NB: This was not to say that optimising the pass pipeline, whether for speed or code quality, isn't something we should keep in mind!)

**Comment by whitequark** [comment]
The pass pipeline needs to be reevaluated again for today's LLVM, since it's been almost three years.
