### ISSUE TITLE
reduce compile time by replacing llvmlite with bindings to LLVM-C

### ISSUE THREAD

**Issue by whitequark** [m-labs/artiq#723]
As discussed elsewhere, there are (I think still unpublished) bindings by Alessandro Di Federico. Since we currently spend up to a half (!) of the time concatenating strings in llvmlite, migrating to the LLVM-C API could potentially result in significant speedup.

**Comment by jordens** [comment]
Note to self. New bindings are MIT. Involves moving to llvmlite 4.0.

**Comment by whitequark** [comment]
Bindings: https://github.com/revng/llvmcpy

**Comment by whitequark** [comment]
Or more precisely it is an LLVM binding generator, not LLVM bindings. This also greatly reduces (ideally to zero) the amount of work binding-side that needs to be done when upgrading LLVM in the future. No more hacking around llvmlite limitations \o/

**Comment by whitequark** [comment]
LLVM-C binding just [gained DIBuilder support](https://reviews.llvm.org/rL317135), which means we will retain the debug information when migrating to LLVM-C.

**Comment by sbourdeauducq** [comment]
What kind of speed improvement can we expect from this, exactly?

**Comment by whitequark** [comment]
You can run the profiler, then cut the time spent doing anything LLVM-related in half.

**Comment by sbourdeauducq** [comment]
llvmlite isn't the biggest problem (https://github.com/m-labs/artiq/issues/1380) and is not used anymore in NAC3 anyway.
