### ISSUE TITLE
artiq_gui TTL override GUI broken

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#73]
In artiq_gui.
On TTL pane
Right click on pmt0 IN...  "Force 0" doesn't update status to "0" in gui
Right click on ttl0 OUT...  "Force 1" doesn't update status to "1" in gui

**Comment by sbourdeauducq** [comment]
This means that you are probably not talking to the core device. Can you ping the core device from the machine running the GUI? Can you post a wireshark trace?

**Comment by sbourdeauducq** [comment]
Problem turned out to be that the clock cable to the core device was unplugged.
