### ISSUE TITLE
Use the llvm linker

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#733]
From #407

Now that we're on LLVM 3.8 we can use the LLVM linker, and rip out a whole bunch of cruft at the same time as making it all faster.

That will also:

* remove the binutils dependency;
* make runtime smaller as we can make use of LTO;
* improve error messages as LLVM's symbolizer works better than GNU's. (this is not strictly related to the linker but it's an adjacent API that would be convenient to make use of at the same time.)

**Comment by whitequark** [comment]
Doesn't have the C API yet. However we can write one and submit it upstream, I know upstream will welcome it.

**Comment by whitequark** [comment]
LLD is production-ready since LLVM 7.0. https://lists.llvm.org/pipermail/llvm-announce/2018-September/000080.html

**Comment by dnadlinger** [comment]
This is definitely an interesting direction (shipping linker plugins for LTO is a bit of a headache otherwise), but, with sample size 1, doesn't currently seem to be critical for speed: https://github.com/m-labs/artiq/issues/1380

**Comment by sbourdeauducq** [comment]
Done on all platforms since RISC-V.
