### ISSUE TITLE
versioneer outputs inconsistent git commit hash lengths

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#739]
When the buildbot builds the gateware (which embeds ``artiq.__version__``): 8 characters
When installing the conda package and using ``artiq.__version__``: 9 characters
When setuptools is not involved (importing ``artiq`` via ``PYTHONPATH``): 8 characters
See also #738

**Comment by sbourdeauducq** [comment]
For maximum obnoxiousness, the 9-character bug only appears when the conda package is built by the buildbot, when doing a local conda build it has the correct 8 characters.

**Comment by whitequark** [comment]
https://github.com/git/git/commit/e6c587c733b4634030b353f4024794b08bc86892

**Comment by sbourdeauducq** [comment]
Thanks.
