### ISSUE TITLE
Coredevice access to converter SPI busses

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#740]
* On Sayma RTM: ADC/DAC/HMC*...
* On Phaser: DAC, PLL

f3c7a7de3be9a89a14b2d5e5540affd0393d4591

**Comment by sbourdeauducq** [comment]
The files in f3c7a7de3be9a89a14b2d5e5540affd0393d4591, except ``test_ad9154_status.py`` that can be reintroduced as-is, do other manipulations to the JESD core that are a bit annoying to support over DRTIO. What about moving them to firmware? Perhaps those tests could be run at each boot.

**Comment by jordens** [comment]
Running them at Sayma boot is good. Depending on the clocking we might have to delay that though.

**Comment by sbourdeauducq** [comment]
The satellite manager should be capable of bringing up all the clocking by itself.

**Comment by sbourdeauducq** [comment]
Though I remember there was some crash/bug that required a reboot of the device after STAPL or PRBS test had been done. Is that fixed? Cc @enjoy-digital

**Comment by enjoy-digital** [comment]
@sbourdeauducq: that's possible you will need to reconfigure the device ADI chip after the STAPL/PRBS. That's something I can test/fix if needed when I'll be integrating and the core on Sayma.
