### ISSUE TITLE
doc : coredevice method arguments too complex

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#741]
Core drivers reference artic.coredevice.sawg and .spline have unnecessarily complex argument types presented in documentation. For example sawg.config.set_clr().

In email, @jordens says
> That's a feature of the compiler, not of SAWG. Feel free to raise an issue.

and @sbourdeauducq says
>Getting sphinx to use str() instead of repr() on type annotations should fix this problem.
```
>>> str(TInt32)
'numpy.int32'
>>> repr(TInt32)
"artiq.compiler.types.TMono('int', OrderedDict([('width', artiq.compiler.types.TValue(32))]))"
```

**Comment by sbourdeauducq** [comment]
https://github.com/sphinx-doc/sphinx/issues/3857
I have tested that the proposed change in ``format_annotation()`` does result in types being nicely printed.

**Comment by jordens** [comment]
We could also just overload repr.

**Comment by sbourdeauducq** [comment]
ARTIQ does the right thing in returning an ``eval()``-parseable string in ``repr()``.

**Comment by whitequark** [comment]
@jordens It's used when debugging, because the user-readable representation can hide some details that may make inference fail. Of course that is not visible from source code.

**Comment by dnadlinger** [comment]
This issue is back after a refactoring in Sphinx; the repr() calls are now in https://github.com/sphinx-doc/sphinx/blob/7faeb793e2e16cde4e5759443fb7f84efddcd9ea/sphinx/util/inspect.py.

**Comment by dnadlinger** [comment]
(Testing patch.)

**Comment by sbourdeauducq** [comment]
We can also use an actual (not monkey) patch on Hydra, the advantage is it'll likely show clearly when it breaks. But users of unpatched sphinx will have the issue.

**Comment by sbourdeauducq** [comment]
It broke again.
