### ISSUE TITLE
run JESD204 PRBS and STAPL tests on firmware startup

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#758]
See f3c7a7de3be9a89a14b2d5e5540affd0393d4591 for the old code.
Discussion started in #740

**Comment by sbourdeauducq** [comment]
@enjoy-digital how to do that?

**Comment by enjoy-digital** [comment]
@sbourdeauducq: here is what i started for STATUS and PRBS:
https://github.com/enjoy-digital/artiq/commit/1c41f53cce3a3d659b91857dd1749a89f645c2c2
https://github.com/enjoy-digital/artiq/commit/14a2d60cf50aa37d3c369a8da540c425a7148d35
PRBS was not working but it should be easy to get it working.
I haven't implemented STAPL but procedure is still the same.

**Comment by sbourdeauducq** [comment]
I think we shouldn't need STAPL - the purpose of this is to test the board's integrity, and PRBS should be enough, correct?

**Comment by enjoy-digital** [comment]
@sbourdeauducq: yes for board's integrity this enough. (STAPL was useful to validate the core).
I'll take care of getting PRBS working in the firmware while doing others JESD related things.

**Comment by sbourdeauducq** [comment]
https://github.com/m-labs/artiq/commit/07f4e2e35a4f7e007383a230ea4356989f1c9c96
