### ISSUE TITLE
sawg: automatically serialize events to config channel

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#765]
In #762 @jordens points to a bug.

> And you are submitting two events to the config channel at the same time. One gets dropped and then you are only setting one limit. Add some delay before for the second limit. I'll force that in the next commits.

**Comment by jordens** [comment]
Please stop the noise.

**Comment by jbqubit** [comment]
This bug persists in 3.0.dev+1207.g5b26e5de. Second call to config channel is silently dropped without delay.

```
            # set clipping amplitude
            self.sawg1.config.set_out_max(0.5)
            #delay(1*us)
            self.sawg1.config.set_out_min(-0.5)
```

**Comment by jordens** [comment]
You do get a collision error in the core log.

**Comment by whitequark** [comment]
Related to #691?

**Comment by jordens** [comment]
Yes.

**Comment by jbqubit** [comment]
> You do get a collision error in the core log.

Configuration that doesn't advance the timeline should not cause a collision error. 

```
        # no collision errors for these sawg commands
        self.sawg0.amplitude1.set(2*a0)
        self.sawg0.frequency1.set(f0)
        self.sawg1.amplitude1.set(a0)
        self.sawg1.frequency1.set(f0)
        self.sawg1.amplitude2.set(a0)
        self.sawg1.frequency2.set(f0)

        # collision error
        self.sawg1.config.set_duc_max(0.5)
        self.sawg1.config.set_duc_min(-0.5)
```

**Comment by jordens** [comment]
No. Having two events at the same time for the config channel is almost always a mistake that should become visible. There should not be silent replacement. For the other channels it is reasonable to replace in that case.

**Comment by jbqubit** [comment]
> Add some delay before for the second limit.  I'll force that in the next commits.

You've already agreed to add a delay that avoids the collision error. Please extend to all the config functions. set_div, set_duc_max, etc.

**Comment by jordens** [comment]
Where did I agree to that?

**Comment by jordens** [comment]
You are intentionally misinterpreting me. I said that I would force serialization by signalling `RTIOCollisions`.

**Comment by jbqubit** [comment]
In #762 @jordens said

> And you are submitting two events to the config channel at the same time. One gets dropped and then you are only setting one limit. Add some delay before for the second limit. I'll force that in the next commits.

My interpretation of "I'll force that in the next commits" was different. I thought you were indicating agreement to add a delay to sawg.config.* as in reset(). My bad. As it stands I confirm that when the user responds to said "force" and adds a delay, no RTIO collision errors are generated and the sawg output is as expected. 

```
        # collision error
        self.sawg1.config.set_duc_max(0.5)
        delay(1*us)
        self.sawg1.config.set_duc_min(-0.5)
```
For those following at home... When ```delay(1*us)``` is commented out here's what a collision error looks like as reported by artiq_corelog.
```
[   779536143us] ERROR(runtime::rtio_mgt): RTIO collision
```
And here's where to read about RTIO Collisions
in the manual: ```artiq/doc/manual/_build/html/rtio.html?highlight=rtio%20collision#collisions```
