### ISSUE TITLE
SAWG on Kintex Ultrascale

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#798]
Port SAWG channels to Sayma and optimize.

Was originally in contract: "Port single-tone non-interpolating RTIO parallelized DDS (fDATA) core to Kintex Ultrascale."

**Comment by jordens** [comment]
Done. Will be debugged when Ethernet is up.
https://github.com/m-labs/artiq/blob/master/artiq/gateware/targets/sayma_amc_standalone.py#L229

**Comment by sbourdeauducq** [comment]
I think this is on our side, not @enjoy-digital's.

**Comment by jordens** [comment]
Sure. But Florent helped with integration.

**Comment by enjoy-digital** [comment]
@jordens: not sure i can really help on that, but if it's related to things i'm working on, yes i'll look at it.

**Comment by jordens** [comment]
It's done. The issue is closed. I was just documenting the progress.
