### ISSUE TITLE
update developing.rst to reflect existence of artiq-dev conda package

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#814]
As of Jan 2016 most ARTIQ binary dependencies are automatically built and distributed in the conda ```artiq-dev``` package. Most end users who build .bit for an ARTIQ core device only modify gateware.target.__ and would benefit from the streamlined workflow. Please update ```doc/manual/developing.rst``` to emphasize the streamlined .bit build workflow that's currently used in the automated build system. For example, 
```
python -m artiq.gateware.targets.phaser
cp bscan_spi_xc7k325t.bit binaries
cp misoc_phaser_kc705/gateware/top.bit binaries
cp misoc_phaser_kc705/software/bios/bios.bin binaries
cp misoc_phaser_kc705/software/runtime/runtime.fbi binaries
artiq_flash -d binaries 
```

**Comment by jordens** [comment]
https://m-labs.hk/artiq/manual-master/core_device.html#phaser
