### ISSUE TITLE
VHDCI for Sayma

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#817]
https://github.com/m-labs/artiq/compare/master...jbqubit:vhdci_play

and

Here's the FMC -> VHDCI adapter pins file we were looking at: https://github.com/npisenti/artiq/blob/jqi-dev/artiq/gateware/jqi_fmc_vhdci.py

/cc @npisenti @jbqubit

**Comment by jbqubit** [comment]
Initialization routine for [Creotech FMC DIO 32ch lvds a v1.2](www.ohwr.org/projects/fmc-dio-32chlvdsa/wiki) is here: 

https://github.com/jbqubit/artiq/blob/vhdci_play/artiq/examples/phaser/repository/init_vhdci.py

**Comment by sbourdeauducq** [comment]
Done, needs testing.

**Comment by sbourdeauducq** [comment]
This works except for the FMC card line direction control.
@gkasprow Are there different versions of that card with different permutations of the shift register outputs, by any chance? Is this correct: https://github.com/m-labs/artiq/blob/fe93a454d68b6e6db697c0c0c6f550ec95bbb691/artiq/coredevice/fmcdio_vhdci_eem.py#L9

The code loads the shift register MSB first:
https://github.com/m-labs/artiq/blob/fe93a454d68b6e6db697c0c0c6f550ec95bbb691/artiq/coredevice/shiftreg.py#L18

**Comment by sbourdeauducq** [comment]
Thanks. The code I linked was correct, but I was doing something daft in my test kernel. Things are working correctly now.
