### ISSUE TITLE
bitstream and device_db builder, EEM I2C tree verification

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#823]
With the Sinara EEMs implying mutually incompatible RTIO Phys we need to build per-setup bitstreams. 
 A potential idea (RFC) would be:

* (optionally) upload a minimal bistream and query EEM types and channel settings (e.g. directions) through I2C
* generate and have the user write/edit a EEM and channel RTIO description
* generate, package bitstream, maybe with a build service
* generate `device_db.pyon` template
* (optionally) verify bitstream correctness w.r.t. EEMs using I2C
* get rid of the various `FIRST_X_CHANNEL` constants
* figure out `ref_multiplier` implicit definition through existence of serdes TTL channels

C.f.
* #581 #564 for growing differentiation of TTL channel types
* #595 #788 are incompatible with other EEMs

Related:
* #781
* #779 

Components:
* https://github.com/quartiq/kasli-i2c

**Comment by sbourdeauducq** [comment]
Essentially done (without the I2C options).
