### ISSUE TITLE
IRC log broken

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#826]
```https://irclog.whitequark.org/m-labs```

502 Bad Gateway
nginx/1.10.3

**Comment by jordens** [comment]
That's not an ARTIQ issue. Write an e-mail.

**Comment by jbqubit** [comment]
@jordens This is an ARTIQ Issue in so much as @sbourdeauducq insists that IRC logs are part of the ARTIQ documentation. Anyway, it's unclear to me who maintains the IRC log.

**Comment by whitequark** [comment]
The domain is "whitequark.org", so @whitequark would be who maintains it...

**Comment by jbqubit** [comment]
Now fixed. Thanks @whitequark

**Comment by sbourdeauducq** [comment]
I never said that and even less insisted on it.
