### ISSUE TITLE
artiq.coredevice.comm_kernel.LoadError: cannot load kernel: symbol lookup error: floor

### ISSUE THREAD

**Issue by mntng** [m-labs/artiq#828]
got this error in the last line of this file: https://github.com/m-labs/artiq/blob/master/artiq/examples/master/repository/coredevice_examples/simple/ad5360.py/

**Comment by sbourdeauducq** [comment]
@whitequark Is this the proper solution:
```
--- a/artiq/firmware/ksupport/api.rs
+++ b/artiq/firmware/ksupport/api.rs
@@ -71,6 +71,7 @@ static mut API: &'static [(&'static str, *const ())] = &[
     /* libm */
     api!(sqrt),
     api!(round),
+    api!(floor),
 
     /* exceptions */
     api!(_Unwind_Resume = ::unwind::_Unwind_Resume),
```

Why was it apparently not a problem before? @mntng is the issue present with ARTIQ-2?

**Comment by whitequark** [comment]
@sbourdeauducq This is the proper solution. Likely what happened is LLVM decided to not inline or not unroll something, and an expression that was previously constant-folded is not, anymore. This should be backported to ARTIQ-2.
