### ISSUE TITLE
ARTIQ 3 release candidate?

### ISSUE THREAD

**Issue by dhslichter** [m-labs/artiq#833]
With the slow TCP performance in #685 now appearing to have been improved, is there a timeline for an official ARTIQ 3 release candidate?  It makes sense to wait until the various cleanup items (e.g. packet loss from ping as discussed in #685) are resolved, but I don't see any open/unresolved issues on Github with the 3.0 milestone.  Are there other issues/fixes in the works before things are stable enough to make a release candidate?  @sbourdeauducq @jordens @whitequark

**Comment by sbourdeauducq** [comment]
This is not an Issue. Yes we will make one as soon as #830 is resolved.
