### ISSUE TITLE
Frequent malformed packet errors

### ISSUE THREAD

**Issue by cjbe** [m-labs/artiq#840]
Using the 3.0 release on a KC705, connected to a 100M switch, I get a 'malformed packet' error from the core device on average every 20s.

This may be related to #837

**Comment by whitequark** [comment]
I could log malformed packets so that it's easy to tell if they are benign or not. Your case is likely to be benign though, just some network background radiation.

**Comment by whitequark** [comment]
Core device now logs the complete packet under DEBUG log level, please open an issue per type of malformed packet you see (unless it is something benign).

**Comment by whitequark** [comment]
Maybe we should lower the log level for the malformed ingress packet to DEBUG.
