### ISSUE TITLE
Sayma won't boot from flash

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#847]
Bitstream is not loaded after ``artiq_flash.py -t sayma proxy gateware start`` and after a power-cycle.
@gkasprow Are there switches or anything that need to be set on the boards you sent us?

**Comment by jordens** [comment]
M[2:0] settings?

**Comment by sbourdeauducq** [comment]
According to @gkasprow it boots when the bitstream is generated and flashed with Vivado.

**Comment by gkasprow** [comment]
Yes, switches need to be set to boot from FLASH. I tested all boards loading via JTGAG, some of them had FLASH tested as well. Without automated test-bench it's hard to test every functionality of every board. Creotech guys are working on it, Sayma AMC part is already done.

**Comment by jbqubit** [comment]
What is Vivado doing that ARTIQ is not? @gkasprow please spell out exactly what the switches are that need to be set for booting from FLASH. Have you seen booting-from-flash failure that @sbourdeauducq reports?

**Comment by gkasprow** [comment]
The switch position does not matter if you load both fpgas via jtag.

**Comment by gkasprow** [comment]
So far the FLASH configures only AMC side.

**Comment by jbqubit** [comment]
ARTIQ loading: 1. flash FPGA proxy .bit using JTAG, 2. send flash data to FPGA which writes to flash, 3. FPGA resets and expects to load .bit from flash. Please detail what the switch configuration needs to be for step 3.

**Comment by jordens** [comment]
@gkasprow could you give me the `bitgen` options you used to test loading the AMC bitstream from flash?

**Comment by gkasprow** [comment]
@jordens is it defined in some text file?

**Comment by jordens** [comment]
I forgot that `bitgen` is ISE.
If you can give me your Vivado sources for that test project or a screenshot of the bitstream properties/configuration dialog, that would be good. Things like frequency, SPI width...

**Comment by gkasprow** [comment]
hope this helps
the project is [here](https://www.dropbox.com/sh/b5gnf815xk6mzds/AABjPOywleaJw29mKkxbrfZCa?dl=0):

![obraz](https://user-images.githubusercontent.com/4325054/33423988-b8d159a2-d5ba-11e7-8e36-a675a16c97eb.png)
![obraz](https://user-images.githubusercontent.com/4325054/33424005-c8d6a87a-d5ba-11e7-9709-e2b1d780b964.png)

![obraz](https://user-images.githubusercontent.com/4325054/33424026-dd52aa38-d5ba-11e7-9dbc-03fd55562045.png)

![obraz](https://user-images.githubusercontent.com/4325054/33424052-f0a39bec-d5ba-11e7-9cda-db0250cded9b.png)

![obraz](https://user-images.githubusercontent.com/4325054/33424099-11df3a32-d5bb-11e7-9f41-ca19ac66144e.png)

![obraz](https://user-images.githubusercontent.com/4325054/33424118-1c132360-d5bb-11e7-860e-c59ea0042443.png)

![obraz](https://user-images.githubusercontent.com/4325054/33424131-25a23cea-d5bb-11e7-97cc-0554c5b67ecd.png)

![obraz](https://user-images.githubusercontent.com/4325054/33424145-2d9cbbc8-d5bb-11e7-9c5a-882d44dd0f54.png)

**Comment by jordens** [comment]
Thanks.

**Comment by jbqubit** [comment]
@jordens What's the status of this?

**Comment by sbourdeauducq** [comment]
> M[2:0] settings?

They are all at 0, which is incorrect, on the HKG boards.

**Comment by sbourdeauducq** [comment]
Er, no all at 1 (but still incorrect) the switches are enabling pull-downs.
This should be the correct position:
![sayma_m](https://user-images.githubusercontent.com/720864/33919189-3cc55b3c-dff2-11e7-99f3-f934bc5ac250.jpg)

**Comment by sbourdeauducq** [comment]
After setting the switches into that position, the board boots from the bitstream that @jordens flashed, but not the one I built from master and flashed with artiq_flash.

**Comment by jordens** [comment]
2917208d

**Comment by jbqubit** [comment]
Confirmed that I can flash using ```artiq_flash -t sayma```.  Thank you @jordens !
