### ISSUE TITLE
Label masters with a name to distinguish dashboards

### ISSUE THREAD

**Issue by cjbe** [m-labs/artiq#848]
It would be useful for Artiq masters to have a configurable name, and have the dashboards show the logical name of the master they are connected to, rather than just an IP address. 

At the moment is it rather confusing when connecting to multiple masters with similar addresses. This is particularly necessary if one is wants to run multiple masters on one host (as we are planning).

**Comment by jordens** [comment]
Using the hostname (instead of the IP address) should work just fine.

**Comment by sbourdeauducq** [comment]
He wants to run multiple masters one one host. You can have multiple hostnames mapped to one IP, and different ports open for each master, but then there can be confusion if you connect with an unplanned hostname/port combination.

I suppose the dashboard should also store one set of configuration data per master.

**Comment by cjbe** [comment]
Implemented in PR #855
