### ISSUE TITLE
Log messages not printed in scheduled experiment

### ISSUE THREAD

**Issue by philipkent** [m-labs/artiq#850]
We're using python logging to print info, warning, debug, etc. messages.  If we use the scheduler to submit an experiment that uses python logging the messages are not printed.  Is there a way to specify the log level when submitting an experiment through the scheduler?  Seems like that's what's needed but there is no argument for log level for the scheduler.submit() method.

**Comment by sbourdeauducq** [comment]
It's not built into the scheduler, but you can implement that yourself in the experiment using ARTIQ's [EnumerationValue](http://m-labs.hk/artiq/manual-release-3/core_language_reference.html#artiq.language.environment.EnumerationValue) and Python's [Logger.setLevel](https://docs.python.org/3/library/logging.html#logging.Logger.setLevel).

**Comment by sbourdeauducq** [comment]
The log level is in ``expid["log_level"]``. It expects an integer with the same conventions as the Python logging module, e.g. ``logging.WARNING``.

**Comment by sbourdeauducq** [comment]
And the current ``expid``, if you need that, is ``scheduler.expid``.

**Comment by sbourdeauducq** [comment]
@philipkent Does this solve your problem?

**Comment by philipkent** [comment]
Thanks, I will try that.

**Comment by philipkent** [comment]
Using scheduler.expid['log_level'] worked.  Thanks.
