### ISSUE TITLE
searching log messages in dashboard panels

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#851]
Currently, the filters only applies to the log messages as they arrive. There is currently no way in the dashboard to search for a previously received log message by keyword (and, with lesser importance, by priority). I see two ways of doing this:
1. also applying the filters to the log messages already in the panel's buffer.
2. adding another search feature.

I'm more leaning towards option 1.

**Comment by jbqubit** [comment]
I like (1). It's helpful when focusing on a specific logged event type to see both its history and new events of that type as they happen.

**Comment by dnadlinger** [comment]
cc @ljstephenson

**Comment by sbourdeauducq** [comment]
Should the incoming message filtering be removed?
