### ISSUE TITLE
Sayma_AMC: interacting with ARTIQ

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#853]
How do I load ARTIQ Python programs? Ethernet or PPP?

**Comment by sbourdeauducq** [comment]
It doesn't work, see my emails about RGMII. PPP is no longer supported.

**Comment by jbqubit** [comment]
I didn't appreciate that this is an implication of the RGMII problem you mentioned. The RGMII discussion should be an Issue so everyone involved can contribute to the discussion. Shall I create a new Issue by cutting and pasting from your email to me? Or would you like to create the Issue?

**Comment by sbourdeauducq** [comment]
> I didn't appreciate that this is an implication of the RGMII problem you mentioned

I don't know how many times we told you that there was a serious problem with Sayma Ethernet...

> The RGMII discussion should be an Issue so everyone involved can contribute to the discussion

Unless someone wants to fix that bug or provide funding, there is nothing to discuss.
