### ISSUE TITLE
serwb scrambling

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#862]

**Comment by jbqubit** [comment]
Please add to Milestone 4.

**Comment by sbourdeauducq** [comment]
It works without scrambling and it is not a blocker for 4.0 release.

**Comment by enjoy-digital** [comment]
Implemented and tested in simulation. I'll test it on Sayma soon.

**Comment by sbourdeauducq** [comment]
Seems to work. Should we close this?

**Comment by enjoy-digital** [comment]
yes we can close it. (it's also validated on the boards i have)
