### ISSUE TITLE
Sayma: no debug info on flterm

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#870]
Confirmed that I can flash using ```artiq_flash -t sayma```. https://github.com/m-labs/artiq/issues/847 However, I don't see anything on flterm when I remove power from Sayma_AMC, wait 3 seconds then reapply power. I've checked all four serial interfaces.

**Comment by sbourdeauducq** [comment]
Is the done led on? Did you set up the M switches?

**Comment by jbqubit** [comment]
Which LED?

**Comment by sbourdeauducq** [comment]
Top layer, green, near the FMC connector and the top edge. And maybe "3 seconds" is not enough.

**Comment by jbqubit** [comment]
I set "M switches" on PCB "HS1" to 1234 -> 0111. I can now flash the board using artiq_flash -t sayma and see on ttyUSB2 MiSoC BIOS messages. Thanks!
