### ISSUE TITLE
instructions for using ARTIQ with Sayma

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#871]
@sbourdeauducq Thank you for the commits including example code for Sayma. https://github.com/m-labs/artiq/commit/569484f88802dabbbbe7fdd8be93498f94ddcf42

What clock are you supplying to Sayma?

**Comment by sbourdeauducq** [comment]
100MHz to the connector on the RTM. This is not an Issue.

**Comment by jbqubit** [comment]
For testing board-board synchronization it will be easier to use the RTM SMA clock input.

**Comment by sbourdeauducq** [comment]
Yes, that's the one.
