### ISSUE TITLE
remove BUILD_SETTINGS_FILE from conda scripts?

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#879]
The conda board scripts contain this boilerplate:
```
BUILD_SETTINGS_FILE=$HOME/.m-labs/build_settings.sh
[ -f $BUILD_SETTINGS_FILE ] && . $BUILD_SETTINGS_FILE
```

Is it necessary or is it some old copy-paste code that persisted?

**Comment by whitequark** [comment]
I believe the purpose of this is setting the path to proxy bitstreams. Since we now build packages exclusively on the buildbot it is no longer necessary.

**Comment by jordens** [comment]
Don't know where that came from. Fwiw can be removed.

**Comment by sbourdeauducq** [comment]
Removed.
