### ISSUE TITLE
Ubuntu 14.04 dependencies missing for git support

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#88]
sudo apt-get install libhttp-parser2.1 libssh2-1

**Comment by sbourdeauducq** [comment]
In general, libraries are installed automatically as dependencies of other packages. What package requires those, exactly?

**Comment by fallen** [comment]
Those are dependencies of libgit2 , I will have a look at if I can either package those in conda or somehow link libgit2 statically with them at build time

**Comment by fallen** [comment]
seems that it's very likely you already have libssh2-1. Since git, gitk, cmake, gnupg, libreoffice, vlc for instance require it

**Comment by fallen** [comment]
I've just re-uploaded the libgit2 package, removing the dependency on libhttp-parser.
It still depends on libssh2 though, but this should be installed on most distros, is it really not installed on Ubuntu 14.04?

**Comment by jboulder** [comment]
My experience yesterday on Xubuntu 14.04 was that both these libraries
needed to be installed via apt-get.

**Comment by fallen** [comment]
So : I removed the dependency on libhttp-parser and I packaged libssh2.
It should be fixed now.
