### ISSUE TITLE
back up Github issues

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#881]
We don't have backups for the non-repository content on Github (issues, wiki).
I propose putting a cronjob on the lab computer that runs one of those on the main repositories (artiq, sinara, migen, misoc, smoltcp):
https://help.github.com/articles/backing-up-a-repository/

**Comment by whitequark** [comment]
I think we have many more important things to do...

**Comment by sbourdeauducq** [comment]
done
