### ISSUE TITLE
artiq 3+ not supported on windows

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#896]
As per #893 m-labs says they are no longer supporting Windows. I'm fine with that. @dhslichter? If Windows support is now deprecated please update the documentation indicating this.

http://m-labs.hk/artiq/manual-release-3/installing.html#installing-artiq

**Comment by sbourdeauducq** [comment]
artiq != artiq-dev. Windows is still supported, what is not is conda packages that let you recompile the runtime etc. on Windows.

**Comment by jbqubit** [comment]
OK. Please note that here

http://m-labs.hk/artiq/manual-release-3/developing.html#developing-artiq

**Comment by dhslichter** [comment]
We still definitely require Windows support.

**Comment by dhslichter** [comment]
@jbqubit we do not intend to do our own ARTIQ builds on Windows (can use a Linux box if this is really necessary), but we do require the ability to run ARTIQ on Windows.  This means maintaining CI for conda packages for Windows.
