### ISSUE TITLE
Binaries missing  in artiq 3.x on Windows

### ISSUE THREAD

**Issue by KaifengC** [m-labs/artiq#903]
Trying to upgrade artiq to 3.2 version using `conda create -n artiq_32 artiq-kc705-nist_clock=3.2`.
The installation is successful but then I tried `artiq_flash -t kc705 -m nist_clock` but got `Binaries directory...... does not exist`

I checked both nist_clock and nist_qc2 hardwares on windows. It seems the binaries files are lost after the installation.

**Comment by sbourdeauducq** [comment]
https://github.com/m-labs/artiq/issues/894 ?

**Comment by jbqubit** [comment]
@sbourdeauducq Please try installing 3.2 on a Windows 10 machine. You will see several hiccups in addition to those reported by @TheCakeIsAPi and @KaifengC.

**Comment by sbourdeauducq** [comment]
What exactly? We do have Windows CI for many things so that's surprising.

**Comment by KaifengC** [comment]
Yes, it's the same with #894 . Sorry I didn't see that before.
I installed several versions on Windows. This bug firstly appears on 3.0. It works well on version 2.5

**Comment by sbourdeauducq** [comment]
Yes, it's due to switching to new-style conda noarch package that happened in 2.4, since after an update of conda the old-style noarch packages began to have various bugs and problems. Maintaining conda takes constant work...

**Comment by sbourdeauducq** [comment]
For now, can you put the binaries manually where artiq_flash expects them?
