### ISSUE TITLE
JESD core conda update

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#906]
cf #854

>Get the JESD core from git (https://github.com/m-labs/jesd204b), not the conda package. Considering how many people run into this issue, I should probably update the conda package...
You can also strip all the JESD stuff since you don't need it for Ethernet.

>It's just 3 commands:
conda remove jesd204b
git clone https://github.com/m-labs/jesd204b
export PYTHONPATH=$PYTHONPATH:`pwd`/jesd204b

**Comment by jbqubit** [comment]
@sbourdeauducq is this closed because you're annoyed or because jesd204b conda is updated? I didn't see a commit.

**Comment by sbourdeauducq** [comment]
The conda package will be built when JESD204 SC1 is done, at the latest. We don't need an issue for every single thing. And, in the present state of affairs, if you use Sayma you are generally expected to build from source and use git.

**Comment by jbqubit** [comment]
[This](http://m-labs.hk/artiq/manual-master/developing.html#artiq-anaconda-development-environment) is how I prepare a conda environment for building .bit. Your build system also uses the same artiq-dev.yaml. Please make it easy for us all to use the same build environment.

**Comment by sbourdeauducq** [comment]
For now just install the JESD core from git using the instructions I posted elsewhere.

**Comment by jbqubit** [comment]
```
conda remove jesd204b
git clone https://github.com/m-labs/jesd204b
export PYTHONPATH=$PYTHONPATH:`pwd`/jesd204b
```
