### ISSUE TITLE
Artiq3.4: binutils-or1k-linux dependency issue on windows

### ISSUE THREAD

**Issue by jonaskeller** [m-labs/artiq#915]
Trying to install artiq 3.4 (py_0+git9db30ce8) on windows 7 64bit fails at the dependency

    binutils-or1k-linux >=2.27

The most recent windows binaries in the conda repository are v 2.25.1.

I could look into building it myself, but since you'll probably want it in your repository anyway, that doesn't seem worth the effort.

**Comment by jordens** [comment]
@whitequark I tightened that dependency to match `artiq-dev`. Are we/should we be using different binutils?

**Comment by whitequark** [comment]
@jordens I don't remember the exact diff between 2.27 and 2.25.1. I think 2.27 is just 2.25.1 plus our patches. The Windows build requires Cygwin and that isn't currently automated.

**Comment by sbourdeauducq** [comment]
Why are the automatic tests not catching that?

**Comment by whitequark** [comment]
Catching what?

**Comment by sbourdeauducq** [comment]
The ARTIQ conda package not installing correctly on Windows, either on the release-3 branch or master; both specify binutils-or1k-linux >=2.27.

**Comment by sbourdeauducq** [comment]
http://buildbot.m-labs.hk/builders/artiq/builds/2026 was for https://github.com/m-labs/artiq/commit/4c22d64ee438d8b65ba728829794698191719181.

**Comment by jordens** [comment]
In that build build 520 was installed on windows while the parent build was 521.

**Comment by jordens** [comment]
The windows test is not installing the artiq version that the build is running for http://buildbot.m-labs.hk/builders/artiq-win64-test/builds/718/steps/conda_create/logs/stdio
@whitequark what should we do? different binutils versions on windows (kernel build) and linux (firmware build)? ignore the version?

**Comment by sbourdeauducq** [comment]
I believe the clean solution is a) fix the buildbot b) do the build of binutils-or1k-linux 2.27 that wasn't done for Windows.

**Comment by sbourdeauducq** [comment]
> do the build of binutils-or1k-linux 2.27 that wasn't done for Windows.

Done.
