### ISSUE TITLE
the artiq_flash exits with error

### ISSUE THREAD

**Issue by mingshenli** [m-labs/artiq#917]
run` artiq_flash -t kc705 -m nist_clock`,with zadig running well

![artiq2](https://user-images.githubusercontent.com/35680445/35903139-ee127d5a-0c18-11e8-96e2-43771915de8f.png)

**Comment by sbourdeauducq** [comment]
What ARTIQ version?

**Comment by mingshenli** [comment]
it is 3.2


thanks


best


 
 
------------------ Original ------------------

**Comment by jordens** [comment]
You need to manually install openocd-0.10.0-1 or wait for 3.5 to do that for you.

**Comment by sbourdeauducq** [comment]
@jordens That's in 3.4 already, and 3.4 is fixable on Windows by updating the binutils package. Doing that now...

**Comment by sbourdeauducq** [comment]
@mingshenli try updating ARTIQ to 3.4. If the problem persists checks that it installed the OpenOCD version that @jordens recommended.

**Comment by jordens** [comment]
Ack
