### ISSUE TITLE
Error:  'device_db.py'can not be found

### ISSUE THREAD

**Issue by mingshenli** [m-labs/artiq#920]
with artiq3.5,run`artiq_compile idle.py` ,
 I can find  'device_db.py'   in  
 C:\ProgramData\Anaconda3\envs\artiq-3.5\Lib\site-packages\artiq\master,
and I move it to
 C:\ProgramData\Anaconda3\pkgs\python-3.6.3-h9e2ca53_1\Lib\idlelib
![m-lab20180211135142](https://user-images.githubusercontent.com/35680445/36070282-8a4402e0-0f32-11e8-9f44-4d11623b198b.png)
but
![m-labqq 20180211-3](https://user-images.githubusercontent.com/35680445/36070308-cc3160d0-0f32-11e8-8515-53d9a1a14a60.png)
the same things happened when I run `artiq_run led.py`  In accordance with the instructions of the instructions on http://m-labs.hk/artiq/manual-release-3/getting_started_core.html

**Comment by sbourdeauducq** [comment]
Those programs look for ``device_db.py`` in the current directory by default. Use the ``cd`` command to go to ``C:\ProgramData\Anaconda3\pkgs\python-3.6.3-h9e2ca53_1\Lib\idlelib`` (though you may want to put those in a more appropriate folder)

**Comment by mingshenli** [comment]
the `device_db.py` has been copy to the folder where `idle.py` in(the first picture), from `C:\ProgramData\Anaconda3\envs\artiq-3.5\Lib\site-packages\artiq\master,`

**Comment by sbourdeauducq** [comment]
https://en.wikipedia.org/wiki/Working_directory

**Comment by sbourdeauducq** [comment]
Your current directory is ``c:\windows\system32``. It is looking for ``c:\windows\system32\device_db.py``, which doesn't exist.

**Comment by mingshenli** [comment]
can moving the `device_db.py` to `c:\windows\system32\device_db.py` solve the problem?

**Comment by sbourdeauducq** [comment]
``c:\windows\system32`` is not meant to hold the ARTIQ device database, use the ``cd`` command to change the current directory instead.

**Comment by mingshenli** [comment]
ok, I will try it. thanks.
