### ISSUE TITLE
autogenerate board conda recipes

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#923]
There is a lot of redundancy in the board conda recipes and this will only get worse as more boards/variants are added.

It woud be better to have one database file with entries containing only:
* package name
* package description
* target file and variant
* master/satellite (as the firmware is named differently)

Or the package building program could look into the target files to get this information.

**Comment by sbourdeauducq** [comment]
Or maybe this: https://conda.io/docs/user-guide/tasks/build-packages/variants.html

**Comment by sbourdeauducq** [comment]
And Sayma (with the RTM) will need special treatment.

**Comment by jordens** [comment]
Conda variants won't do the trick AFACT since they are mutually exclusive in an environment.
