### ISSUE TITLE
failed to create process on version 2.3 under Windows

### ISSUE THREAD

**Issue by philipkent** [m-labs/artiq#931]
On Windows 7 64-bit, using ARTIQ version 2.3 from the m-labs conda repository, trying to run any of the artiq commands from a command prompt fails with "failed to create process" error:

     (artiq-2.3) >artiq_flash -t kc705 -m nist_qc2
      failed to create process.

     (artiq-2.3) >artiq_master
      failed to create process.

     (artiq-2.3) >artiq_browser
      failed to create process.

**Comment by sbourdeauducq** [comment]
That's a conda bug, iirc worked around in artiq 2.4.

**Comment by jordens** [comment]
@philipkent Assuming 2.4 had already fixed this, I'll close it.
