### ISSUE TITLE
Artiq 2.4: Experiment fails to run on Windows because cygwin1.dll can't be found

### ISSUE THREAD

**Issue by philipkent** [m-labs/artiq#935]
Running an experiment using version 2.4 on windows 7 64 bit from the conda repository fails with the following error:

      or1k-linux-ld.exe: The program can't start because cygwin1.dll is missing from your computer.  Try reinstalling the program to fix this problem

The `cygwin1.dll` dll can't be found.

This can be fixed by downgrading the `binutils-or1k-linux` package to version 2.25.1-4 with:

    conda install --name <environment name> binutils-or1k-linux=2.25.1

**Comment by whitequark** [comment]
No, it needs to be rebuilt at version 2.25.1-5 using msys instead of cygwin.

**Comment by whitequark** [comment]
Also, it's or1k-linux-ld, not -id.

**Comment by whitequark** [comment]
Package rebuilt.

**Comment by whitequark** [comment]
No, actually, it doesn't work.

**Comment by whitequark** [comment]
The package does work now.

**Comment by sbourdeauducq** [comment]
No, it doesn't.

**Comment by sbourdeauducq** [comment]
Still happens with binutils-or1k-linux 2.27 5.

**Comment by whitequark** [comment]
No, it doesn't. I have provisioned a completely fresh Windows machine just now and installed only the binutils-or1k-linux package, and it doesn't crash because of `cygwin1.dll`:
![screenshot_20180315_205616](https://user-images.githubusercontent.com/54771/37490750-77a85ecc-2893-11e8-9527-45190a263e08.png)

**Comment by whitequark** [comment]
And I can actually `artiq_compile` code with these binutils.

**Comment by sbourdeauducq** [comment]
Well @mingshenli does have a Windows machine on which this package is installed, and ``ld`` fails due to missing cygwin1.dll. Interestingly, this only happens when the experiment is run by the master, ``artiq_run`` and ``artiq_compile`` are working correctly. I thought ``ld`` was now completely independent from cygwin?

**Comment by sbourdeauducq** [comment]
Though that behavior may be due to the ``cygwin1.dll`` he put in the device db directory as a workaround.

**Comment by sbourdeauducq** [comment]
@mingshenli To double-check: can you activate the artiq conda environment, go to ``d:\artiq1`` and run ``or1k-linux-ld --version``?

**Comment by whitequark** [comment]
It is completely independent from cygwin. It is compiled as a MinGW application, which means it's windows native. What you're describing seems like the result of master being run from a different conda environment with older binutils package.

**Comment by mingshenli** [comment]
yes, I find the or1k-linux-ld.exe and run it, but failed because " the cygwin1.ddl can not be found."

**Comment by whitequark** [comment]
This must be an old conda package. If all else fails, you can remove your entire conda install and start over.

**Comment by sbourdeauducq** [comment]
@whitequark same conda environment that makes artiq_run work.

**Comment by whitequark** [comment]
Is there another miniconda installation in PATH?

**Comment by mingshenli** [comment]
Now it seems work.

**Comment by sbourdeauducq** [comment]
@mingshenli Still, what is the output of ``or1k-linux-ld --version``?

**Comment by mingshenli** [comment]
nothing happened after I run `start C:\ProgramData\Anaconda3\envs\artiq-3.5\bin\or1k-linux-ld.exe `  except a cmd window flash.
I only have those on  my computer.
![qq 20180316172049](https://user-images.githubusercontent.com/35680445/37512649-b77fee34-293d-11e8-87d0-a37e7b9e2302.png)

**Comment by sbourdeauducq** [comment]
Please follow the instructions carefully:

> activate the artiq conda environment, go to d:\artiq1 and run or1k-linux-ld --version

Do this in an already open cmd window.

**Comment by mingshenli** [comment]
do as  follow?

 `activate artiq-3.5`     
`cd D:\artiq1`
`or1k-linux-ld --version`

**Comment by sbourdeauducq** [comment]
Yes.

**Comment by mingshenli** [comment]
but it didn't work because 'or1k-linux-ld --version' is not a command or file

**Comment by sbourdeauducq** [comment]
Strange, if you see this screenshot it works:
https://github.com/m-labs/artiq/issues/935#issuecomment-373520539

**Comment by mingshenli** [comment]
is it have any influence on  running  `artiq_run` or other command uploading the python file to the kc-705 board?
