### ISSUE TITLE
report DRTIO loss-of-link when a kernel is running

### ISSUE THREAD

**Issue by cjbe** [m-labs/artiq#942]
If a kernel is running and the DRTIO link is lost, the kernel hangs until the link is back up, at which point it underflows. If the link does not come back, the kernel hangs indefinitely.

It would be useful to have some way of signalling this catastrophic error state to the user.

**Comment by sbourdeauducq** [comment]
Planning to introduce a ``RTIOLinkError`` exception when attempting a RTIO operation that involves a link that is down. It cannot be precise (since we usually don't wait for feedback from the satellite devices for latency/throughput reasons) but it should catch most cases.

**Comment by sbourdeauducq** [comment]
done.
