### ISSUE TITLE
Satman 'aux packet error' on DRTIO link initialisation

### ISSUE THREAD

**Issue by cjbe** [m-labs/artiq#949]
Whenever a DRTIO link is initialised (by reboot or unplugging/replugging a fiber) the satellite emits a warning. 

A typical log:
```
Starting firmware.
[     0.000006s]  INFO(satman): ARTIQ satellite manager starting...
[     0.004622s]  INFO(satman): software version 4.0.dev+670.ge3938620
[     0.010802s]  INFO(satman): gateware version 4.0.dev+670.ge3938620
[     1.968716s]  INFO(board_artiq::si5324): Si5324 is locked
[     2.585181s]  INFO(satman): link is up, switching to recovered clock
[     4.254683s]  INFO(board_artiq::si5324): Si5324 is locked
[     4.258772s]  WARN(satman): aux packet error (gateware reported error)
```

The satman warning seems to happen at roughly the same time as the master reports 'link initialisation complete'. These warnings only seem to occur on link startup - I have never seen them at any other time.

**Comment by sbourdeauducq** [comment]
Yes, that's pretty harmless - during link initialization the master keeps pinging the satellite on the aux channel until it is able to answer packets correctly, after which the link is declared up. What is happening is the satellite gateware receives a ping packet while the firmware is busy-waiting on the Si5324 lock, then another that causes an error as the buffer was already full (the firmware is still blocked on the lock). Then the Si locks, and the firmware looks at the aux packet gateware, and sees the error flag. There should be no adverse effects other than this warning message.
