### ISSUE TITLE
Kasli: use default MAC address from EEPROM

### ISSUE THREAD

**Issue by cjbe** [m-labs/artiq#955]
As Kasli v1.1 has an EEPROM with a MAC address pre-programmed, it would be nice if the default MAC address was read from this.

**Comment by hartytp** [comment]
:+1:

**Comment by jordens** [comment]
Yeah. Maybe a nice tweak. But you still need to set all kinds of other information. And commissioning Kasli is more than that. Write the FT4232H eeprom with the serial number and correct settings, set the writable part of the eeprom, commission the other devices on the tree.
