### ISSUE TITLE
check that FPGA has latest firmware

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#97]
On occasions modifications to ARTIQ require compilation of a new bit file. Upon startup artiq_master should check to see if the Core Device is up to date. If not prompt user to run artiq_flash.sh.

**Comment by sbourdeauducq** [comment]
This is complicated (due to the problem of tracking which bitfiles changes are incompatible and which are not). How important is that?

**Comment by jordens** [comment]
I don't think we have to do any meaningful tracking and versioning of the gateware interface/runtime API yet. As outlined on the mailing list, having the host-side code query the embedded gateware git hash, the bios git hash and the runtime git hash and compare against its own would go a long way. Then reduce the mismatch error from something fatal to a warning if the `pdb` entry for the core device has `ignore_mismatch` which you could use during development.
I suspect `versioneer` might come handy here.
Low priority IMHO. Feel free to label as such.

**Comment by sbourdeauducq** [comment]
Let me take care of this one, will be an occasion to touch the new comms code.
