### ISSUE TITLE
core.reset() touches phy state

### ISSUE THREAD

**Issue by cjbe** [m-labs/artiq#971]
Calling core.reset() resets the direction of all InOut TTLs to inputs - previously the phy state has been untouched by core.reset().

Observed using a Kasli and Artiq 1553fc8c7df7150c00ce853dea71fc6840606f7e

**Comment by jordens** [comment]
To be clear, those are SERDES TTLs? Or simple TTLs?

**Comment by cjbe** [comment]
@jordens I observe this on SERDES TTLs, I have not tried this on simple TTLs
