### ISSUE TITLE
String comparisons by value using != on core

### ISSUE THREAD

**Issue by philipkent** [m-labs/artiq#974]
I tried looking around to see if this was covered in an earlier issue but couldn't find any...

On Artiq version 2.4 on windows 64 bit, I have the following experiment:

     from artiq.experiment import *

     class StrComp(EnvExperiment):

         def build(self):
             self.setattr_device('core')

         @kernel
         def run(self):
             if 'a' != '':
                 print(True)
             else:
                 print(False)

Which always prints False.  If I use the  `==` operator instead, the comparisons seem to work fine: `'a' == 'a'` returns True and  `'a' == ''` returns False.  Are string comparisons like the one above allowed on the core?  If not, we can easily do the comparisons using `==` instead but it's easy to forget while writing that using `!=` and an empty string returns False instead of True.

**Comment by whitequark** [comment]
Seems like a bug.

**Comment by whitequark** [comment]
This actually has nothing to do with comparing by value, I compare strings for nonequality with
```
for (x, y) in lhs.zip(rhs):
  if x == y:
    return False
return True
```
which is obviously wrong.
