### ISSUE TITLE
not any files are installed when install artiq-3.6 version

### ISSUE THREAD

**Issue by joeshardow** [m-labs/artiq#975]
![20180402 artiq3 6](https://user-images.githubusercontent.com/31177110/38178549-d0c1b802-3647-11e8-98d5-6f25656c2aaf.jpg)
![20180402 artiq3 6 2](https://user-images.githubusercontent.com/31177110/38178550-d117415a-3647-11e8-9b64-831eb44e1ad0.jpg)
There are not any files when i install artiq 3.6. How can I build a normal environment?

**Comment by whitequark** [comment]
You also need to install the `artiq` package.

**Comment by joeshardow** [comment]
How to install artiq package now? The command "conda create -n artiq-main artiq-kc705-nist_clock"  is install everything before.

**Comment by whitequark** [comment]
`activate artiq-main` then `conda install artiq`

**Comment by sbourdeauducq** [comment]
@whitequark Is there a problem with the dependency of the board packages?

**Comment by sbourdeauducq** [comment]
@whitequark Can be reproduced (on Linux); the board package no longer installs artiq.
