### ISSUE TITLE
the dashboard raise error

### ISSUE THREAD

**Issue by mingshenli** [m-labs/artiq#977]
I open the dashboard as the documentation  says, and successfully makes it print ''hello world''
![qq 20180403200814](https://user-images.githubusercontent.com/35680445/38248156-0cb4d6d6-377a-11e8-8692-e40a8ae0d214.png)
however, when I create a file which hope the ttl windows on dashboard will react,(the file is in `~/artiq-master/repository` )
![qq 20180403200144](https://user-images.githubusercontent.com/35680445/38247830-21f57600-3779-11e8-81fe-4ea1ef201f97.png)
 open the dashboard, there is a error
![qq 20180403195927](https://user-images.githubusercontent.com/35680445/38247926-64cf4dfc-3779-11e8-86c2-a6316ef850eb.png)
and the dashboard
![qq 20180403200038](https://user-images.githubusercontent.com/35680445/38247996-90b32f7e-3779-11e8-9aed-d76d046e036d.png)
click submit, then

![qq 20180403200118](https://user-images.githubusercontent.com/35680445/38248104-e4a5f54e-3779-11e8-9a37-d8f8a4d31e21.png)
and the ttl windows on dashboard has no response.

and, on a VMware run linux Ubuntu，the dashboard can not be open

![qq 20180403201437](https://user-images.githubusercontent.com/35680445/38248461-08d95f72-377b-11e8-8ed5-9792a7ee2d59.png)

**Comment by mingshenli** [comment]
ok. I will have a try. thanks

**Comment by mingshenli** [comment]
no, now there is error
![qq 20180403204312](https://user-images.githubusercontent.com/35680445/38249645-f6d3af9a-377e-11e8-9d3d-72896f7148bc.png)
the`MgmtTutorial1` is the name it changed  from`rtio.py`, and `Mgmt_Tutorial.py`  is the name of the file I use to test the dashboard(print `hello world`)
and, can the dashboard function without the kc705 been connected through internet?

**Comment by sbourdeauducq** [comment]
> heMgmtTutorial1 is the name it changed fromrtio.py, and Mgmt_Tutorial.py is the name of the file I use to test the dashboard(print hello world)

Right-click on the experiment list in the explorer and trigger a rescan.

> and, can the dashboard function without the kc705 been connected through internet?

Yes.

**Comment by mingshenli** [comment]
it still raise the same error

**Comment by sbourdeauducq** [comment]
Please post detailed steps explaining how I can reproduce the problem.

**Comment by mingshenli** [comment]
after open the dashboard, and the cmd windows is same as upon pictures shows,
![10](https://user-images.githubusercontent.com/35680445/38250624-d88c8ba8-3781-11e8-8ee0-e7c825a1cf2b.png)

> Right-click on the experiment list in the explorer and trigger a rescan

I click `scan repository HEAD`
because it says `Renaming class 'MgmtTutorial' in 'rtio.py' to 'Management tutorial1'`, then I chose the 
Management tutorial1 and click submit, and then the cmd of artiq_master shows `ERROR:master:artiq.master.scheduler:got worker exception in prepare stage, deleting RID 49`

**Comment by sbourdeauducq** [comment]
That's not enough for me to reproduce it, e.g. I don't have your experiments. I need detailed instructions that start from a *blank* ARTIQ installation.

**Comment by mingshenli** [comment]
![qq 20180403211021](https://user-images.githubusercontent.com/35680445/38250967-b29cb020-3782-11e8-940c-5795c5dc2c75.png)
![qq 20180403211409](https://user-images.githubusercontent.com/35680445/38251151-3b5843ca-3783-11e8-8dc8-a05b29c168e6.png)

**Comment by sbourdeauducq** [comment]
I see three experiments in your screenshot. Are they all needed to reproduce the problem? if yes then I need all three. If no then please delete the other ones and give me minimal instructions.

**Comment by sbourdeauducq** [comment]
And please post the *text* of experiments, not a screenshot, so I can copy-paste it.

**Comment by mingshenli** [comment]
the rtio.py:
from artiq.experiment import *


class Tutorial(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.setattr_device("ttl0")

    @kernel
    def run(self):
        self.core.reset()
        self.ttl0.output()
        for i in range(1000000):
            delay(2000000*us)
            self.ttl0.pulse(2000000*us)

**Comment by mingshenli** [comment]
the mgmt_tutorial.py
from artiq.experiment import *


class MgmtTutorial(EnvExperiment):
    """Management tutorial"""
    def build(self):
        pass  # no devices used

    def run(self):
        print("Hello World")

**Comment by mingshenli** [comment]
and it is strange that I only put these two experiments in repository

**Comment by mingshenli** [comment]
and, about the problem on ubuntu, I do as the guide says 'making a py35 environment' the same as I do on windows.
![qq 20180403212549](https://user-images.githubusercontent.com/35680445/38251728-da6d28e4-3784-11e8-8bf1-bc81f44d2301.png)


and we have pay the fee for Technical consultation when we buy the sinara

**Comment by sbourdeauducq** [comment]
What is your email address?

**Comment by mingshenli** [comment]
limsh9@mail2.sysu.edu.cn

**Comment by mingshenli** [comment]
no. actually I make a python3.5 environment as the documentation says. should I create a python 3.6 environment use `conda create -n py36 python=3.6 anaconda`?

**Comment by sbourdeauducq** [comment]
I meant **ARTIQ*** 3.6, not Python 3.6.

**Comment by mingshenli** [comment]
no, I use artiq3.4. how to update? 
![qq 20180403223347](https://user-images.githubusercontent.com/35680445/38255446-5c8ddc5c-378e-11e8-86b4-62c1207d1973.png)
the order can not be used for a long time, says files can not be found.

**Comment by sbourdeauducq** [comment]
``conda create -n artiq-new artiq=3.6 artiq-kc705-nist_clock=3.6``

**Comment by mingshenli** [comment]
ok. after installing 3.6 as the order you give,  I will try it on a new version, hoping the new version will solve the problem. the installing will take a long time, I will let you know once I reproduce the step above.
thanks alot.

**Comment by sbourdeauducq** [comment]
The software also behaves correctly when I make a copy of the experiment ``Management tutorial`` (renames one of them, they both can still run, and there is no bug when rescanning the repository).

**Comment by sbourdeauducq** [comment]
Also reflash the board after upgrading.

**Comment by mingshenli** [comment]
ok. hope the upgrading will solve the problem.
thanks.

**Comment by sbourdeauducq** [comment]
It should fix the cygwin one, but nothing has changed regarding repository management, so I think the experiment name issue will persist.

**Comment by mingshenli** [comment]
here is every move:
`activate artiq-new`;   `cd C:\Users\18926\AppData\Local\conda\conda\envs\artiq-new\artiq-master`
`artiq_master`;  and open a new cmd, activate the artiq-new, ` cd C:\Users\18926\AppData\Local\conda\conda\envs\artiq-new\artiq-master` ; `artiq_dashboard`

![qq 20180404142418](https://user-images.githubusercontent.com/35680445/38291638-29d3c756-3813-11e8-9591-b273d9f61749.png)
and then I click submit, the experiment is same as above,
all of the log since the dashboard been opened:(the chinese means ''error sem timeout''

![qq 20180404142901](https://user-images.githubusercontent.com/35680445/38291854-16cd15e4-3814-11e8-88a3-15e29ffbb629.png)


![qq 20180404142801](https://user-images.githubusercontent.com/35680445/38292006-a31125e0-3814-11e8-93fb-3fd7f35217a5.png)

**Comment by sbourdeauducq** [comment]
So, it seems that the first problem you were reporting is resolved: There are no more incorrect names in the explorer, and the experiment starts when you submit it.

The two errors you now have are:
1. the dashboard failing to connect to the core device for moninj (i.e. TTL and DDS panels)
2. the experiment, once started, failing to connect to the core device.

Is the core device (the KC705 board) properly set up and connected to the network? Can you ping it? Did you set its IP address in ``device_db.py``?

**Comment by mingshenli** [comment]
well, we didn't connect to the kc705(as you said it do not have to)
and the problem is ''get worker exception'', and, the ttl window has no respons

**Comment by sbourdeauducq** [comment]
What I meant is, if your experiment does not need a core device, then you do not need a core device for the dashboard either. The experiment you are currently running needs a core device.

**Comment by mingshenli** [comment]
so the dashboard can not simulate the board?

**Comment by sbourdeauducq** [comment]
There is limited simulation support (see ``artiq/examples/no_hardware/repository/simple_simulation.py``), but no one finds it very useful, so it is not very developed and in particular not integrated with the dashboard.

**Comment by sbourdeauducq** [comment]
Arguably, blinking the TTL panel when no device is connected and an experiment with the core device is run is not a useful feature.

**Comment by mingshenli** [comment]
all right, I will get a kc705 and test it.(unluckily I have to wait for few days and that is why I hope the dashboard can simulate the board).

**Comment by sbourdeauducq** [comment]
Try experiments that do not need the core device and play with the datasets and applets, see e.g. ``artiq/examples/no_hardware/repository/flopping_f_simulation.py``.

**Comment by mingshenli** [comment]
that seems work well.

**Comment by mingshenli** [comment]
by the way, where can I find the pin setting in the documentation so that I can know where to use a Oscilloscope to detect the ttl out? Did the documentation online say it?

**Comment by sbourdeauducq** [comment]
https://github.com/m-labs/artiq/blob/master/artiq/gateware/nist_clock.py
https://github.com/m-labs/artiq/blob/master/artiq/gateware/nist_qc2.py
and the manual.

**Comment by sbourdeauducq** [comment]
Note that ttl, 0 in nist_clock is not necessarily ttl0 in the device database (check the manual).

**Comment by mingshenli** [comment]
I find that 'binaries' is in the wrong dictionary.

**Comment by mingshenli** [comment]
it suppose to be C:\Users\18926\AppData\Local\conda\conda\envs\artiq-new\lib\site-packages\artiq\binaries,
but now in C:\Users\18926\AppData\Local\conda\conda\envs\artiq-new\lib\python3.5\site-packages\artiq

**Comment by sbourdeauducq** [comment]
Can you give more details? What exactly did you do?

**Comment by mingshenli** [comment]
well， I 'm not sure what happened, maybe there are too many version artiq on my computer so the artiq-new raise some error. However, now I remove all the old artiq and install the 3.6 and all the problem solved.

**Comment by mingshenli** [comment]
Yes I am in it. thanks a lot.
