### ISSUE TITLE
Ethernet SFP0 LED not working on Kasli 1.1

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#982]
The Ethernet SFP0 LED is always off with Kasli 1.1, but works with 1.0. The Ethernet link works correctly on 1.1.
The code driving the LED is in MiSoC.

**Comment by gkasprow** [comment]
The LED   and a few more signals assignment changed between versions.

**Comment by sbourdeauducq** [comment]
MOD_PRESENT polarity is different between the two versions.
