### ISSUE TITLE
board binaries under windows

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#989]
Under Windows, the artiq-board binaries don't end up where artiq_flash expects them.
I tested this on the win7-experimental VM

```
$ conda create -c m-labs/label/dev -c m-labs -c defaults -c conda-forge -n artiq-test artiq-kasli-opticlock=4.0.dev=877+git73fa5722
(installs all the correct versions, openocd, bscan-spi-bitstreams, artiq, artiq-kasli-opticlock)
$ activate artiq-test
$ artiq_flash -t kasli -V opticlock
```

![image](https://user-images.githubusercontent.com/1338946/39378887-ee657b84-4a59-11e8-9454-0bd77218591f.png)

They end up in `c:\miniconda64\envs\artiq-test\lib\python3.5\site-packages\artiq\binaries`. That's a `python3.5` too much.
Manually moving them makes artiq_flash work.

**Comment by jordens** [comment]
Does it even make special sense to put them into python/site-packages? Why not `$PREFIX/share/artiq` in analogy to bscan-spi-bitstreams?

**Comment by jordens** [comment]
This is still the case as of 9715f774.
```
-rwxrwxr-x buildbot/buildbot 76744 2018-05-23 13:57 lib/python3.5/site-packages/artiq/binaries/kasli-opticlock/bootloader.bin
-rw-rw-r-- buildbot/buildbot 630396 2018-05-23 13:57 lib/python3.5/site-packages/artiq/binaries/kasli-opticlock/runtime.fbi
-rw-rw-r-- buildbot/buildbot 2485166 2018-05-23 13:57 lib/python3.5/site-packages/artiq/binaries/kasli-opticlock/top.bit
-rwxrwxr-x buildbot/buildbot 5328348 2018-05-23 13:57 lib/python3.5/site-packages/artiq/binaries/kasli-opticlock/runtime.elf
```

**Comment by sbourdeauducq** [comment]
@jordens I'm not sure if bugs that are frustrating but have a simple workaround should be labeled as "critical".
@whitequark Since fixing this on the conda side is causing another avalanche of time-consuming problems, maybe artiq_flash can simply work around whatever conda is doing, by looking at both possible locations?

**Comment by whitequark** [comment]
@sbourdeauducq I believe I fixed it.

**Comment by jordens** [comment]
I am following the procedures I know from other projects. Critical refers to the impact and the urgency, not the complexity of the fix or the workaround. A single character typo may well be critical because it breaks everything. Even if every user is trivially able to hack that into the files as installed.
