### ISSUE TITLE
Rename asyncserial

### ISSUE THREAD

**Issue by whitequark** [m-labs/artiq#994]
There is now an asyncserial on pip, https://github.com/xvzf/asyncserial-py, and it will get installed if m-labs/asyncserial isn't installed either manually via setuptools or conda. Once installed, eggs have priority over conda packages, so this leads to very obscure errors.

**Comment by sbourdeauducq** [comment]
Nix sandboxing, which prevents setup.py from accessing the network, avoids this problem.
